## prose_characters.rpy - Act 1 generated speaker definitions
##
## Trimmed to speakers used by the public Act 1 demo.

define a_voice = Character("Voice", color="#888888", what_prefix="\"", what_suffix="\"")
define another_worker = Character("Another Worker", color="#888888", what_prefix="\"", what_suffix="\"")
define arbiter = Character("Arbiter", color="#888888", what_prefix="\"", what_suffix="\"")
define arbitrator = Character("Arbitrator", color="#888888", what_prefix="\"", what_suffix="\"")
define attendant = Character("Attendant", color="#888888", what_prefix="\"", what_suffix="\"")
define bram = Character("Bram", color="#888888", what_prefix="\"", what_suffix="\"")
define broad_one = Character("Broad One", color="#888888", what_prefix="\"", what_suffix="\"")
define broker = Character("Broker", color="#888888", what_prefix="\"", what_suffix="\"")
define client = Character("Client", color="#888888", what_prefix="\"", what_suffix="\"")
define coil = Character("Coil", color="#888888", what_prefix="\"", what_suffix="\"")
define contact = Character("Contact", color="#888888", what_prefix="\"", what_suffix="\"")
define contractor = Character("Contractor", color="#888888", what_prefix="\"", what_suffix="\"")
define darros = Character("Darros", color="#888888", what_prefix="\"", what_suffix="\"")
define della = Character("Della", color="#888888", what_prefix="\"", what_suffix="\"")
define desk_attendant = Character("Desk Attendant", color="#888888", what_prefix="\"", what_suffix="\"")
define elder = Character("Elder", color="#888888", what_prefix="\"", what_suffix="\"")
define fourth_pirate = Character("Fourth Pirate", color="#888888", what_prefix="\"", what_suffix="\"")
define governor = Character("Governor", color="#888888", what_prefix="\"", what_suffix="\"")
define harren = Character("Harren", color="#888888", what_prefix="\"", what_suffix="\"")
define labor_rep = Character("Labor Rep", color="#888888", what_prefix="\"", what_suffix="\"")
define line_foreman = Character("Line Foreman", color="#888888", what_prefix="\"", what_suffix="\"")
define man = Character("Man", color="#888888", what_prefix="\"", what_suffix="\"")
define medical_ai = Character("Medical AI", color="#888888", what_prefix="\"", what_suffix="\"")
define mira = Character("Mira", color="#888888", what_prefix="\"", what_suffix="\"")
define new_worker = Character("New Worker", color="#888888", what_prefix="\"", what_suffix="\"")
define official = Character("Official", color="#888888", what_prefix="\"", what_suffix="\"")
define older_woman = Character("Older Woman", color="#888888", what_prefix="\"", what_suffix="\"")
define other_captain = Character("Other Captain", color="#888888", what_prefix="\"", what_suffix="\"")
define other_crew_voice = Character("Other Crew Voice", color="#888888", what_prefix="\"", what_suffix="\"")
define partner = Character("Partner", color="#888888", what_prefix="\"", what_suffix="\"")
define representative = Character("Representative", color="#888888", what_prefix="\"", what_suffix="\"")
define security_lead = Character("Security Lead", color="#888888", what_prefix="\"", what_suffix="\"")
define supervisor = Character("Supervisor", color="#888888", what_prefix="\"", what_suffix="\"")
define tablet_woman = Character("Tablet Woman", color="#888888", what_prefix="\"", what_suffix="\"")
define tella = Character("Tella", color="#888888", what_prefix="\"", what_suffix="\"")
define their_admin = Character("Their Admin", color="#888888", what_prefix="\"", what_suffix="\"")
define their_lead = Character("Their Lead", color="#888888", what_prefix="\"", what_suffix="\"")
define their_medic = Character("Their Medic", color="#888888", what_prefix="\"", what_suffix="\"")
define their_pilot = Character("Their Pilot", color="#888888", what_prefix="\"", what_suffix="\"")
define their_tech = Character("Their Tech", color="#888888", what_prefix="\"", what_suffix="\"")
define unknown_voice = Character("Unknown Voice", color="#888888", what_prefix="\"", what_suffix="\"")
define vendor = Character("Vendor", color="#888888", what_prefix="\"", what_suffix="\"")
define woman = Character("Woman", color="#888888", what_prefix="\"", what_suffix="\"")
define writbound_man = Character("Writbound Man", color="#888888", what_prefix="\"", what_suffix="\"")
define writbound_woman = Character("Writbound Woman", color="#888888", what_prefix="\"", what_suffix="\"")
define young_worker = Character("Young Worker", color="#888888", what_prefix="\"", what_suffix="\"")
