## Generated from 14c_bridge_transit_ritual.md by convert_prose.py
## Do not edit manually — re-run converter after prose changes

label act1_14c_bridge_transit_ritual:
    pause 0.3
    narrator "{i}The bridge smells like coffee and ozone and focus.{/i}"
    narrator "{i}Jalen sits in the pilot cradle, spine straight, hands light on the controls like anything heavier would insult the ship.{/i}"
    narrator "{i}Elisira stands behind them with a slate, posture relaxed in the way that means she is not relaxed.{/i}"
    narrator "{i}Vesper has one hand on a rail and the other on a datapad full of forms that never stop wanting signatures.{/i}"
    narrator "{i}Rho leans in the doorway with a mug and the expression of someone prepared to fight the universe with caffeine.{/i}"
    narrator "{i}Elia is sprawled near weapons control, boots on a brace, looking bored on purpose.{/i}"
    narrator "{i}Avyanna takes the last open station and tries not to look like she is begging to be allowed to exist there.{/i}"
    narrator "Bridge means responsibility. Responsibility means they can be angry at you."
    jalen "{i}[[without looking back]]{/i} Strap in."
    narrator "{i}Avyanna straps in immediately.{/i}"
    narrator "{i}Then stops herself.{/i}"
    narrator "{i}Elia's drill rises like a reflex with teeth.{/i}"
    avyanna "{i}[[careful]]{/i} Why."
    narrator "{i}Jalen's mouth twitches. Not quite a smile.{/i}"
    jalen "Because this corridor is spiteful."
    elia "{i}[[bright]]{/i} Because the map lies."
    elisira "Because the lane has been shifting."
    vesper "Because insurance pretends it's weather."
    rho "Because if you hit a seam wrong, you bite your tongue off."
    narrator "{i}Avyanna blinks.{/i}"
    avyanna "That's... all the same answer."
    elia "Correct. Welcome to the galaxy."

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}Jalen taps the console. A route path blooms on the holo-blue line through blackness, annotated with numbers and warnings.{/i}"
    narrator "{{color=#43d4a8}}<CINNAMON.EXE// OBSERVATION: corridor stability rating \"marginal\" | NOTE: recommended speed reduction 12%% | INFERENCE: reduced peak shear | CONFIDENCE: 0.84>{{/color}}"
    narrator "{{color=#43d4a8}}<WAFFLE.BAT// COMMENTARY: marginal is my favorite kind of safe>{{/color}}"
    narrator "{{color=#43d4a8}}<BUBBLES// REMINDER: keep limbs inside existence at all times>{{/color}}"
    elia "{i}[[to the air]]{/i} Thank you, Bubbles. Very inspiring."
    bubbles "{i}[[over comm]]{/i} You are welcome."
    narrator "{i}The ship shifts. A subtle pressure change, like the universe leaning in to listen.{/i}"
    narrator "{i}The stars on the forward display smear for a heartbeat.{/i}"
    narrator "{i}Avyanna's stomach drops.{/i}"
    narrator "Mine collapse."
    narrator "{i}The memory tries to overlay reality: rock groaning, dust filling lungs, the moment the ceiling decides to become ground.{/i}"
    narrator "{i}Her hands clench on the armrests.{/i}"
    narrator "{i}She counts exits without thinking.{/i}"
    narrator "{i}There are none. It's a bridge. It's a box. It's a trap.{/i}"
    vesper "{i}[[quiet, not looking at her]]{/i} Check."
    narrator "{i}Avyanna swallows.{/i}"
    avyanna "{i}[[too fast]]{/i} Green."
    narrator "{i}A beat.{/i}"
    avyanna "{i}[[correcting]]{/i} Yellow."
    narrator "{i}Vesper's hand shifts-doesn't touch her, just moves closer to the rail between them, a visible choice not to invade.{/i}"
    vesper "Thank you."
    narrator "Thank you for telling the truth. Not thank you for being okay."
    narrator "{i}Jalen's voice stays calm, which is its own kind of weapon.{/i}"
    jalen "Drift left two degrees. Hold. Hold."
    narrator "{i}The ship responds like it likes being spoken to with respect.{/i}"
    narrator "{i}Pressure eases.{/i}"
    narrator "{i}Avyanna's lungs remember they are allowed to take air.{/i}"
    rho "{i}[[sipping]]{/i} See. Fine."
    narrator "{{color=#43d4a8}}<CINNAMON.EXE// RESPONSE: \"fine\" is not a metric>{{/color}}"
    rho "{i}[[without missing a beat]]{/i} \"Operationally adequate.\""
    narrator "{{color=#43d4a8}}<CINNAMON.EXE// ACCEPTABLE>{{/color}}"

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}A small shudder runs through the deck plates.{/i}"
    narrator "{i}Not violent. Just... a seam.{/i}"
    elisira "{i}[[to Jalen]]{/i} That was early."
    jalen "Yeah."
    jalen "{i}[[flat]]{/i} The corridor is lying today."
    elia "{i}[[cheerful]]{/i} I love it when the universe has personality."
    vesper "It's not personality. It's incentives."
    elia "{i}[[glancing over]]{/i} Everything is incentives with you."
    vesper "{i}[[dry]]{/i} Everything is incentives with everyone. Most people just don't admit it."
    narrator "{i}Avyanna watches them argue like it's a ritual. No one is afraid of disagreement here.{/i}"
    narrator "In the mine, arguing meant punishment. Here it means... mapping."
    narrator "{i}Jalen flicks a switch. The display shifts-blue line, but now with a second overlay: a thin gray shadow of possible alternatives.{/i}"
    avyanna "What's that."
    jalen "Official route."
    jalen "And what the ship thinks the route is."
    avyanna "{i}[[quiet]]{/i} Those aren't the same."
    jalen "{i}[[looking at her for the first time]]{/i} Now you're learning."

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}They ride the corridor like a river that dislikes boats.{/i}"
    narrator "{i}Avyanna's job is small.{/i}"
    narrator "{i}Read out sensor warnings when Cinnamon flags them.{/i}"
    narrator "{i}Repeat Elisira's directions back so no one mishears.{/i}"
    narrator "{i}Keep a log of time-stamps the way Vesper taught her: claim, source, when.{/i}"
    narrator "{i}Useful. Quiet. Not invisible.{/i}"
    narrator "{i}At one point, the ship lurches harder.{/i}"
    narrator "{i}Avyanna's vision narrows.{/i}"
    narrator "{i}The mine tries to come back.{/i}"
    narrator "{i}Rho's voice cuts in, rough and real.{/i}"
    rho "Avy. Breathe."
    narrator "{i}Avyanna inhales.{/i}"
    narrator "{i}Jalen exhales at the same time-slow on purpose.{/i}"
    narrator "{i}It pulls her rhythm with it, like gravity.{/i}"
    narrator "{i}She holds on.{/i}"
    narrator "{i}The corridor releases them with a final shiver, grudgingly.{/i}"
    narrator "{{color=#43d4a8}}<CINNAMON.EXE// OBSERVATION: stability improving | INFERENCE: seam passed | CONFIDENCE: 0.88>{{/color}}"
    elia "{i}[[stretching]]{/i} That was disappointingly non-lethal."
    elisira "{i}[[without looking at her]]{/i} We can arrange lethal if you're bored."
    elia "{i}[[delighted]]{/i} She loves me."
    narrator "{i}Avyanna's mouth twitches.{/i}"
    narrator "{i}It's almost a smile.{/i}"
    narrator "{i}She files that too.{/i}"

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}Afterward, nobody disperses like they're fleeing the smell of fear.{/i}"
    narrator "{i}Jalen eases the ship down into a quiet stretch of corridor-space-stable enough to breathe, unstable enough to keep respect.{/i}"
    elisira "{i}[[to Avyanna]]{/i} Debrief."
    narrator "{i}Avyanna's shoulders go rigid.{/i}"
    narrator "Debrief means you explain why you failed."
    avyanna "I-"
    narrator "{i}Elisira waits, patient in the way that doesn't let you hide behind panic.{/i}"
    avyanna "{i}[[working]]{/i} We hit a seam early. The deck shuddered before the display predicted it. The pressure change came before the warning ping."
    elisira "Good."
    avyanna "Jalen adjusted two degrees left and reduced speed. Cinnamon flagged \"marginal\" stability, but it improved after the seam."
    elisira "What did your body do."
    narrator "{i}Avyanna blinks.{/i}"
    avyanna "My body-"
    vesper "{i}[[quiet]]{/i} This is evidence too."
    narrator "{i}Avyanna swallows.{/i}"
    avyanna "My hands clenched. I went cold. I... counted exits."
    narrator "{i}Elia makes a small sound, not quite a joke.{/i}"
    elia "Same."
    avyanna "{i}[[startled]]{/i} You count exits."
    elia "{i}[[bright]]{/i} I count fun. Different category."
    elisira "{i}[[flat]]{/i} Elia."
    elia "{i}[[innocent]]{/i} I was validating."
    narrator "{i}Avyanna's mouth twitches again.{/i}"
    narrator "{i}Rho drinks his coffee like it's a shield and watches her carefully, as if counting how long it takes her to come back.{/i}"
    rho "You breathed when I told you."
    avyanna "Yes."
    rho "Good."
    narrator "{{color=#43d4a8}}<CINNAMON.EXE// OBSERVATION: trainee returned to baseline within 46 seconds | INFERENCE: recovery improving | CONFIDENCE: 0.81>{{/color}}"
    narrator "{i}Avyanna looks at the telemetry and feels, unexpectedly, protected by being measured without being judged.{/i}"
    vesper "Log it."
    avyanna "{i}[[automatic]]{/i} Yes."
    narrator "{i}She catches herself.{/i}"
    avyanna "Why."
    vesper "Because next time your body tells you a story, we compare it to the data."
    vesper "If the story is wrong, we correct it. If the story is right, we prepare."
    avyanna "{i}[[quiet]]{/i} Memory lies under stress."
    vesper "{i}[[a small nod]]{/i} Exactly."

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}Later, in the corridor outside the bridge, Avyanna stops beside a wall panel and opens her notebook.{/i}"
    narrator "{i}She writes in block letters, the way Vesper taught her to write claims:{/i}"
    narrator "{{color=#808090}}{b}CLAIM:{/b} corridor seam occurred early{{/color}}"
    narrator "{i}>{/i}"
    narrator "{{color=#808090}}{b}OBSERVATION:{/b} deck shudder preceded warning ping{{/color}}"
    narrator "{i}>{/i}"
    narrator "{{color=#808090}}{b}RESPONSE:{/b} speed reduction + lateral correction{{/color}}"
    narrator "{i}>{/i}"
    narrator "{{color=#808090}}{b}BODY:{/b} cold, exit-counting, then recovery{{/color}}"
    narrator "{i}She stares at the last line.{/i}"
    narrator "Body: witness. Not enemy."
    narrator "{i}A shadow falls over the page.{/i}"
    narrator "{i}Jalen stands there, hands in pockets, pretending this isn't care.{/i}"
    jalen "You did fine."
    avyanna "{i}[[startled]]{/i} Fine is not a metric."
    narrator "{i}Jalen's mouth twitches.{/i}"
    jalen "Operationally adequate."
    avyanna "{i}[[quiet]]{/i} Better."
    jalen "Don't make it a habit."
    narrator "{i}They walk away before Avyanna can turn gratitude into a performance.{/i}"
    return
