## Generated from 19c_receipt_practice.md by convert_prose.py
## Do not edit manually — re-run converter after prose changes

label act1_19c_receipt_practice:
    pause 0.3
    narrator "{i}Vesper's office is too orderly to be natural.{/i}"
    narrator "{i}Shelves. Binders. A desk that looks like it has never been used for anything except war.{/i}"
    narrator "{i}Avyanna sits across from Vesper with a stack of printouts and a pen that feels heavier than it should.{/i}"
    vesper "Tell me what you saw."
    narrator "{i}Avyanna's jaw tightens on instinct.{/i}"
    narrator "If I tell the truth wrong, it becomes a weapon aimed at me."
    avyanna "Which part."
    vesper "The part you are scared to put into words."
    narrator "{i}Avyanna swallows.{/i}"
    avyanna "The station clerk tried to make me sign \"voluntary disclosure.\""
    vesper "Good. That's a claim."
    avyanna "{i}[[baffled]]{/i} That's not-"
    vesper "It is. \"Clerk attempted coercion.\" Claim."
    narrator "{i}Vesper taps the printouts.{/i}"
    vesper "Evidence."
    avyanna "The slip. The camera footage request Elisira filed. The time stamp on the terminal log."
    vesper "Good."
    vesper "Inference."
    avyanna "They were fishing. For identity. For contacts."
    vesper "Next step."
    avyanna "Report it. Archive it. Don't sign."
    narrator "{i}Vesper's mouth twitches.{/i}"
    vesper "You're learning."
    narrator "{i}Avyanna's chest tightens.{/i}"
    avyanna "I'm trying."
    vesper "Trying is a verb. Keep using it."

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}Vesper slides a new printout toward her.{/i}"
    narrator "{i}Aurum-coded header. Not the mine's logo, exactly-cleaner, but the same colors.{/i}"
    narrator "{i}Avyanna's vision tunnels.{/i}"
    narrator "{i}The room tilts.{/i}"
    narrator "No."
    narrator "{i}Her hands go cold.{/i}"
    vesper "Avyanna. Eyes on me."
    narrator "{i}Avyanna forces her gaze up.{/i}"
    avyanna "{i}[[thin]]{/i} That looks like-"
    vesper "Aurum."
    avyanna "{i}[[breathing wrong]]{/i} They're here."
    vesper "No."
    vesper "Not physically."
    vesper "It's a record artifact. A data style. A mimic."
    narrator "{i}Vesper's voice stays calm on purpose.{/i}"
    vesper "Check."
    avyanna "{i}[[after a beat]]{/i} Yellow."
    vesper "Good. Stay with yellow."
    narrator "{i}Vesper does not touch her.{/i}"
    narrator "{i}She doesn't have to.{/i}"
    narrator "{i}She moves the printout away, flips it face-down.{/i}"
    vesper "We don't process trauma by pretending it isn't there."
    vesper "We process it by turning it into something that can be handled."
    avyanna "That sounds like you."
    vesper "It is me."

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}Vesper opens a binder and pulls out a template.{/i}"
    narrator "{{color=#808090}}{b}WITNESS STATEMENT (DRAFT){/b}{{/color}}"
    narrator "{i}>{/i}"
    narrator "{{color=#808090}}{i}Claim{/i}{{/color}}"
    narrator "{i}>{/i}"
    narrator "{{color=#808090}}{i}Evidence{/i}{{/color}}"
    narrator "{i}>{/i}"
    narrator "{{color=#808090}}{i}Inference{/i}{{/color}}"
    narrator "{i}>{/i}"
    narrator "{{color=#808090}}{i}Confounders{/i}{{/color}}"
    narrator "{i}>{/i}"
    narrator "{{color=#808090}}{i}What would prove me wrong{/i}{{/color}}"
    avyanna "Cinnamon would like that."
    vesper "Cinnamon does like that."
    vesper "Now."
    vesper "We're going to practice on something that won't kill you if you get it wrong."
    avyanna "{i}[[dry]]{/i} That's generous."
    vesper "It's responsible."
    narrator "{i}Avyanna picks up her pen.{/i}"
    narrator "{i}Her hand still shakes, but she can write through it.{/i}"
    avyanna "Claim: the mine's medical bay neglected workers on purpose."
    vesper "Evidence."
    narrator "{i}Avyanna's voice goes quieter.{/i}"
    avyanna "The logs. The ration schedule. The number of collapsed people per shift. The way they stamped \"noncompliant\" on anyone who asked for painkillers."
    vesper "Inference."
    avyanna "The neglect was policy. Not failure."
    vesper "Confounders."
    narrator "{i}Avyanna freezes.{/i}"
    vesper "This is where you stop being a victim of your own certainty."
    avyanna "{i}[[working]]{/i} Confounders... shortages. Staffing. Flicker day malfunctions."
    vesper "Good."
    vesper "What would prove you wrong."
    avyanna "A supply manifest showing adequate medicine. A record of workers treated promptly."
    vesper "And if those exist."
    avyanna "Then I'm wrong."
    narrator "{i}The words taste strange in her mouth.{/i}"
    narrator "Wrong means you die."
    narrator "{i}Here, wrong means: adjust.{/i}"
    vesper "If you can be proven wrong, you can be trusted."
    avyanna "That's... backwards."
    vesper "It's adversarial."
    vesper "The people who can't be wrong are trying to sell you something."

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}A pause.{/i}"
    narrator "{i}Avyanna stares at the blank space on her template labeled WITNESS STATEMENT and feels something in her chest shift.{/i}"
    avyanna "This is... how you fight."
    vesper "This is one way."
    vesper "Another way is Elia."
    avyanna "{i}[[a small, real laugh]]{/i} Yes."
    narrator "{i}Vesper stands, goes to the shelf, and takes down a thin folder.{/i}"
    vesper "Tomorrow we go to arbitration."
    vesper "Today we build the spine."
    narrator "{i}She sets the folder in front of Avyanna.{/i}"
    vesper "No heroics."
    avyanna "{i}[[soft]]{/i} Just receipts."
    vesper "Just receipts."
    narrator "{i}Avyanna opens the folder.{/i}"
    narrator "{i}This time, the paper doesn't feel like a trap.{/i}"
    narrator "{i}It feels like a handle.{/i}"

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}Vesper doesn't let the moment turn sentimental.{/i}"
    narrator "{i}She flips to a new section in the binder and slides it across.{/i}"
    narrator "{{color=#808090}}{b}CROSS-EXAMINATION PREP{/b}{{/color}}"
    narrator "{i}>{/i}"
    narrator "{{color=#808090}}{i}If they say you're lying, what do you point to?{/i}{{/color}}"
    narrator "{i}>{/i}"
    narrator "{{color=#808090}}{i}If they say you misremembered, what do you point to?{/i}{{/color}}"
    narrator "{i}>{/i}"
    narrator "{{color=#808090}}{i}If they say it's \"standard,\" what do you ask?{/i}{{/color}}"
    avyanna "{i}[[reading]]{/i} What do you ask."
    vesper "\"Under which jurisdiction. Enforced by whom. Consequence for refusal.\""
    avyanna "{i}[[quiet]]{/i} That's... the spine."
    vesper "Yes."
    vesper "When someone is trying to drown you in language, you don't swim."
    vesper "You stand on three questions."
    narrator "{i}Avyanna's pen hovers.{/i}"
    avyanna "In the mine, questions got you noticed."
    vesper "Here, questions keep you alive."
    narrator "{i}A beat.{/i}"
    vesper "Not just physically."
    narrator "{i}Avyanna swallows.{/i}"
    avyanna "This feels like fighting without... touching anyone."
    vesper "It is."
    vesper "It's slower than Elia. But it leaves bodies intact."
    avyanna "{i}[[dry]]{/i} Sometimes."
    narrator "{i}Vesper's mouth twitches.{/i}"
    vesper "Sometimes."

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}Vesper pulls a small index card from a box and slides it toward Avyanna.{/i}"
    narrator "{{color=#808090}}{b}YOUR JOB IN THE ROOM{/b}{{/color}}"
    narrator "{i}>{/i}"
    narrator "{{color=#808090}}- say what you saw\n- don't guess\n- if you don't know, say you don't know\n- if you need a minute, ask for it{{/color}}"
    avyanna "{i}[[soft]]{/i} I can ask for a minute."
    vesper "Yes."
    vesper "If anyone tries to deny you that, I will make it expensive."
    narrator "{i}Avyanna's throat tightens.{/i}"
    narrator "Expensive. Protective. Not ownership."

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}Vesper taps the face-down Aurum-coded printout with one knuckle.{/i}"
    vesper "This."
    avyanna "{i}[[tense]]{/i} Yes."
    vesper "You did not break when you saw it."
    avyanna "I almost did."
    vesper "\"Almost\" is data."
    avyanna "That's... also you."
    vesper "{i}[[without apology]]{/i} Yes."
    narrator "{i}She pauses.{/i}"
    vesper "When you're in the room tomorrow and something tries to pull you back into the mine-"
    avyanna "Like a smell. Like a word."
    vesper "-you do not have to white-knuckle it."
    vesper "You can say: \"I need to pause.\""
    avyanna "{i}[[quiet]]{/i} And nobody will-"
    vesper "No penalty."
    narrator "{i}The phrase lands like a seal on paper.{/i}"

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}Avyanna writes it down.{/i}"
    narrator "{{color=#808090}}{b}NO PENALTY{/b}{{/color}}"
    narrator "{i}Not in Cinnamon's font. In her own.{/i}"
    narrator "{i}She looks up at Vesper.{/i}"
    avyanna "Thank you."
    vesper "{i}[[measured]]{/i} You're welcome."
    narrator "{i}Vesper straightens Avyanna's collar without asking. Then catches herself.{/i}"
    vesper "Go drink water."
    avyanna "{i}[[blinking]]{/i} That's an order."
    vesper "It's medical advice."
    avyanna "{i}[[a small smile]]{/i} Who enforces it."
    vesper "Nyx."
    narrator "{i}Avyanna laughs.{/i}"
    vesper "And also me."
    narrator "{i}The second part is said so quietly it almost doesn't count.{/i}"
    narrator "{i}Almost.{/i}"
    narrator "{i}Avyanna gathers the folder and the index card like they're equipment.{/i}"
    narrator "{i}Because they are.{/i}"
    narrator "{i}She leaves Vesper's office with her spine built from paper and the strange sensation of being allowed to carry it.{/i}"
    ## Progression state
    $ relationship_manager.change_affinity("elisira", 2)
    return
