## Generated from 14_dumb_reliability.md by convert_prose.py
## Do not edit manually — re-run converter after prose changes

label act1_14_dumb_reliability:
    narrator "{{color=#808090}}{b}LUMEN THIEF - ENGINEERING TRAINING MODULE (FIELD COPY):{/b}\n{i}Subject: Dumb Reliability{/i}\n{i}Instructor: Jalen Kade{/i}\n{i}Trainee: Avyanna Lagrange{/i}\n{i}Summary: Magic fails. Corridors collapse. Guns jam. The wrench works.{/i}\n{i}Rule 1: Know where the mechanical override lives.{/i}\n{i}Rule 2: Practice it before you need it.{/i}\n{i}Rule 3: If you can't fix it with your hands, at least know who can.{/i}\n{i}Addendum: If someone tells you \"nothing ever breaks,\" they are either lying or trying to sell you something.{/i}{{/color}}"
    pause 0.3
    narrator "{i}The maintenance corridors don't pretend to be kind.{/i}"
    narrator "{i}They are narrow and stripped. Conduit bundles hang like exposed nerves. The air tastes like hot dust and old lubricant and the faint chemical ghost of coolant that never fully leaves a ship once it's been there.{/i}"
    narrator "{i}Avyanna likes them anyway.{/i}"
    narrator "No carpet. No soft voice. No false promise."
    narrator "{i}Metal. Bolts. The honest language of things that hold or don't.{/i}"

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}Jalen is waiting at a hatch panel with their sleeves rolled up and a grease smear on their forearm like punctuation.{/i}"
    narrator "{i}They look up when she approaches, then look back down at the open toolkit.{/i}"
    jalen "You came."
    narrator "{i}No praise. No surprise. Just an observation that means: you showed up, so we proceed.{/i}"
    avyanna "You said fourteen hundred."
    jalen "I did. And you are currently not hiding in a vent. Two wins."
    narrator "{i}Avyanna stops herself from glancing at the ceiling grates. She fails. Looks anyway. Old habits have gravity.{/i}"
    narrator "{i}Jalen's mouth twitches. Not unkind.{/i}"
    jalen "Before we start-this gets cramped. If you want to tap out, you say so. No explanation required."
    narrator "{i}Avyanna's throat tightens around reflex.{/i}"
    narrator "In the Kennel, \"tap out\" meant you got replaced."
    avyanna "I can do cramped."
    jalen "I know. I'm not asking about ability. I'm asking about consent."
    narrator "{i}The word lands with a weight she isn't used to: heavy and clean.{/i}"
    narrator "{i}Avyanna nods once.{/i}"
    avyanna "Okay."
    jalen "Good. Grab the light."

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}The flashlight is old. The kind that can survive being dropped, kicked, and resented. Its casing is scarred. It still turns on.{/i}"
    narrator "{i}Avyanna takes it like it's fragile anyway.{/i}"
    narrator "Everything was fragile in the mine. Even the things built to hurt you."
    narrator "{i}Jalen pulls the hatch open. Hinges complain. The corridor breathes heat out of its throat.{/i}"
    jalen "This is the first lesson."
    narrator "{i}They point at a thick lever bolted to the frame-paint chipped from use.{/i}"
    jalen "See this? Mechanical override. No magic required. When everything goes wrong, this still works."
    narrator "{i}Avyanna stares.{/i}"
    narrator "{i}It looks like nothing. A lever. A piece of metal. A promise you can touch.{/i}"
    avyanna "What does it do."
    jalen "It forces a seal. If the smart lock glitches or the net goes down or the ship is busy screaming at the universe, you can still close a door."
    narrator "{i}They pull it partway. The lever fights back. Jalen wins anyway, patient strength.{/i}"
    narrator "{i}A lock clunks deeper in the wall. Not a polite beep. A physical acknowledgement.{/i}"
    narrator "{i}Avyanna's shoulders drop half a centimeter before she notices and re-tenses out of habit.{/i}"
    jalen "Your turn."
    narrator "{i}Avyanna steps in. The corridor narrows; the bulkhead leans close. She sets the light, angles it until Jalen's hands are lit and her own aren't shaking too obviously.{/i}"
    narrator "{i}Her palm finds the lever. Cold. Gritty with old paint.{/i}"
    narrator "This is real. This is real. This is real."
    narrator "{i}She pulls. The lever resists. For a heartbeat her body flashes to the Kennel: machinery that punished you for not being strong enough. Tools that existed to prove your weakness.{/i}"
    narrator "{i}Jalen waits. Doesn't touch. Doesn't \"help\" in the way that steals the lesson.{/i}"
    jalen "Use your legs. Your hips. Don't fight it with your wrists."
    narrator "{i}Avyanna tries again. This time the lever moves.{/i}"
    narrator "{i}Clunk.{/i}"
    narrator "{i}The sound hits her like relief.{/i}"
    avyanna "It... worked."
    jalen "Usually does."
    avyanna "Usually."
    jalen "Nothing is a hundred percent. That's why we have backups. Which is the second lesson."

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}They move deeper, into the ship's under-throat-between systems that keep people alive and systems that keep people comfortable.{/i}"
    narrator "{i}A vibration runs through the deck plates. The ship is in motion. Always in motion.{/i}"
    narrator "{i}Avyanna watches Jalen's hands. How they move without hesitation-like every screw has already introduced itself.{/i}"
    narrator "{i}Jalen tosses her a wrench.{/i}"
    avyanna "{i}[[startling, catching it]]{/i} I-"
    jalen "It's not a grenade."
    avyanna "Everything is a grenade on this ship."
    jalen "Fair."
    narrator "{i}Cooling beat: Jalen turns a bolt with a small, precise motion. The wrench in Avyanna's hand feels heavier than it should. Like responsibility. Like something that can be used or misused.{/i}"
    jalen "Rule of dumb reliability: if it can't be fixed with a wrench, at least make sure the thing that can be fixed with a wrench doesn't depend on it."
    narrator "{i}Avyanna frowns.{/i}"
    avyanna "That's... a sentence."
    jalen "Thank you. I made it myself."

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}They stop at a panel with a diagram stenciled onto it-lines and boxes and arrows. The ship explaining itself to anyone willing to listen.{/i}"
    narrator "{i}Jalen points at a cluster of labels.{/i}"
    jalen "Primary comms. Secondary comms. Tertiary comms. Emergency transmitter that works by being too stupid to fail."
    avyanna "Too stupid."
    jalen "No network handshake. No clever routing. Just power and signal and a piece of metal that refuses to be subtle."
    avyanna "That sounds like Elia."
    narrator "{i}Jalen snorts.{/i}"
    jalen "Elia is clever. She just hates admitting it."
    narrator "{i}They tap the emergency transmitter housing with their knuckle.{/i}"
    jalen "This is what I want you to remember."
    narrator "{i}Jalen's voice goes flatter, the humor cooling.{/i}"
    jalen "Magic fails. Corridors collapse. Guns jam. The wrench works."
    narrator "{i}The sentence isn't a slogan. It's an inventory list. A scar catalogued into words.{/i}"
    avyanna "The Lattice fails?"
    jalen "The Lattice is weather with paperwork. Sometimes it's kind. Sometimes it isn't. Sometimes it just..."
    narrator "{i}Their fingers hover over nothing, like they're waiting for the right word to arrive.{/i}"
    jalen "...stops cooperating."
    narrator "{i}Avyanna's mouth tastes metallic. She thinks of flicker days in the mine-machines stuttering, lights going wrong, supervisors calling it \"normal variance.\"{/i}"
    avyanna "Nyx said the corridor-load index can spike. CLI."
    jalen "Nyx is right. Nyx is usually right and it's annoying."
    narrator "{i}Jalen taps the nav display. A corridor route blinks amber.{/i}"
    jalen "But even without spikes, corridors shift. Gates misbehave. Maps lie. Sometimes a lane just closes and everyone pretends that's physics and not a choice someone made upstream."
    avyanna "Someone... made it close?"
    narrator "{i}Jalen's eyes flick to her. A quick scan: are you ready for this part.{/i}"
    jalen "Maybe. Sometimes it's just damage. Sometimes it's... politics. Either way, you end up in the same place."
    narrator "{i}They point with the wrench.{/i}"
    jalen "Stuck. Waiting. Breathing through a system you didn't build and can't fix."
    narrator "{i}Avyanna grips the flashlight harder.{/i}"
    avyanna "So you don't depend on it."
    jalen "You don't depend on anything you can't fix with your hands."
    narrator "{i}Then, softer-almost reluctantly, like the sentence costs.{/i}"
    jalen "Or with someone you trust."

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}They crawl into a service duct together. Jalen goes first. Avyanna follows, light held low.{/i}"
    narrator "{i}The metal is close. The air is warmer. Every breath tastes like machine skin.{/i}"
    narrator "{i}Avyanna keeps her elbows in. The Kennel taught her how to occupy as little space as possible.{/i}"
    narrator "{i}Jalen pauses ahead, just long enough that she almost bumps into their boots.{/i}"
    jalen "You okay back there?"
    narrator "{i}The question is absurdly gentle in a place this mechanical.{/i}"
    avyanna "Yes."
    jalen "That was a real yes or a Kennel yes?"
    narrator "{i}Her stomach clenches.{/i}"
    narrator "{i}She hates how well they see her. She hates how safe it makes her feel.{/i}"
    avyanna "...Real."
    jalen "Okay. Keep the light steady."

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}They stop at a junction where three cable runs braid together.{/i}"
    narrator "{i}Jalen unscrews a cover plate. The screws are old enough to be stubborn. Their hands are patient enough to outlast it.{/i}"
    narrator "{i}Inside: a mechanical governor wheel, small and precise, like a watch that keeps a ship breathing.{/i}"
    jalen "Life support regulator. It's mostly automated. Mostly."
    avyanna "Mostly is bad."
    jalen "Mostly is honest."
    narrator "{i}Jalen points to a manual adjustment knob.{/i}"
    jalen "If the smart control starts doing something creative, you can bring it back to baseline with this. No interface. No permissions. Just..."
    narrator "{i}They twist the knob a fraction. The ship's hum changes-so slightly Avyanna would have missed it a month ago. Now she hears everything.{/i}"
    jalen "...physics."
    narrator "{i}Avyanna's throat tightens.{/i}"
    narrator "The floor can hold you. The ship can hold you. The system can still betray you."

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}A faint chime ripples through the corridor speakers. Not an alarm. A notice.{/i}"
    narrator "{{color=#43d4a8}}<WAFFLE.BAT// ALERT: static bloom (minor) | ACTION: switching select subsystems to analog fallback | NOTE: boring is safe>{{/color}}"
    narrator "{i}The lights warm and cool in a tiny, seasick pulse. Somewhere deeper in the ship, a servo whines and then steadies.{/i}"
    jalen "See?"
    avyanna "That was... the Lattice?"
    jalen "That was the universe reminding us it hates being relied on."
    narrator "{i}They gesture at the governor wheel.{/i}"
    jalen "This still works."
    narrator "{i}Avyanna stares at the small knob like it's a religious object. She hates that part of her brain. The part that wants to worship anything that doesn't hurt her.{/i}"
    avyanna "It's dumb."
    jalen "Exactly."
    narrator "{i}They grin in the dark, where she can't see it, but she can hear it anyway.{/i}"
    jalen "Dumb reliability."

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}They back out of the duct. Avyanna's shoulders ache from holding herself small.{/i}"
    narrator "{i}Jalen drops to the deck with practiced ease. They offer a hand to Avyanna-not pulling, just a point of contact if she wants it.{/i}"
    narrator "{i}Avyanna takes it.{/i}"

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}They move into the sensor alcove next.{/i}"
    narrator "{i}Avyanna hesitates at the threshold.{/i}"
    narrator "{i}A small wall display is mounted above the paneling-stars and lines and a grid that looks like math trying to pretend it's pretty.{/i}"
    narrator "{i}She remembers tracing lights through dust, on the Kennel's night shifts. Three stars in a rough line. A shape she kept seeing and never got to name.{/i}"
    avyanna "{i}[[quiet]]{/i} Do the stars have... names."
    narrator "{i}Jalen pauses, then looks up at the display like it's an old argument.{/i}"
    jalen "Depends who's selling you the map."
    avyanna "That's not an answer."
    jalen "It's the only honest one."
    narrator "{i}They point at the three-star line.{/i}"
    jalen "Some stations call that \"good luck.\""
    jalen "Some call it \"home.\""
    jalen "Some don't name it at all because naming makes people think they own a thing."
    avyanna "{i}[[frowning]]{/i} So what do you call it."
    jalen "Coordinates."
    narrator "{i}They tap the screen. The pretty shape collapses into numbers and a reference grid.{/i}"
    jalen "A name is a handle."
    jalen "A coordinate is a location."
    jalen "If you want to survive corridors, learn the difference."
    narrator "{i}Avyanna's throat tightens with something that isn't fear.{/i}"
    narrator "Learn the difference."
    avyanna "The mine didn't teach-"
    jalen "Of course it didn't."
    narrator "{i}Their voice goes dry and tired for half a second.{/i}"
    jalen "If they teach you the universe has more than one story, you start asking why yours is so small."
    narrator "{i}Avyanna looks at the grid again. The numbers don't comfort her. They give her leverage.{/i}"
    avyanna "So... if someone tells me \"this is just what the stars mean,\" I should ask-"
    jalen "Who taught them."
    jalen "And what they get if you believe it."
    jalen "Then you cross-check."
    jalen "Names, if you must. Numbers, always."
    narrator "{i}Not the bridge. Not the clean screens. The place behind it, where the ship's eyes are kept honest.{/i}"
    narrator "{i}Jalen flips a panel open. Inside are stacked components with handwritten labels: PRIMARY, SECONDARY, YOU BETTER WORK.{/i}"
    avyanna "Is that official."
    jalen "It's on the ship. That makes it law."
    avyanna "Elia said the ship doesn't get to make laws."
    jalen "Elia says a lot of things."
    narrator "{i}Avyanna almost smiles. It feels like a small betrayal of her own fear.{/i}"
    narrator "{i}Jalen hands her a thin module with contact pins.{/i}"
    jalen "Swap it."
    avyanna "That's it?"
    jalen "That's it."
    avyanna "No calibration?"
    jalen "Calibration is after. First you learn not to be scared of touching the thing you're responsible for."
    narrator "{i}The module is warm from the ship's body heat. Avyanna pulls it free. The slot accepts the replacement with a soft click.{/i}"
    narrator "{i}The screen above them flickers once, then stabilizes.{/i}"
    avyanna "That feels... real. More real than the shard stuff."
    narrator "{i}The words come out before she can filter them.{/i}"
    narrator "{i}Heat rises at the base of her skull-brief, not warning, not pain. A presence leaning closer to listen.{/i}"
    narrator "{i}Jalen's hands pause.{/i}"
    jalen "It is real. That's the point."
    narrator "{i}They look at her, and for a second the humor drops all the way out.{/i}"
    jalen "The shard stuff is real too. But it doesn't obey the same rules. It doesn't give you a maintenance manual. It doesn't care if you can hold a wrench."
    avyanna "Does anything care."
    jalen "People do."
    narrator "{i}A beat. Jalen clears their throat like they're resetting a circuit.{/i}"
    jalen "Okay. Now calibration."

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}They run her through the sensor check sequence.{/i}"
    narrator "{i}Jalen doesn't make it a quiz. They make it a pattern: do this, then this, then this, and if it looks wrong, you say so.{/i}"
    narrator "{i}Avyanna gets one step backward. The screen flashes an error code. Her stomach drops hard, old reflex screaming: mistake equals pain.{/i}"
    narrator "{i}She freezes, fingers hovering over the controls.{/i}"
    jalen "Hey."
    narrator "{i}Avyanna forces herself to look at them.{/i}"
    jalen "Are you stuck because you don't know what to do, or because you're waiting for someone to hit you?"
    narrator "{i}Her jaw tightens.{/i}"
    avyanna "Both."
    narrator "{i}Jalen nods like she's named a fault in the wiring.{/i}"
    jalen "Okay. Then we do the next step."
    narrator "{i}They point at the sequence on the panel.{/i}"
    jalen "Out loud. Tell me what you see."
    narrator "{i}Her throat tries to close. The Sparkle Doctrine isn't in this room, but it haunts the ship like ambient pressure.{/i}"
    avyanna "The module is reading, but the checksum isn't matching."
    jalen "Good. That means you have eyes. Now: what's the simplest failure mode?"
    avyanna "Dirty contacts."
    jalen "Exactly."
    narrator "{i}Jalen hands her a cloth.{/i}"
    jalen "Clean it. Then try again."
    narrator "{i}Avyanna cleans the contact pins, slow and careful. Her hands are steady. The mine taught her that much. The mine taught her to do delicate work under threat.{/i}"
    narrator "{i}She reseats the module. The error clears.{/i}"
    narrator "{i}Avyanna exhales like someone lowering a weight they've been carrying in their teeth.{/i}"
    jalen "See? No one died."
    avyanna "Yet."
    jalen "That's the spirit. Healthy paranoia."
    narrator "{i}Cooling beat: Jalen closes the panel. The latch clicks. Final.{/i}"

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}They leave the sensor alcove and walk toward the observation deck.{/i}"
    narrator "{i}The ship's commons opens around them-space that feels like an argument the ship won. A message board on one wall flickers with posted notes, chores, requests, and problems marked with bright tags.{/i}"
    narrator "{i}Sparkles.{/i}"
    narrator "{i}Avyanna slows, reading one without meaning to.{/i}"
    narrator "{i}- coffee machine still sulking. again.{/i}"
    narrator "{i}- someone left three wrenches in the galley. cinnamon is mad.{/i}"
    narrator "{i}- cargo bay mat needs cleaning (blood? paint? both?){/i}"
    narrator "{i}- nav drift: check third redundant gyro{/i}"
    narrator "{i}She swallows.{/i}"
    narrator "The ship is held together by complaints and maintenance and people noticing what hurts."
    jalen "You don't have to fix everything you see."
    narrator "{i}Avyanna startles.{/i}"
    avyanna "I wasn't-"
    jalen "You were. It's fine. Just... don't turn it into a debt."
    narrator "{i}Avyanna looks at the board again.{/i}"
    avyanna "How do you know what's yours."
    narrator "{i}Jalen's gaze goes distant for a second. Not the observation deck distant-further.{/i}"
    jalen "You ask."
    narrator "{i}They shrug, like it's that simple, like grief doesn't make everything complicated.{/i}"
    jalen "Out loud. Like the captain keeps trying to teach you."
    narrator "{i}Avyanna's chest tightens. Heat brushes her spine. Approval, maybe. Or just attention.{/i}"

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}They reach the observation deck.{/i}"
    narrator "{i}Stars fill the viewport. Cold and bright and indifferent. The ship's hum is steady underfoot, a mechanical heartbeat that doesn't care what you believe.{/i}"
    narrator "{i}Jalen leans against the bulkhead. They don't sit. Stillness is a trap. Avyanna notices.{/i}"
    avyanna "You hate sitting still."
    narrator "{i}Jalen's mouth twitches like they're considering denial, then decides it's not worth the energy.{/i}"
    jalen "I hate what happens when I stop."
    narrator "{i}Avyanna waits, the way she's learned to wait-without filling the silence with apology.{/i}"
    narrator "{i}Jalen looks out at the stars, but their eyes aren't on the stars.{/i}"
    jalen "You know why I teach dumb reliability?"
    avyanna "Because the Lattice fails."
    jalen "Yes."
    narrator "{i}A beat. Jalen's hands flex once, like they're remembering a control yoke.{/i}"
    jalen "And because I was on a station when the route collapsed. I got out. My family didn't."
    narrator "{i}The sentence is the key dialogue beat from the outline, but in Jalen's mouth it sounds like a bolt being tightened: simple, irreversible.{/i}"
    narrator "{i}Avyanna's throat closes anyway.{/i}"
    narrator "{i}She remembers the coda, the cockpit at 0300, the stars like rain. She remembers the way grief can become a job you do alone.{/i}"
    avyanna "Kettering's Rest."
    narrator "{i}Jalen goes still. Just for a second.{/i}"
    jalen "Yeah."
    avyanna "You watched the lane close."
    narrator "{i}Jalen's laugh is sharp and small, no humor in it.{/i}"
    jalen "I watched the universe decide my family was a rounding error."
    narrator "{i}Avyanna's hands curl around the wrench still in her pocket. She didn't realize she kept it.{/i}"
    jalen "That's why the backup systems matter. That's why the wrench matters."
    narrator "{i}Their gaze shifts to her, steady now-teaching again, because teaching is safer than grief.{/i}"
    jalen "Because sometimes the Lattice just... stops."
    narrator "{i}Avyanna swallows.{/i}"
    narrator "{i}She thinks of the Kennel's flicker days. Of lights stuttering. Of supervisors calling it weather. Of bodies pushed through instability like it was just another shift.{/i}"
    avyanna "In the mine, when systems failed, they made us keep working anyway."
    jalen "I know."
    avyanna "If something broke, it was our fault."
    jalen "I know."
    narrator "{i}Two syllables that don't fix anything, but they don't lie either.{/i}"
    jalen "Here, when something breaks, we fix it. We don't feed you to it."
    narrator "{i}Avyanna's chest hurts.{/i}"
    narrator "We don't feed you to it."
    narrator "{i}The phrase isn't a promise of safety. It's a promise of behavior. A floor.{/i}"

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}Jalen pushes off the bulkhead.{/i}"
    jalen "Okay. Lesson over."
    narrator "{i}Avyanna blinks.{/i}"
    avyanna "That's it?"
    jalen "You learned how to close a door when the ship forgets how. You learned how to keep a sensor honest. You learned that \"stops\" is a thing the universe does."
    narrator "{i}They pause.{/i}"
    jalen "And you learned you can ask to stop."
    narrator "{i}Avyanna's fingers tighten around the wrench through her pocket fabric.{/i}"
    avyanna "I didn't ask."
    jalen "Not today. But you heard it. That's step one."
    narrator "{i}They start walking, already moving again, already outrunning their own silence.{/i}"
    jalen "Return the wrench. Cinnamon will eat me alive if you don't."
    narrator "{i}Avyanna almost laughs. The sound comes out thin, surprised at itself.{/i}"
    narrator "{i}Cooling beat: she presses her tongue to her teeth, tasting metal and something like relief.{/i}"

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}In the tool alcove, Avyanna sets the wrench back into its slot.{/i}"
    narrator "{i}The rack holds it without comment. The ship doesn't praise her for basic competence. It just accepts the tool back into the system.{/i}"
    narrator "{i}That acceptance feels better than praise.{/i}"
    narrator "{i}The presence behind her eyes hums-quiet, patient. Not words. A tone that shifts when her fingers leave the wrench.{/i}"
    narrator "You like this."
    narrator "{i}No answer. But the warmth at the base of her skull steadies, like agreement that doesn't need language.{/i}"
    narrator "{{color=#43d4a8}}<WAFFLE.BAT// OBSERVATION: trainee completed mechanical override drill | INFERENCE: grounding behavior increased | CONFIDENCE: 0.78 | NOTE: boring is safe. safe is good.>{{/color}}"

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}End Chapter 14{/i}"
    return
