## Generated from 17d_library_glossary_of_lies.md by convert_prose.py
## Do not edit manually — re-run converter after prose changes

label act1_17d_library_glossary_of_lies:
    pause 0.3
    narrator "{i}The library is small, which makes it feel safer.{/i}"
    narrator "{i}Shelves. Terminals. A table with a lamp that throws warm light without being asked.{/i}"
    narrator "{i}A stamp on the wall reads:{/i}"
    narrator "{{color=#808090}}{b}TAKE WHAT YOU NEED{/b}{{/color}}"
    narrator "{i}Avyanna reads it like it's a threat.{/i}"
    narrator "Need according to who. Enforced by whom. Paid how."
    narrator "{i}No one jumps out to correct her for touching a book.{/i}"
    narrator "{i}She touches one anyway.{/i}"
    narrator "{i}The cover is worn. The title is boring: {i}Civic Forms and Jurisdictional Practice (Guild Primer).{/i}"
    narrator "{i}She sits.{/i}"
    narrator "{i}She opens her notebook.{/i}"
    narrator "{i}On the first page she writes, in careful block letters:{/i}"
    narrator "{{color=#808090}}{b}GLOSSARY OF LIES{/b}{{/color}}"
    narrator "{i}Then, underneath, columns:{/i}"
    narrator "{{color=#808090}}WORD{{/color}}"
    narrator "{i}>{/i}"
    narrator "{{color=#808090}}WHAT THEY SAY IT MEANS{{/color}}"
    narrator "{i}>{/i}"
    narrator "{{color=#808090}}WHO PROFITS{{/color}}"
    narrator "{i}>{/i}"
    narrator "{{color=#808090}}WHO ENFORCES{{/color}}"
    narrator "{i}>{/i}"
    narrator "{{color=#808090}}WHAT IT COSTS{{/color}}"
    narrator "If I can name the shape of the trap, maybe it stops being invisible."

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}She starts with the words that keep showing up like insects in her teeth.{/i}"
    narrator "{i}{b}COMPLIANCE{/b}{/i}"
    narrator "{i}She pauses.{/i}"
    narrator "{i}In the mine, \"compliance\" meant: do what you're told or your body becomes a lesson.{/i}"
    narrator "{i}She writes:{/i}"
    narrator "{{color=#808090}}WHAT THEY SAY: safety / order / protocol{{/color}}"
    narrator "{i}>{/i}"
    narrator "{{color=#808090}}WHO PROFITS: whoever issues the rule{{/color}}"
    narrator "{i}>{/i}"
    narrator "{{color=#808090}}WHO ENFORCES: guards / forms / hunger{{/color}}"
    narrator "{i}>{/i}"
    narrator "{{color=#808090}}COST: agency{{/color}}"
    narrator "{i}The word sits there, ugly and honest.{/i}"
    narrator "{i}She turns the page.{/i}"
    narrator "{i}{b}WEATHER{/b}{/i}"
    narrator "{i}She almost laughs.{/i}"
    narrator "Weather. Like the corridor is a sky and not a mechanism."
    narrator "{{color=#808090}}WHAT THEY SAY: natural / inevitable / no one's fault{{/color}}"
    narrator "{i}>{/i}"
    narrator "{{color=#808090}}WHO PROFITS: insurance / people selling \"protection\"{{/color}}"
    narrator "{i}>{/i}"
    narrator "{{color=#808090}}WHO ENFORCES: fear / delayed shipments / fees{{/color}}"
    narrator "{i}>{/i}"
    narrator "{{color=#808090}}COST: questions{{/color}}"
    narrator "{i}She taps her pen.{/i}"
    narrator "{i}Elia would write: \"STAB IT.\"{/i}"
    narrator "{i}Elisira would write: \"FILE IT.\"{/i}"
    narrator "{i}Vesper would write: \"PROVE IT.\"{/i}"
    narrator "{i}Avyanna writes:{/i}"
    narrator "{{color=#808090}}NEXT: find pattern that shows it isn't weather{{/color}}"
    narrator "{i}It feels like building a knife one note at a time.{/i}"

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}Cinnamon pings the terminal with a small notification.{/i}"
    narrator "{{color=#43d4a8}}<CINNAMON.EXE// NOTE: good structure | SUGGESTION: add \"what would disprove it\" column>{{/color}}"
    narrator "{i}Avyanna stares at that.{/i}"
    avyanna "{i}[[muttering]]{/i} Of course you want a disproof column."
    narrator "{{color=#43d4a8}}<CINNAMON.EXE// AFFIRMATION: yes | COMMENTARY: adversaries exist>{{/color}}"
    narrator "{i}She adds a sixth column.{/i}"
    narrator "{{color=#808090}}WHAT WOULD PROVE ME WRONG{{/color}}"
    narrator "{i}The notebook looks more dangerous immediately.{/i}"

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}She keeps going.{/i}"
    narrator "{i}{b}VOLUNTARY DISCLOSURE{/b}{/i}"
    narrator "{{color=#808090}}WHAT THEY SAY: transparency / cooperation{{/color}}"
    narrator "{i}>{/i}"
    narrator "{{color=#808090}}WHO PROFITS: whoever wants your history{{/color}}"
    narrator "{i}>{/i}"
    narrator "{{color=#808090}}WHO ENFORCES: social pressure / clerks with smiles{{/color}}"
    narrator "{i}>{/i}"
    narrator "{{color=#808090}}COST: leverage (yours){{/color}}"
    narrator "{i}>{/i}"
    narrator "{{color=#808090}}DISPROOF: they cite a law with enforcement and consequence{{/color}}"
    narrator "{i}She underlines \"cite a law.\"{/i}"
    narrator "{i}{b}PROCESSING FEE{/b}{/i}"
    narrator "{i}Her pen hovers.{/i}"
    narrator "Mine word. Station word. Same shape."
    narrator "{{color=#808090}}WHAT THEY SAY: administrative necessity{{/color}}"
    narrator "{i}>{/i}"
    narrator "{{color=#808090}}WHO PROFITS: middlemen{{/color}}"
    narrator "{i}>{/i}"
    narrator "{{color=#808090}}WHO ENFORCES: delays / \"lost paperwork\"{{/color}}"
    narrator "{i}>{/i}"
    narrator "{{color=#808090}}COST: time / dignity{{/color}}"
    narrator "{i}>{/i}"
    narrator "{{color=#808090}}DISPROOF: fee correlates to actual labor{{/color}}"

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}A shadow falls over her page.{/i}"
    narrator "{i}Vesper stands at the end of the table with a mug in hand, reading without touching.{/i}"
    vesper "Glossary of lies."
    avyanna "{i}[[bracing]]{/i} It's... for me."
    vesper "Good."
    narrator "{i}Avyanna blinks.{/i}"
    avyanna "Good?"
    vesper "Yes."
    vesper "This is how you stop being controlled by vocabulary."
    narrator "{i}Vesper's gaze moves to the disproof column.{/i}"
    vesper "You added falsification tests."
    avyanna "Cinnamon told me to."
    vesper "{i}[[dry]]{/i} Cinnamon is correct."
    narrator "{i}Vesper taps the edge of the spreadsheet.{/i}"
    vesper "Add one more column."
    avyanna "Of course."
    vesper "\"How would I explain this to someone else.\""
    avyanna "Why."
    vesper "Because if you can teach it, you own it."
    narrator "{i}Avyanna's throat tightens.{/i}"
    narrator "Own it. Not be owned by it."
    avyanna "Okay."
    narrator "{i}She writes:{/i}"
    narrator "{{color=#808090}}HOW TO TEACH IT{{/color}}"

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}Vesper sets the mug down beside her notebook.{/i}"
    narrator "{i}Not a gift. Not a transaction. Just a fact: warm liquid exists, and you are allowed to drink it.{/i}"
    vesper "Keep going."
    narrator "{i}Then she leaves.{/i}"
    narrator "{i}Avyanna watches her go and feels, for a moment, like she is being trained to survive a world that wants her illiterate.{/i}"
    narrator "{i}She looks back down at her notebook.{/i}"
    narrator "{i}She writes a new entry.{/i}"
    narrator "{i}{b}FAMILY{/b}{/i}"
    narrator "{i}Her hand pauses.{/i}"
    narrator "Not established. Not defined. Not safe. Not a trap. Maybe."
    narrator "{i}She writes in the first column anyway.{/i}"
    narrator "{{color=#808090}}WHAT THEY SAY: nothing{{/color}}"
    narrator "{i}She exhales.{/i}"
    narrator "{i}Then, carefully:{/i}"
    narrator "{{color=#808090}}WHO ENFORCES: us{{/color}}"

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}She adds more entries until her hand cramps.{/i}"
    narrator "{i}{b}JURISDICTION{/b}{/i}"
    narrator "{{color=#808090}}WHAT THEY SAY: neutral authority / procedure{{/color}}"
    narrator "{i}>{/i}"
    narrator "{{color=#808090}}WHO PROFITS: whoever owns the court{{/color}}"
    narrator "{i}>{/i}"
    narrator "{{color=#808090}}WHO ENFORCES: uniforms / locks / paperwork{{/color}}"
    narrator "{i}>{/i}"
    narrator "{{color=#808090}}COST: options{{/color}}"
    narrator "{i}>{/i}"
    narrator "{{color=#808090}}DISPROOF: enforcement is absent{{/color}}"
    narrator "{i}{b}HUMANITARIAN{/b}{/i}"
    narrator "{i}She stares at the word for a long time.{/i}"
    narrator "Humanitarian is what people call themselves when they want to feel clean."
    narrator "{{color=#808090}}WHAT THEY SAY: mercy{{/color}}"
    narrator "{i}>{/i}"
    narrator "{{color=#808090}}WHO PROFITS: whoever controls the aid{{/color}}"
    narrator "{i}>{/i}"
    narrator "{{color=#808090}}WHO ENFORCES: distribution offices / \"eligibility\"{{/color}}"
    narrator "{i}>{/i}"
    narrator "{{color=#808090}}COST: dignity (if conditional){{/color}}"
    narrator "{i}>{/i}"
    narrator "{{color=#808090}}DISPROOF: aid is delivered without leverage{{/color}}"
    narrator "{i}{b}SAFETY{/b}{/i}"
    narrator "{{color=#808090}}WHAT THEY SAY: protection{{/color}}"
    narrator "{i}>{/i}"
    narrator "{{color=#808090}}WHO PROFITS: whoever sells it{{/color}}"
    narrator "{i}>{/i}"
    narrator "{{color=#808090}}WHO ENFORCES: fear{{/color}}"
    narrator "{i}>{/i}"
    narrator "{{color=#808090}}COST: freedom{{/color}}"
    narrator "{i}>{/i}"
    narrator "{{color=#808090}}DISPROOF: safety increases options instead of reducing them{{/color}}"
    narrator "{i}The last one makes her pause.{/i}"
    narrator "Safety that cages you is not safety."

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}A new book appears on the table beside her notebook.{/i}"
    narrator "{i}She didn't hear the door.{/i}"
    narrator "{i}Bubbles must have done it. Or Elisira. Or the ship itself, quietly feeding her curiosity.{/i}"
    narrator "{i}Rim Accord Civic Practices: A Field Guide.{/i}"
    narrator "{i}A sticky note is attached to the cover in neat handwriting.{/i}"
    narrator "{{color=#808090}}{b}This one will help you avoid talking yourself into a trap. - E{/b}{{/color}}"
    narrator "{i}E.{/i}"
    narrator "{i}Elisira.{/i}"
    narrator "{i}Avyanna touches the note like it might burn.{/i}"
    narrator "She's paying attention."
    narrator "{i}Avyanna opens the book.{/i}"
    narrator "{i}It is full of arguments.{/i}"
    narrator "{i}Not propaganda arguments. Real arguments: people disagreeing on paper because disagreement is allowed to exist in public.{/i}"
    narrator "{i}Her stomach twists with something that isn't fear.{/i}"
    narrator "Noise. Choice. Floors."

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}Cinnamon pings again.{/i}"
    narrator "{{color=#43d4a8}}<CINNAMON.EXE// QUESTION: do you want this indexed>{{/color}}"
    avyanna "Indexed."
    narrator "{{color=#43d4a8}}<CINNAMON.EXE// CLARIFICATION: do you want privacy on your notes>{{/color}}"
    narrator "{i}Avyanna's heart stutters.{/i}"
    avyanna "Privacy."
    narrator "{{color=#43d4a8}}<CINNAMON.EXE// RESPONSE: default privacy enabled | NOTE: sharing is always opt-in>{{/color}}"
    narrator "{i}Avyanna's eyes sting. Again. Annoying. Habit-forming.{/i}"

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}She writes one more entry, smaller than the others.{/i}"
    narrator "{i}{b}OPTIONAL{/b}{/i}"
    narrator "{{color=#808090}}WHAT THEY SAY: choice{{/color}}"
    narrator "{i}>{/i}"
    narrator "{{color=#808090}}WHO PROFITS: depends{{/color}}"
    narrator "{i}>{/i}"
    narrator "{{color=#808090}}WHO ENFORCES: no one{{/color}}"
    narrator "{i}>{/i}"
    narrator "{{color=#808090}}COST: fear (yours){{/color}}"
    narrator "{i}>{/i}"
    narrator "{{color=#808090}}DISPROOF: nothing happens when you decline{{/color}}"
    narrator "{i}She underlines the last line three times.{/i}"
    narrator "{i}Then she closes her notebook.{/i}"
    narrator "{i}She sits in the library until her body stops expecting someone to come take the table away.{/i}"
    return
