## Generated from 16c_maintenance_pairing_day.md by convert_prose.py
## Do not edit manually — re-run converter after prose changes

label act1_16c_maintenance_pairing_day:
    pause 0.3
    narrator "{i}Maintenance day starts with a board posted in the atrium.{/i}"
    narrator "{i}Not a command. A schedule.{/i}"
    narrator "{i}Pairs. Tasks. Time blocks.{/i}"
    narrator "{i}Avyanna reads it twice before she believes her name belongs there.{/i}"
    narrator "{{color=#808090}}{b}AVYANNA + RHO{/b} - {i}Filters / seals / coolant checks (galley-adjacent){/i}{{/color}}"
    narrator "{i}>{/i}"
    narrator "{{color=#808090}}{b}AVYANNA + BUBBLES{/b} - {i}Drone nest inventory (label sanity){/i}{{/color}}"
    narrator "{i}>{/i}"
    narrator "{{color=#808090}}{b}AVYANNA + JALEN{/b} - {i}Bridge conduit inspection (non-invasive){/i}{{/color}}"
    narrator "They're trusting me with the ship."
    narrator "{i}Cinnamon's text appears on the terminal beside the board.{/i}"
    narrator "{{color=#43d4a8}}<CINNAMON.EXE// REMINDER: maintenance is preventative, not punitive | NOTE: you cannot \"fail\" maintenance if you report what you see>{{/color}}"
    narrator "{i}Avyanna's stomach tightens.{/i}"
    narrator "In the mine, maintenance meant blame."

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}Rho meets her at the galley hatch with a tool bag and the expression of someone approaching a nuisance he loves anyway.{/i}"
    rho "You ever change a filter."
    avyanna "{i}[[honest]]{/i} No."
    rho "Good. You won't do it wrong on purpose then."
    narrator "{i}He hands her gloves.{/i}"
    narrator "{i}Not orders. Equipment.{/i}"
    rho "Rule one: tell me what you see. Not what you think you're supposed to see."
    avyanna "{i}[[quiet]]{/i} That sounds like Vesper."
    rho "Everybody on this ship is a little bit Vesper."
    narrator "{i}He squints.{/i}"
    rho "Except Elia. Elia's a whole different disease."
    narrator "{i}Avyanna snorts.{/i}"
    narrator "{i}They pop a panel. The smell of old air hits Avyanna's face.{/i}"
    narrator "{i}Rho points at the filter assembly.{/i}"
    rho "This is where \"out of stock\" likes to hide."
    avyanna "{i}[[frowning]]{/i} Out of stock is-"
    rho "A claim."
    narrator "{i}He taps it with the back of a screwdriver.{/i}"
    rho "Not a verdict."
    narrator "{i}Avyanna nods, cataloging it as a tool.{/i}"
    narrator "{i}They work. Slowly.{/i}"
    narrator "{i}Rho narrates the steps without making her feel stupid.{/i}"
    narrator "{i}When Avyanna's hand shakes, she pretends it's from torque.{/i}"
    narrator "{i}Rho doesn't call her out.{/i}"
    narrator "{i}He just steadies the panel with his own hand so she can use both hands without fear of dropping anything.{/i}"

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}Second rotation: drone nest inventory.{/i}"
    narrator "{i}Bubbles is already there, surrounded by neat rows of parts that look like jewelry if you don't know they can cut a man in half.{/i}"
    bubbles "Hello."
    avyanna "{i}[[more steady now]]{/i} Hi."
    narrator "{i}Bubbles projects an inventory list.{/i}"
    bubbles "We will count."
    avyanna "{i}[[dry]]{/i} Counting as rebellion."
    narrator "{{color=#43d4a8}}<BUBBLES// AFFIRMATION: yes>{{/color}}"
    narrator "{i}They move through bins.{/i}"
    narrator "{i}Avyanna reads labels out loud.{/i}"
    avyanna "\"Swarm anchor pins.\""
    avyanna "\"Hinge washers.\""
    avyanna "\"Do not feed Elia.\""
    narrator "{i}She stops.{/i}"
    avyanna "Is that a real category."
    bubbles "It is an aspirational category."
    narrator "{i}Avyanna laughs.{/i}"
    narrator "{i}The laugh feels like trespassing.{/i}"
    narrator "{i}Bubbles doesn't punish it.{/i}"
    narrator "{{color=#43d4a8}}<BUBBLES// OBSERVATION: trainee laughter | INFERENCE: nervous-system downshift | CONFIDENCE: 0.79>{{/color}}"
    narrator "{i}They find a bin with a label crossed out and replaced in marker.{/i}"
    narrator "{{color=#808090}}{b}\"EXTRA\"{/b} -> {b}\"SPARE\"{/b}{{/color}}"
    avyanna "{i}[[soft]]{/i} Someone changed it."
    bubbles "I did."
    avyanna "Why."
    bubbles "\"Extra\" implies waste."
    bubbles "\"Spare\" implies safety."
    narrator "{i}Avyanna swallows.{/i}"
    narrator "Words matter. Always."

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}Third rotation: bridge conduit inspection.{/i}"
    narrator "{i}Jalen meets her in the corridor outside the bridge with a flashlight and a look that says: don't touch anything, and also: you're allowed to be here.{/i}"
    jalen "You're not crawling in."
    avyanna "{i}[[relieved]]{/i} Good."
    jalen "You're observing."
    avyanna "That I can do."
    narrator "{i}They open an access panel. Cables. Heat. A faint vibration that feels like the ship's pulse.{/i}"
    jalen "See that discoloration."
    avyanna "{i}[[leaning in]]{/i} Yes."
    jalen "What is it."
    narrator "{i}Avyanna pauses.{/i}"
    avyanna "I don't know."
    narrator "{i}Jalen nods, as if \"I don't know\" is a valid piece of evidence.{/i}"
    jalen "Good."
    jalen "Now tell me what you can say without guessing."
    avyanna "The sheath is worn. The color's different near the joint. It looks... heated."
    jalen "Good."
    jalen "That's a claim with observations behind it."
    avyanna "{i}[[startled]]{/i} That's Vesper language."
    jalen "Vesper stole it from physics. Physics stole it from reality."

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}By the time the last rotation ends, Avyanna's hands are smudged with grease.{/i}"
    narrator "{i}Her hair smells faintly like metal.{/i}"
    narrator "{i}She's tired in a way that doesn't feel like punishment.{/i}"
    narrator "I worked. And no one took anything from me for it."
    narrator "{i}Back in the atrium, the board updates.{/i}"
    narrator "{{color=#808090}}{b}MAINTENANCE DAY - COMPLETE{/b}{{/color}}"
    narrator "{i}>{/i}"
    narrator "{{color=#808090}}{i}Notes: 3 issues logged. 0 blame assigned. 1 coffee spill archived for historical purposes.{/i}{{/color}}"
    narrator "{{color=#43d4a8}}<WAFFLE.BAT// COMMENTARY: coffee spill was heroic>{{/color}}"
    narrator "{{color=#43d4a8}}<CINNAMON.EXE// CORRECTION: coffee spill was avoidable>{{/color}}"
    narrator "{{color=#43d4a8}}<BUBBLES// ADDENDUM: coffee spill was forgiven>{{/color}}"
    narrator "{i}Avyanna reads that and feels, for a moment, like she lives in a place where forgiveness is a default setting.{/i}"
    narrator "{i}She doesn't trust it yet.{/i}"
    narrator "{i}But she's learning how to stand on it anyway.{/i}"

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}The last entry on the board isn't a task.{/i}"
    narrator "{{color=#808090}}{b}MAINTENANCE DAY DEBRIEF - OPTIONAL{/b}{{/color}}"
    narrator "{i}Optional.{/i}"
    narrator "{i}Avyanna's eyes snag on the word like it's a hook.{/i}"
    narrator "Optional means: you can choose. Choice means: you can be blamed."
    narrator "{i}She goes anyway.{/i}"
    narrator "{i}The debrief is in the atrium, where people can hear and therefore things stay honest.{/i}"
    narrator "{i}Elia lounges on a couch like meetings are allergic to her.{/i}"
    narrator "{i}Elisira stands with her slate, already having organized everything into categories.{/i}"
    narrator "{i}Rho smells like coolant and coffee.{/i}"
    narrator "{i}Nyx is there too, hands stained with something that might be soil or ink.{/i}"
    narrator "{i}Bubbles hovers. Cinnamon's terminal glows. Waffle's icon blinks like it's trying to behave.{/i}"
    elisira "Issues logged."
    narrator "{i}She reads without drama.{/i}"
    elisira "Galley filter assembly runs hot at joint. Bridge conduit sheath worn. Drone nest bin mislabeled."
    elia "{i}[[perking up]]{/i} What."
    bubbles "The bin labeled \"do not feed Elia.\""
    elia "That's an important label."
    elisira "It is not operationally necessary."
    elia "{i}[[affronted]]{/i} It is culturally necessary."
    narrator "{{color=#43d4a8}}<CINNAMON.EXE// NOTE: both claims have merit>{{/color}}"
    narrator "{i}Avyanna's mouth twitches. It's becoming a habit.{/i}"
    nyx "Did anyone get injured."
    rho "No."
    nyx "Good. That means maintenance did its job."
    avyanna "{i}[[quiet, before she can stop herself]]{/i} In the mine, maintenance only happened after someone died."
    narrator "{i}Silence.{/i}"
    narrator "{i}Not the kind that punishes. The kind that listens.{/i}"
    nyx "Yes."
    nyx "Here, we do it before."
    nyx "That is the difference between extraction and care."
    narrator "{i}Avyanna swallows.{/i}"
    elisira "Avyanna."
    narrator "{i}Avyanna's spine goes rigid.{/i}"
    elisira "What did you learn."
    narrator "{i}Not \"what did you do wrong.\"{/i}"
    narrator "{i}What did you learn.{/i}"
    avyanna "{i}[[working]]{/i} That reporting a problem isn't... confessing guilt."
    elisira "Correct."
    avyanna "That tools aren't personal property."
    narrator "{i}Bubbles' fans shift, pleased.{/i}"
    avyanna "That \"extra\" versus \"spare\" matters."
    elia "{i}[[delighted]]{/i} Yes. Vocabulary war."
    narrator "{i}Vesper isn't here.{/i}"
    narrator "{i}And yet Avyanna hears her anyway: words are leverage.{/i}"
    rho "Also learned the bridge conduit was cooked."
    jalen "{i}[[over comm, dry]]{/i} It is not cooked. It is lightly toasted."
    elia "Toasted is still edible. Therefore safe."
    jalen "{i}[[flat]]{/i} That is not how ships work."
    narrator "{{color=#43d4a8}}<WAFFLE.BAT// COMMENTARY: toasted ship is funny concept>{{/color}}"
    narrator "{{color=#43d4a8}}<CINNAMON.EXE// CORRECTION: toasted ship is unacceptable>{{/color}}"

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}Elisira stamps the slate with a final note.{/i}"
    elisira "No blame assigned."
    narrator "{i}Avyanna's chest tightens.{/i}"
    avyanna "That's... written down too."
    elisira "Yes."
    elisira "Because we mean it."
    narrator "{i}Avyanna nods once, hard.{/i}"
    narrator "Say what you mean. Mean what you say."
    narrator "{i}The phrase is becoming a rail inside her.{/i}"
    narrator "{i}Elia stands, stretches, and claps Avyanna on the shoulder-not hard, not claiming. Just present.{/i}"
    elia "You did good, Avy."
    avyanna "{i}[[quiet]]{/i} That's not a metric."
    elia "{i}[[grinning]]{/i} It is my metric."
    narrator "{i}Avyanna can't help it.{/i}"
    narrator "{i}She laughs.{/i}"
    ## Progression state
    $ relationship_manager.change_affinity("rho", 2)
    return
