## Generated from 15c_station_micro_errand_paperwork_and_predators.md by convert_prose.py
## Do not edit manually — re-run converter after prose changes

label act1_15c_station_micro_errand_paperwork_and_predators:
    pause 0.3
    narrator "{i}The concourse smells like hot oil, cheap perfume, and the particular tang of too many bodies pretending not to need each other.{/i}"
    narrator "{i}Avyanna walks half a step behind Elisira, trying to match her pace.{/i}"
    narrator "{i}Elisira moves like she belongs. Not because she's loud. Because she's certain.{/i}"
    narrator "How do you look like you belong when you're always waiting to be corrected."
    elisira "Stay close enough that you can hear me."
    avyanna "{i}[[automatic]]{/i} Yes."
    narrator "{i}Avyanna catches herself.{/i}"
    avyanna "Why."
    narrator "{i}Elisira glances at her, a tiny flicker of approval.{/i}"
    elisira "Because this is a funnel."
    narrator "{i}She gestures without moving her hands-just a small tilt of chin toward a cluster of kiosks, a queue, and a row of \"assistance desks\" with people who look too eager.{/i}"
    elisira "Funnels are where predators hunt."
    avyanna "{i}[[quiet]]{/i} Like the mine."
    elisira "Like anywhere people are scared and tired."

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}They're here for a simple errand: pick up a stamped copy of a contract addendum. A paper artifact. A thing the Guild recognizes even if systems \"glitch.\"{/i}"
    narrator "{i}Avyanna hates that paper matters.{/i}"
    narrator "Paper matters because someone can take it away. Paper matters because it can be burned."
    narrator "{i}Elisira doesn't hate it. Elisira treats paper like a weapon with a handle.{/i}"
    narrator "{i}They approach the counter.{/i}"
    narrator "{i}A clerk smiles too widely.{/i}"
    clerk "Can I help you, miss-"
    narrator "{i}Her eyes flick to Avyanna's collar tag. Too fast to be casual.{/i}"
    clerk "-traveler."
    narrator "{i}Avyanna's skin crawls.{/i}"
    elisira "{i}[[pleasant]]{/i} We're here for a pickup. Code is on the slate."
    narrator "{i}She slides the slate over. Not close enough for the clerk to snatch it.{/i}"
    narrator "{i}The clerk's smile tightens.{/i}"
    clerk "We'll need to verify identity."
    avyanna "{i}[[tensing]]{/i} Which-"
    elisira "{i}[[cutting in, still pleasant]]{/i} Under which jurisdiction."
    narrator "{i}The clerk blinks.{/i}"
    clerk "Excuse me?"
    elisira "You said \"need.\" I'm asking: need by which rule. Enforced by whom."
    narrator "{i}The clerk's eyes flick toward a security camera. Toward a uniform across the hall.{/i}"
    narrator "{i}Then back.{/i}"
    clerk "It's... standard."
    elisira "Standard is not enforceable."
    narrator "{i}The clerk's stylus taps twice against the counter.{/i}"
    clerk "Fine. Sign here."
    narrator "{i}She prints a slip with a pen attached by chain.{/i}"
    narrator "{i}The slip is a trap with polite edges: it asks for name, origin, and \"additional contacts.\"{/i}"
    narrator "{i}Avyanna's throat tightens.{/i}"
    narrator "Additional contacts means: who can we threaten."
    elisira "{i}[[to Avyanna, quiet]]{/i} You don't sign anything you didn't request."
    avyanna "{i}[[whisper]]{/i} I didn't request this."
    elisira "Correct."
    narrator "{i}Elisira takes the pen-not from the clerk's hand, from the counter.{/i}"
    elisira "{i}[[pleasant]]{/i} We're declining voluntary disclosure."
    clerk "It's required."
    elisira "Then cite it."
    narrator "{i}Silence.{/i}"
    narrator "{i}The clerk's smile becomes brittle.{/i}"
    clerk "If you don't cooperate, the pickup may be delayed."
    narrator "{i}Avyanna's heart rate spikes.{/i}"
    narrator "Delay means loss. Loss means punishment. Loss means hunger."
    elisira "Then delay it."
    narrator "{i}She says it like: we have all day. Like time can't be weaponized here.{/i}"
    elisira "We'll file a complaint with the arbitration desk. We'll note the attempted coercion. We'll request the security footage."
    narrator "{i}The clerk's eyes widen, just a fraction.{/i}"
    narrator "{i}She reaches under the counter and produces the stamped packet like it's always been there.{/i}"
    clerk "No need to escalate."
    elisira "Good."

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}They step away.{/i}"
    narrator "{i}Avyanna's knees feel like they're trying to unlock.{/i}"
    avyanna "{i}[[breathing]]{/i} You can just... do that."
    elisira "Yes."
    avyanna "Why didn't she-"
    elisira "Because the clerk wasn't enforcing policy. She was testing a boundary."
    avyanna "Like a-"
    elisira "Predator."
    narrator "{i}Avyanna's hands tremble as she clutches the packet.{/i}"
    avyanna "What if she had called security."
    elisira "Then we'd have receipts."
    avyanna "That sounds like Vesper."
    elisira "Vesper taught me half of it. I taught her the other half. It's incestuous."
    avyanna "{i}[[a startled laugh]]{/i} That's not-"
    elisira "{i}[[deadpan]]{/i} It's a metaphor. Do not repeat it."

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}A man steps into their path.{/i}"
    narrator "{i}Not uniformed. Not armed. Just... friendly.{/i}"
    man "Hey. You look lost. I know where the arbitration wing is. I can-"
    narrator "{i}Avyanna's mouth opens.{/i}"
    narrator "{i}The mine reflex tries to offer politeness as payment.{/i}"
    elisira "No thank you."
    man "I'm just helping."
    elisira "We did not request help."
    man "Wow. Hostile."
    elisira "{i}[[pleasant]]{/i} Correct."
    narrator "{i}They walk around him.{/i}"
    narrator "{i}Avyanna's chest tightens as if waiting for the hit that follows refusal.{/i}"
    narrator "{i}None comes.{/i}"
    narrator "{i}The man mutters something under his breath and moves on, scanning for softer prey.{/i}"
    avyanna "{i}[[quiet]]{/i} No thank you."
    elisira "Yes."
    avyanna "That's... allowed."
    elisira "It's required."
    narrator "{i}Avyanna looks at her.{/i}"
    elisira "For survival."

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}Back at the docking tunnel, Avyanna exhales like she's been holding her breath since they left the ship.{/i}"
    avyanna "I kept thinking... if I'm rude, something bad happens."
    elisira "That's because something bad used to happen."
    avyanna "Does it ever stop feeling like-"
    elisira "{i}[[cutting in, softer than usual]]{/i} Yes."
    narrator "{i}A pause.{/i}"
    elisira "Not fast. But yes."
    narrator "{i}Avyanna nods.{/i}"
    narrator "{i}She presses the stamped packet to her chest like it can keep her safe.{/i}"
    narrator "Paper is teeth. But sometimes it bites the right thing."

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}They don't go straight back.{/i}"
    narrator "{i}Elisira takes the long route through the concourse on purpose.{/i}"
    narrator "{i}Not because she likes crowds. Because she likes information.{/i}"
    avyanna "Why are we-"
    elisira "Watching."
    narrator "{i}They pause near a wall of public postings.{/i}"
    narrator "{i}Not a bulletin board. A contract board. Smaller than the Guild's, but the same bones: jobs, fees, penalties, a thousand ways to make desperation look like choice.{/i}"
    narrator "{i}Avyanna reads a posting aloud without thinking.{/i}"
    avyanna "\"Processing surcharge applies to late submissions.\""
    narrator "{i}Her stomach twists.{/i}"
    narrator "Processing surcharge. Mine word. Station word. Same shape."
    elisira "What does that mean."
    avyanna "{i}[[automatic]]{/i} It means... pay."
    elisira "That's the effect. Not the meaning."
    avyanna "{i}[[working]]{/i} It means they're charging for time they didn't lose. They're charging for... being behind."
    elisira "Who benefits."
    avyanna "The office. The broker. Whoever owns the desk."
    elisira "Who enforces it."
    avyanna "The clerk. The system. The fact that if you miss a submission, you lose your claim."
    elisira "Good."

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}A woman approaches them.{/i}"
    narrator "{i}Mid-thirties, expensive coat, smile tuned for crowds. She carries a badge that looks real enough to be dangerous.{/i}"
    woman "You look like you're having trouble with the boards."
    elisira "No."
    woman "I can help you file. I know the system. I can get you processed faster."
    narrator "{i}Avyanna's mouth goes dry.{/i}"
    narrator "Faster means: I own you now."
    narrator "{i}The woman's gaze flicks to Avyanna again. Too curious.{/i}"
    woman "You're new. You don't want to get tripped up by bureaucracy. It's such a shame when people lose claims over small mistakes."
    narrator "{i}She smiles wider, as if pity is a gift.{/i}"
    narrator "{i}Avyanna feels her body prepare the mine-script: apologize, agree, accept the hook.{/i}"
    narrator "{i}Elisira doesn't raise her voice.{/i}"
    elisira "No thank you."
    woman "I'm not charging."
    elisira "Then you are lying."
    narrator "{i}The woman's smile tightens.{/i}"
    woman "Excuse me?"
    elisira "People who do labor for free in systems like this are buying something else."
    woman "I'm just-"
    elisira "Helping."
    elisira "We did not request help."
    narrator "{i}The woman's eyes harden, just for a blink. A tell.{/i}"
    avyanna "{i}[[quiet, to Elisira]]{/i} Anger at refusal."
    narrator "{i}Elisira's gaze flicks to her. Approval without softness.{/i}"
    elisira "Correct."
    narrator "{i}The woman recovers her smile.{/i}"
    woman "You don't have to be rude."
    elisira "I do."
    woman "That's going to make you enemies."
    elisira "It's a public concourse. Everyone is already an enemy. The difference is which ones pretend."
    narrator "{i}The woman's smile drops entirely.{/i}"
    woman "Fine. Good luck."
    narrator "{i}She walks away quickly, scanning for someone who will trade fear for assistance.{/i}"
    avyanna "{i}[[breathing]]{/i} I almost-"
    elisira "Took the hook."
    avyanna "Yes."
    elisira "That's normal."
    avyanna "It doesn't feel normal."
    elisira "It feels like training data."
    narrator "{i}Avyanna's throat tightens.{/i}"
    avyanna "Am I... always going to be that easy."
    elisira "No."
    elisira "You just proved it."

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}They walk back toward the docking tunnel.{/i}"
    narrator "{i}Avyanna clutches the stamped packet less like a lifeline and more like evidence.{/i}"
    narrator "Politeness is wrapper. Evaluate the ask."
    narrator "{i}She repeats it silently until the words stop feeling like a borrowed tool and start feeling like hers.{/i}"
    return
