## Generated from 13e_water_is_not_a_test.md by convert_prose.py
## Do not edit manually — re-run converter after prose changes

label act1_13e_water_is_not_a_test:
    pause 0.3
    narrator "{i}The washroom is too clean.{/i}"
    narrator "{i}Not sterile-lived clean. The kind of clean that means someone uses this space and then puts it back the way they want to find it.{/i}"
    narrator "{i}Avyanna stands in the doorway with her hands in fists, staring at the shower control panel.{/i}"
    narrator "{i}A dial with temperature ranges. A toggle for pressure. A little display that says WATER AVAILABLE.{/i}"
    narrator "Available for who. For how long."
    narrator "{i}Bubbles hovers behind her, not pushing her in.{/i}"
    bubbles "You have not bathed."
    avyanna "{i}[[too fast]]{/i} I have."
    narrator "{i}Bubbles waits.{/i}"
    narrator "{i}Avyanna hears herself and corrects the lie without being asked.{/i}"
    avyanna "I rinsed."
    avyanna "Once."
    bubbles "That is not bathing."
    avyanna "It was enough."
    narrator "{{color=#43d4a8}}<BUBBLES// OBSERVATION: deflection language | INFERENCE: scarcity conditioning | CONFIDENCE: 0.89>{{/color}}"
    narrator "{i}Avyanna stares at the dial.{/i}"
    narrator "{i}She can feel the mine on her skin like a second uniform: dust that never leaves, sweat that dries wrong, the memory of water that came with eyes on you.{/i}"
    narrator "If you take too long, someone yells. If you take too much, someone takes it back."
    narrator "{i}Cinnamon's terminal in the corner wakes, as if it has been listening and decides it is time to be useful.{/i}"
    narrator "{{color=#43d4a8}}<CINNAMON.EXE// STATUS: water rationing not active | NOTE: no metering policy for hygiene | POLICY: \"take what you need\">{{/color}}"
    avyanna "{i}[[hoarse]]{/i} Nothing is unmetered."
    narrator "{{color=#43d4a8}}<CINNAMON.EXE// RESPONSE: correct in hostile systems | NOTE: this ship is not hostile to hygiene>{{/color}}"
    avyanna "That doesn't mean it's safe."
    narrator "{i}Bubbles rotates toward her, fans quieting.{/i}"
    bubbles "You are safe enough to be clean."
    narrator "{i}The sentence lands like a hand offered.{/i}"
    narrator "{i}Avyanna doesn't take it. Not yet.{/i}"
    avyanna "If I use too much, does it... affect the ship."
    narrator "{i}Cinnamon answers without pity, which is the only way Avyanna can hear it.{/i}"
    narrator "{{color=#43d4a8}}<CINNAMON.EXE// ANSWER: negligible impact | CONTEXT: hygiene is operational requirement | FOLLOW-UP: infections cost more water>{{/color}}"
    avyanna "{i}[[a small laugh that isn't humor]]{/i} Everything is operational."
    narrator "{{color=#43d4a8}}<CINNAMON.EXE// AFFIRMATION: yes>{{/color}}"
    bubbles "We like you operational."
    avyanna "{i}[[quiet]]{/i} I'm not a machine."
    narrator "{i}Bubbles' fans change pitch-annoyed in defense of her.{/i}"
    bubbles "Correct."
    bubbles "You are a person."
    narrator "{i}Avyanna swallows.{/i}"
    narrator "{i}She reaches for the dial and stops.{/i}"
    narrator "{i}Her hand hovers over warmth like it's a trap door.{/i}"
    narrator "Warm water means vulnerability. Warm water means someone can hurt you because you're soft."
    avyanna "{i}[[barely]]{/i} How long."
    bubbles "How long what."
    avyanna "How long until I'm... done."
    narrator "{i}Silence. Listening, not judging.{/i}"
    narrator "{{color=#43d4a8}}<CINNAMON.EXE// OBSERVATION: trainee framing hygiene as timed task | INFERENCE: prior punishment context | CONFIDENCE: 0.91>{{/color}}"
    narrator "{{color=#43d4a8}}<CINNAMON.EXE// RESPONSE: there is no \"until\" | SUGGESTION: bathe until body reports \"better\">{{/color}}"
    avyanna "My body lies."
    narrator "{i}Bubbles drifts closer, just enough that Avyanna can hear the tiny corrective hum.{/i}"
    bubbles "Your body is a witness."
    bubbles "It is scared. It is still a witness."
    narrator "{i}Avyanna's throat tightens.{/i}"
    avyanna "That's not fair."
    bubbles "No."
    bubbles "The mine was not fair."
    narrator "{i}Avyanna turns the dial one notch toward warm.{/i}"
    narrator "{i}Water hisses through the pipes like the ship clearing its throat.{/i}"
    narrator "{i}She flinches at the sound.{/i}"
    narrator "{i}Bubbles does not comment.{/i}"
    narrator "{i}The first spray hits her palm-hot enough to make her jerk back.{/i}"
    avyanna "Ow."
    narrator "{{color=#43d4a8}}<CINNAMON.EXE// OBSERVATION: temperature overshoot | ACTION: reduce to safe threshold>{{/color}}"
    narrator "{i}The water shifts to a steady warmth, like someone smoothing a blanket.{/i}"
    avyanna "{i}[[suspicious]]{/i} You adjusted it."
    narrator "{{color=#43d4a8}}<CINNAMON.EXE// AFFIRMATION: yes | NOTE: you are allowed to be comfortable>{{/color}}"
    narrator "{i}Avyanna stares at the display again.{/i}"
    narrator "{i}WATER AVAILABLE.{/i}"
    narrator "{i}It doesn't tick down.{/i}"
    narrator "It doesn't tick down."
    narrator "{i}Her shoulders drop by a millimeter.{/i}"
    narrator "{i}She steps in.{/i}"
    narrator "{i}The water hits her hair, her scalp, her neck. Heat spreads under skin that has been cold for too long.{/i}"
    narrator "{i}For a second, the mine tries to rise-showers as a line, as a punishment, as a place where eyes measured you for weakness.{/i}"
    narrator "{i}Avyanna's lungs seize.{/i}"
    narrator "{i}She turns her face into the spray and forces breath through the moment.{/i}"
    narrator "{i}In. Out.{/i}"
    narrator "{i}In.{/i}"
    narrator "{i}Bubbles speaks from outside the curtain, not entering without permission.{/i}"
    bubbles "Do you want company."
    avyanna "{i}[[immediate]]{/i} No."
    narrator "{i}Then-because she is learning honesty is a floor, not a threat-{/i}"
    avyanna "Thank you."
    bubbles "You are welcome."
    narrator "{i}Cinnamon's text appears on the terminal, simple.{/i}"
    narrator "{{color=#43d4a8}}<CINNAMON.EXE// REMINDER: you may take two towels>{{/color}}"
    avyanna "{i}[[startled]]{/i} Two."
    narrator "{{color=#43d4a8}}<CINNAMON.EXE// CLARIFICATION: yes | NOTE: drying quickly reduces chill response>{{/color}}"
    narrator "{i}She laughs again, quieter.{/i}"
    avyanna "Who decided that."
    narrator "{{color=#43d4a8}}<CINNAMON.EXE// ANSWER: me>{{/color}}"
    avyanna "{i}[[muttering]]{/i} Of course."
    narrator "{i}She washes. Slowly.{/i}"
    narrator "{i}Soap that smells like something alive-not mine disinfectant, not chemical fear.{/i}"
    narrator "{i}When she finally turns the water off, she stands still for a moment, waiting for the other shoe.{/i}"
    narrator "{i}No alarm.{/i}"
    narrator "{i}No banging on the door.{/i}"
    narrator "{i}No shouted quota.{/i}"
    narrator "{i}Just the ship humming like it has always been this kind.{/i}"
    narrator "{i}Avyanna steps out wrapped in a towel that is too soft to trust.{/i}"
    narrator "{i}Bubbles offers another without making it a question that costs anything.{/i}"
    narrator "{i}Avyanna takes it.{/i}"
    narrator "{i}Her hands tremble once.{/i}"
    narrator "I'm clean. And nothing bad happened."
    narrator "{i}She doesn't know what to do with that.{/i}"
    narrator "{i}So she does the only thing she knows how to do with new evidence.{/i}"
    narrator "{i}She files it.{/i}"

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}The laundry nook is adjacent, like the ship assumes hygiene includes clothing and isn't making you ask permission twice.{/i}"
    narrator "{i}A row of baskets. A machine that looks too expensive to waste on ordinary fabric. Shelves of detergent in small bottles, each labeled with a scent name that feels like a luxury someone bothered to catalog.{/i}"
    narrator "{i}Avyanna stands in front of them as if choosing wrong will be punished.{/i}"
    narrator "In the mine, you got whatever chemical soap they issued. It stripped skin. It didn't count as cruelty because it was \"standard.\""
    narrator "{i}Bubbles hovers at the doorway again, refusing to enter without being invited.{/i}"
    bubbles "Laundry is next."
    avyanna "{i}[[stiff]]{/i} I can do it."
    bubbles "Yes."
    bubbles "Do you want help."
    narrator "{i}Avyanna's throat tightens at the question. Help always meant debt.{/i}"
    avyanna "No."
    narrator "{i}Then-{/i}"
    avyanna "Maybe... explain the machine."
    narrator "{i}Bubbles' fans shift: approval without fanfare.{/i}"
    bubbles "Yes."

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}The machine has a simple interface.{/i}"
    narrator "{i}Load.{/i}"
    narrator "{i}Select cycle.{/i}"
    narrator "{i}Select temperature.{/i}"
    narrator "{i}Start.{/i}"
    narrator "{i}No cost display. No countdown. No warning about \"overuse.\"{/i}"
    avyanna "{i}[[quiet]]{/i} It doesn't track."
    narrator "{{color=#43d4a8}}<CINNAMON.EXE// RESPONSE: it tracks for maintenance only | NOTE: not for punishment>{{/color}}"
    narrator "{i}Avyanna pulls her clothes from the hamper.{/i}"
    narrator "{i}Crew-issue fabric, already softening from regular washing.{/i}"
    narrator "{i}She hesitates at the pile, suddenly aware of how much she owns.{/i}"
    narrator "Mine brain: hoard. Keep. Don't waste. Don't take what you can't defend."
    narrator "{i}She starts sorting like she's trying to prove she deserves it.{/i}"
    narrator "{i}Bubbles doesn't let her spiral quietly.{/i}"
    bubbles "You are permitted to wash all of it."
    avyanna "{i}[[defensive]]{/i} I wasn't-"
    bubbles "You were."
    narrator "{i}Avyanna freezes.{/i}"
    avyanna "{i}[[small]]{/i} If I wash it all, I'll have nothing to wear."
    narrator "{{color=#43d4a8}}<CINNAMON.EXE// SUGGESTION: use spare linens | NOTE: crew-issue basics exist in supply locker | POLICY: you may take them>{{/color}}"
    avyanna "Supply locker."
    narrator "The mine would never let you take from supply without \"approval.\" Approval meant debt."
    bubbles "We can get you two sets of basics."
    avyanna "Two."
    bubbles "Two."
    narrator "{i}Bubbles pauses.{/i}"
    bubbles "You can have more later."
    narrator "{i}Avyanna's chest tightens.{/i}"
    avyanna "{i}[[rough]]{/i} I don't know how to..."
    bubbles "Want."
    narrator "{i}The word is gentle and brutal.{/i}"
    narrator "{i}Avyanna swallows.{/i}"
    avyanna "I don't know how to want without paying."
    narrator "{{color=#43d4a8}}<CINNAMON.EXE// RESPONSE: practice>{{/color}}"

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}Avyanna stares at the detergent shelf again.{/i}"
    avyanna "What do I pick."
    narrator "{{color=#43d4a8}}<CINNAMON.EXE// QUESTION: what do you prefer>{{/color}}"
    narrator "{i}Prefer.{/i}"
    narrator "{i}The word feels like a trick question.{/i}"
    narrator "{i}Avyanna picks up one bottle, reads the label.{/i}"
    narrator "{{color=#808090}}{i}Citrus.{/i}{{/color}}"
    narrator "{i}She puts it down.{/i}"
    narrator "{i}Picks up another.{/i}"
    narrator "{{color=#808090}}{i}Lavender.{/i}{{/color}}"
    narrator "{i}Her throat tightens unexpectedly.{/i}"
    narrator "The mine smelled like metal and sweat and disinfectant. Lavender smells like a place where no one dies for production."
    avyanna "{i}[[quiet]]{/i} This one."
    narrator "{i}No alarm. No correction. No laughter.{/i}"
    bubbles "Acknowledged."
    narrator "{{color=#43d4a8}}<CINNAMON.EXE// NOTE: preference logged | COMMENTARY: good>{{/color}}"
    narrator "{i}\"Preference logged\" should feel invasive.{/i}"
    narrator "{i}Instead it feels like someone taking her seriously.{/i}"

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}She loads the machine.{/i}"
    narrator "{i}Presses start.{/i}"
    narrator "{i}The drum begins to turn.{/i}"
    narrator "{i}The sound is ordinary. Domestic. It makes her eyes sting.{/i}"
    narrator "The ship is doing chores. The ship is treating me like I belong inside chores."
    narrator "{i}Avyanna wipes her face with the edge of her towel before she can be embarrassed by needing one.{/i}"
    narrator "{i}Bubbles stays outside the doorway, a sentinel for dignity.{/i}"
    bubbles "Do you need anything else."
    narrator "{i}Avyanna looks at the shelf of folded towels.{/i}"
    narrator "{i}One is still around her hair. Another around her shoulders. She wants a third, absurdly, because it would mean she's allowed to be wasteful.{/i}"
    narrator "{i}She takes a breath.{/i}"
    avyanna "I... want another towel."
    narrator "{i}Silence.{/i}"
    narrator "{i}Then Cinnamon, brisk as ever:{/i}"
    narrator "{{color=#43d4a8}}<CINNAMON.EXE// RESPONSE: granted>{{/color}}"
    narrator "{i}Bubbles adds:{/i}"
    bubbles "I will bring it."
    narrator "{i}Avyanna's throat tightens. Not with shame. With something worse.{/i}"
    narrator "They didn't make me justify it."
    narrator "{i}Bubbles returns with a third towel and places it on the counter like it's nothing.{/i}"
    narrator "{i}Like wanting is nothing.{/i}"
    narrator "{i}Avyanna doesn't know how to hold that without breaking, so she does what she's learned to do with fragile things.{/i}"
    narrator "{i}She holds it carefully.{/i}"
    return
