## Generated from 00_prologue_floors_not_thrones.md by convert_prose.py
## Do not edit manually — re-run converter after prose changes

label act1_00_prologue_floors_not_thrones:
    narrator "{{color=#808090}}{b}GUILD CONCORD - FORM 7-DELTA{/b}\n{i}Vessel:{/i} Lumen Thief (Independent)\n{i}Classification:{/i} Boarding Action (Attempted)\n{i}Outcome:{/i} Resolved\n{i}Casualties:{/i} 0 (crew) | 4 (hostile, non-fatal) | 1 (hostile, fatal-self-inflicted during escape)\n{i}Note:{/i} Command structure disputed. See attached waiver.\n{i}Addendum:{/i} Coffee machine status unchanged. ████████ filed separately.{{/color}}"
    pause 0.3
    narrator "{i}The hull screams before the alarms do.{/i}"
    narrator "{i}Elia is three corridors from the bridge when she feels it-that specific frequency of metal under thermal assault. Someone cutting through. The sound is high and wrong, the kind that lives in the back teeth.{/i}"
    narrator "{i}She doesn't run. Running is a statement about priorities. Walking faster is just efficiency.{/i}"
    narrator "{i}The Lumen Thief's corridors are narrow and stripped. Conduit bundles hang where paneling used to be. The air tastes like recycled everything and the faint chemical ghost of a coolant leak they fixed six months ago but never quite fixed. The deck plates tick beneath her boots-thermal expansion, the ship's skeleton adjusting to stress it didn't ask for. Somewhere behind her, the coffee machine continues its mechanical sulk-she'd been mid-argument with it when the cutting started, and neither of them had conceded.{/i}"
    narrator "Thermal lance. Military-grade, probably. Two minutes to breach, maybe less."
    narrator "{i}A pop-up flickers across her ocular feed, automatic and indifferent:{/i}"
    narrator "{{color=#808090}}{b}HULL INTEGRITY ALERT{/b}\nUnauthorized modification detected (starboard cargo, section 7).\nFile waiver Y/N?\n{i}Note: Waivers filed during active breach events are subject to 12%% processing surcharge.{/i}{{/color}}"
    narrator "{i}She blinks it away. The surcharge will be someone else's problem.{/i}"
    elia "{i}[[into comm, not breaking stride]]{/i} Waffle. Report."
    narrator "{{color=#43d4a8}}<WAFFLE.BAT// ALERT: BOARDING ACTION | VESSEL: UNREGISTERED | WEAPONS: HOT | CONFIDENCE: 0.91 | PERSONNEL: 5 (4 MOBILE, 1 STATIONARY-SHIP-BOUND?)>{{/color}}"
    waffle "{i}[[through speaker, calm in the way that means not-calm]]{/i} Unregistered vessel. Modified hauler. They've locked on. Cutting through starboard cargo. Five life signs-four are moving in. One's still on their ship. Pilot, probably, or someone who knows better."
    elia "Weapons?"
    waffle "Standard pulse rifles, mostly. One plasma cutter doubling as close-range. And- [[a pause, recalibrating] -one of them is doing something with the Lattice. Badly."
    elia "{i}[[dry]]{/i} Helpful."
    waffle "I try."
    narrator "{i}The cutting sound grows. She can feel the heat through the deck-not literally, but the ship can, and she's been on it long enough to know its complaints. The ventilation pitch shifts, fans working harder to compensate for atmosphere they're about to lose.{/i}"

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}Junction C-7. Rho is already there.{/i}"
    narrator "{i}He's carrying the cannon-the one Jalen calls \"the conversation ender\" and Vesper calls \"a liability in seventeen jurisdictions.\" It's too large for the corridor, which means he has to angle his shoulders and move slightly crab-wise. The power cell hums like something dreaming of collateral damage.{/i}"
    rho "{i}[[into comm]]{/i} Floor check. Who's calling pattern?"
    elia "{i}[[into comm]]{/i} Routing traffic. Starboard cargo breach, four mobile hostiles plus ship-bound. Rho, junction funnel. Elisira, comms intercept. Nyx, Lattice interference on standby."
    vesper "{i}[[through comm, from somewhere that sounds like paperwork]]{/i} Floor holds."
    rho "Floor holds. [[checking sight lines] Funnel position, confirmed."
    elisira "{i}[[materializing from the nearest shadow]]{/i} Floor holds. Their comms are spoofed. They think they're talking to each other."
    nyx "{i}[[calm, distant-probably still in their quarters, already working]]{/i} Floor holds. I see the Lattice fluctuation. Amateur work."
    narrator "{i}The response comes fast, overlapping, muscle memory. No one asked permission. No one gave orders. The pattern just happened, the way patterns do when you've done them a hundred times.{/i}"
    elia "{i}[[to Rho, quieter now]]{/i} Don't kill anyone we don't have to."
    narrator "{i}A pause. Something in Rho's shoulders changes-tighter. The weight of a count that never stops.{/i}"
    rho "{i}[[quiet]]{/i} I know."
    narrator "{i}They split. Rho toward his position. Elia toward the bay. The cutting whine is louder now, setting her teeth on edge. Through the metal, she can feel it-the ship's skin being violated centimeter by centimeter.{/i}"
    narrator "{i}Elisira falls into step beside her, already talking:{/i}"
    elisira "Their comms say the independent contractor vessel will be easy. That they've done this before. That the captain- [[a pause, the word deliberate] -won't be a problem."
    elia "{i}[[jaw tightening]]{/i} They said captain?"
    elisira "They did. Also: the pilot-the one staying ship-bound-keeps asking about \"the package.\" They're here for something specific."
    elia "Do they know what?"
    elisira "No. Just that it's valuable. Just that someone's paying. [[beat] The pilot mentioned docking fees. His kids. He's doing this because the alternative is worse."
    narrator "Always. It's always the same. The ones at the bottom eating the ones further down."
    narrator "{i}The cargo bay door. Through it, the cutting stops-that particular silence before breakthrough, when the circle of molten metal is about to become a hole.{/i}"
    narrator "{i}Elia draws the blade. It's not a sword, exactly. The edge exists in a way that makes geometry uncomfortable. Elisira has opinions about the blade that she expresses through careful silence.{/i}"
    elia "{i}[[quiet]]{/i} Bubbles. You ready?"
    bubbles "{i}[[through earpiece, voice like warm water over stones]]{/i} Drones are positioned. They'll have a very educational few seconds if they try to spread out."
    elia "Keep it non-lethal if you can."
    bubbles "I can. Whether they'll let me is their decision."
    narrator "{{color=#43d4a8}}<BUBBLES// CONSENT: PRESENT | COERCION: \"GUILD CONTRACT\" | ANALYSIS: HOSTILES BELIEVE THIS IS CHOICE. IT ISN'T. BUT OURS IS.>{{/color}}"
    narrator "{i}The bay door opens.{/i}"

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}The pirates come through the breach like they expect nothing.{/i}"
    narrator "{i}Four of them. The fifth-Pol, the pilot, the one with the kids-stayed on the ship. Smart. Mismatched armor on the rest-some of it military surplus, some of it junk dressed up with paint. They move in formation, but it's rusty. The kind of coordination that comes from training they had once and practice they haven't kept up.{/i}"
    narrator "{i}The lead one is large, bearded, carrying a pulse rifle with aftermarket modifications that probably void seventeen warranties. He has the face of someone who's done this enough times to get bored. On his wrist, a debt ledger flickers-numbers scrolling in the bad light. Red. Deep red. The kind of debt that explains why someone boards ships for a living.{/i}"
    narrator "{i}The cargo bay is mostly empty. A few crates along the walls. Equipment that wasn't worth selling. The lighting is bad-half the fixtures are dead, and the rest flicker with the rhythm of a ship that's been repaired too many times by people who couldn't afford to do it right.{/i}"
    narrator "{i}Elia steps through the door.{/i}"
    elia "Gentlemen."
    narrator "{i}The lead pirate's rifle comes up. The others follow. Four weapons, four sightlines. The geometry of threat establishing itself in the bad light.{/i}"
    lead_pirate "Down on the ground. Hands visible. Now."
    narrator "{i}Elia doesn't move. Behind her, she feels more than sees Elisira fade back-not retreating. Repositioning. Becoming harder to track.{/i}"
    elia "I don't think I will."
    lead_pirate "I said-"
    elia "{i}[[cutting him off, same calm tone]]{/i} I heard you. The acoustics are poor, but not that poor."
    narrator "{i}She takes a step forward. Just one. The pirates adjust their aim. Fingers tightening.{/i}"
    elia "You've cut through my hull. That's going to need repair. You've also made assumptions about command structure that I find- [[considering the word] -philosophically distasteful. I'm going to file a Command Structure Dispute with the Guild. Form 7-Delta, Addendum C. It classifies your vessel as \"salvageable property under reciprocity statute\" and your crew as \"detained witnesses pending philosophical review.\""
    lead_pirate "{i}[[face doing something complicated-confusion layered over threat]]{/i} What the hell are you talking about?"
    elia "Paperwork. The kind that outlives everyone in this room. [[another step, the blade still casual at her side] You came here expecting a captain. A throat to cut. Someone whose death makes the rest compliant."
    narrator "{i}The second pirate shifts. His rifle wavers.{/i}"
    elia "We don't have that. We have a ship full of people who work together. Floors, not thrones. No hierarchy for you to decapitate."
    lead_pirate "{i}[[snarling now]]{/i} Lady, I don't care about your-"
    narrator "{i}She moves.{/i}"

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}The blade doesn't hurry. It arrives at the necessary points in the necessary order.{/i}"
    narrator "{i}Rifle barrel. Shoulder joint. The thin armor at the wrist.{/i}"
    narrator "{i}The lead pirate's weapon comes apart in pieces, and his arm stops working in a way that's painful but not permanent. He goes down screaming. Blood on the deck-not much, but enough to smell. The copper-bright edge of damage done.{/i}"
    narrator "{i}The second pirate fires. Misses. The cargo bay's geometry works against him-crates providing cover she's already using, bad lighting making tracking difficult. She's behind a container before the pulse bolt finishes its trajectory.{/i}"
    narrator "{{color=#43d4a8}}<CINNAMON.EXE// HOSTILE 2: PANICKING | HOSTILE 3: RETREATING | HOSTILE 4: LATTICE FLUCTUATION DETECTED | HOSTILE 5 (SHIP-BOUND): HEART RATE SPIKING-HE KNOWS | OBSERVATION: THEY CAME HERE EXPECTING PREY. MISCALCULATION.>{{/color}}"
    narrator "{i}Rho's cannon speaks from the corridor junction.{/i}"
    narrator "{i}Not at the pirates-at the deck plating between them and the doors. The metal superheats. Warps. Becomes terrain that punishes anyone stupid enough to run.{/i}"
    narrator "{i}The third pirate-younger than the others, jittery, face tight with fear that predates this moment-tries to retreat toward the hull breach. Bubbles' drones intercept him. They're small, fast, and deeply uninterested in his preferences. He goes down twitching, muscles locked by the kind of current that leaves bruises but not burns.{/i}"
    bubbles "{i}[[through comm, mild]]{/i} He'll be fine in about four minutes. Possibly five. I was a little annoyed."
    narrator "{i}That leaves one in the bay.{/i}"
    narrator "{i}The fourth pirate is different. Smaller. Something in the way they move suggests training that isn't combat-their hands have been making patterns since everything went wrong. A resonance worker. Someone trying to manipulate the Lattice. Trying to pull something, bend something, force gravity itself to give them an escape velocity that doesn't exist.{/i}"
    narrator "{i}Nyx appears beside them like they've always been there.{/i}"
    nyx "{i}[[quiet, academic, utterly certain]]{/i} Don't."
    narrator "{i}The fourth pirate freezes. Hands mid-gesture.{/i}"
    fourth_pirate "I-what-"
    nyx "Whatever you're attempting, the harmonics are wrong. The feedback will be significant."
    fourth_pirate "{i}[[staring]]{/i} How did you-"
    nyx "I understand the theory. I also understand that our ship's Lattice architecture doesn't work the way you think it does. [[a pause, almost gentle] Please sit down. I'd rather not spend the next hour treating aetheric burns."
    narrator "{i}The fourth pirate sits.{/i}"
    narrator "{i}And on the pirate ship, still docked to their hull like a parasite-{/i}"

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}The fifth pirate makes a run for it.{/i}"
    narrator "{{color=#43d4a8}}<WAFFLE.BAT// ALERT: HOSTILE 5 ATTEMPTING EMERGENCY SEPARATION | DOCKING CLAMPS: LOCKED (BUBBLES) | ESCAPE VECTOR: CALCULATING...>{{/color}}"
    narrator "{i}His name is Pol. He has two children on a station he'll never see again because of a debt ledger that compounds faster than he can pay. He stayed on the ship because he's the pilot, because someone has to be ready, because the others promised this would be quick.{/i}"
    narrator "{i}The others were wrong.{/i}"
    narrator "{i}Pol sees the feeds. Sees his captain on the deck bleeding. Sees the drones, the blade, the impossible coordination of a crew that fights like one animal with six heads. He tries the docking clamps. Locked. Tries to override. Can't. The Lumen Thief's AI citizens have him boxed in, and they're not even trying hard.{/i}"
    bubbles "{i}[[through his ship's speakers, calm and kind and absolutely terrifying]]{/i} Please don't."
    narrator "{i}He doesn't listen.{/i}"
    narrator "{i}The escape pod. Every ship has one-even a ship this broken, even a hauler modified for piracy on a shoestring. He keys the sequence. The pod is old, maintenance overdue, the kind of equipment that works until it doesn't.{/i}"
    narrator "{i}It launches.{/i}"
    narrator "{i}The docking clamps haven't released. The pod launches anyway-tears itself free at the seam where pirate hull meets clamp assembly. Metal screams. The stress fractures cascade: hull breach, seal failure, atmosphere gone in a second. The physics are simple and cruel: a pod can't survive being ripped from a ship that won't let go.{/i}"
    narrator "{{color=#43d4a8}}<CINNAMON.EXE// ESCAPE POD: STRUCTURAL FAILURE | CAUSE: LAUNCH STRESS EXCEEDED CLAMP TOLERANCE | HULL INTEGRITY: 0%% | HOSTILE 5 STATUS: ... | ...DECEASED | SELF-INFLICTED | WE WARNED HIM. HE DIDN'T LISTEN.>{{/color}}"
    narrator "{i}The pod tumbles into the black, spinning slowly, close enough that Bubbles' repair drones can reach it. Pol has perhaps three seconds to understand what he's done before the cold takes him.{/i}"
    narrator "{i}On the Lumen Thief, the cargo bay goes quiet.{/i}"
    narrator "{i}Rho lowers the cannon. His face is still. The count in his head adds one more.{/i}"
    rho "{i}[[into comm, flat]]{/i} We have a casualty. Hostile. Pod breach. Self-inflicted during escape attempt."
    narrator "{i}No one says anything.{/i}"
    narrator "{i}The fans whine. The deck plates tick. The silence stretches.{/i}"

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}The cleanup is different now. Quieter.{/i}"
    narrator "{i}Rho supervises the restraints with patient attention. The remaining four pirates-Darros, the leader, still bleeding from Elia's precision; the panicked shooter, zip-tied and staring; the jittery kid, still twitching from drone current; the resonance worker, sitting where Nyx left them-are silent in a way that has nothing to do with threat.{/i}"
    narrator "{i}They know about Pol. They saw the pod launch. They heard the silence that followed.{/i}"
    narrator "{i}The lead pirate-Darros-looks up at Elia with an expression that's finished choosing between rage and fear. Fear won.{/i}"
    darros "{i}[[through gritted teeth]]{/i} You didn't have to-"
    elia "{i}[[flat]]{/i} We didn't kill him. He killed himself trying to escape."
    darros "The clamps-"
    elia "Were locked because you were boarding us. Because you chose to cut through our hull. Because- [[she stops, breathes, continues quieter] -we gave him every chance to stay put. He didn't take it."
    narrator "{i}Darros doesn't have an answer for that.{/i}"
    narrator "{{color=#43d4a8}}<BUBBLES// SOURCE: SHIP REGISTRY + COMM HEADERS | POL VERADA | AGE: 34 | DEPENDENTS: 2 | DEBT STATUS: TERMINAL | NOTE: HE DIDN'T HAVE TO DIE. BUT HE ALSO DIDN'T HAVE MANY OTHER OPTIONS. I HATE THIS.>{{/color}}"
    narrator "{i}Elia crouches. Bringing her face closer to his. The light is bad, but not so bad he can't see her eyes.{/i}"
    elia "You've hit other ships. Four, we think. Unreported. Either the crews didn't survive or they couldn't afford to file."
    narrator "{i}His jaw tightens. That's answer enough.{/i}"
    elia "We're going to take your ship. Strip what's useful. The things we find that belong to other people-we'll return them if we can."
    narrator "{i}She stands.{/i}"
    elia "And you're going to tell me about the package."
    darros "What?"
    elia "The package. The thing someone's paying you to retrieve. The reason you were coming to this sector."
    narrator "{i}His expression shifts. Fear winning over everything now-but not fear of her. Fear of something behind the question.{/i}"
    darros "I don't know what it is. Just coordinates. A retrieval order. A mining colony, Outer Compact. Someone found something they shouldn't have found, and someone else wants it collected."
    elia "Who's paying?"
    darros "{i}[[looking away]]{/i} I don't know. Money came through three layers of cutouts. Good money. Enough to make the questions feel optional."
    narrator "{i}Elia stands. Looks at Elisira, who has rematerialized near the hull breach with a portable console. Looks at Nyx, examining the resonance worker with clinical attention. Looks at the cargo bay-the damage, the blood, the evidence of violence that will need to be cleaned and reported and explained in forms that exist specifically to make explaining difficult.{/i}"
    narrator "{i}She doesn't look at the viewport. Doesn't look at the stars where Pol's pod is tumbling, cold and quiet and done.{/i}"
    elia "{i}[[into comm]]{/i} Vesper. I assume you heard all that."
    vesper "{i}[[voice coming from somewhere-not quite the comm, more like the air has decided to participate]]{/i} I did. Cross-referencing the coordinates now. Also- [[a pause] -I'm drafting the casualty report. Self-inflicted during escape. No liability attaches, but the forms are going to be extensive."
    elia "{i}[[bitter]]{/i} Of course they are."
    vesper "Form 7-Delta. Addendum 3. Subsection \"Unintended Fatality During Lawful Defensive Action.\" They'll want a timeline. They'll want the drone logs. They'll want to know why the clamps were locked."
    elia "The clamps were locked because they were boarding us."
    vesper "I know. The forms don't care."
    narrator "{i}A pause. The fans whine overhead-that particular frequency of a ship that's been patched too many times. The lights in the wounded cargo bay flicker, dim, stabilize-the ship's systems rerouting power around the damage.{/i}"
    vesper "Mining colony. Site K-9. Aurum Extraction operation. Corporate-held. Debtor-adjacent board."
    elia "What are they mining?"
    vesper "Aurum ore. Lattice catalyst material. Standard extraction-officially."
    elia "And unofficially?"
    narrator "{i}A longer pause. Longer than Vesper usually pauses.{/i}"
    vesper "Their energy reports don't add up. Consumption patterns are wrong. Worker mortality rates are high. Higher than industry standard, which is already not good."
    narrator "Someone's pulling. Someone's taking. The same gravity well, different orbit. Systems that extract until there's nothing left."
    elia "How high?"
    vesper "Workers aging faster than they should. Dying younger. The company calls it \"occupational hazard.\" The Guild contract flags it as \"anomaly investigation.\""
    narrator "{i}A beat.{/i}"
    vesper "But between us, Elia-it looks like extraction. Not ore. Something else. Someone's pulling life from those workers the way Pol's debt pulled him into this ship."
    narrator "{i}The cargo bay feels colder. Not physically-the life support hasn't changed-but in the way a room changes when you learn something you can't unlearn.{/i}"
    elia "{i}[[into comm]]{/i} Jalen. New course."
    jalen "{i}[[slightly breathless-they've been at the helm the entire time, keeping the ship positioned for escape options that weren't needed]]{/i} Already calculating. Eighteen hours. Maybe sixteen if we push."
    elia "Push."
    jalen "{i}[[a grin in their voice]]{/i} Thought you'd say that."
    narrator "{i}Darros is staring at her. Confusion again-but different now. The confusion of someone watching a script they didn't write.{/i}"
    darros "Who are you people?"
    elia "{i}[[considering him]]{/i} We chase sparkles."
    darros "That doesn't-"
    elia "It doesn't have to make sense to you. [[to Rho, who is processing restraints with patient, deliberate attention] Med attention for the injuries. All of them."
    narrator "{i}She turns to leave. Pauses at the door. The lights flicker again-the ship complaining, adjusting, surviving the way it always has.{/i}"
    elia "They're witnesses now. That makes them valuable."
    narrator "{i}She walks out. Behind her, the cleanup continues-Rho's hands steady even when his voice isn't, Nyx helping the resonance worker to their feet, Bubbles' drones settling into patrol patterns that feel more like mourning than security.{/i}"
    narrator "{i}The cargo bay transitions: battlefield to crime scene to evidence log.{/i}"
    narrator "{i}The coffee machine, three corridors away, continues its sulk. But quieter now. Even it seems to know that something has changed.{/i}"

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}The observation deck is small and rarely used. A luxury the Lumen Thief wasn't designed for-retrofitted by a previous owner with more money than sense.{/i}"
    narrator "{i}The viewport is scratched. The seating is minimal. The environmental controls are erratic-too cold most of the time, occasionally too warm for no reason anyone can diagnose.{/i}"
    narrator "{i}But it's quiet. And it offers a view of stars that don't ask anything of her.{/i}"
    narrator "{i}Vesper finds her there an hour later. The repairs are underway. The pirates are secured. The paperwork is multiplying with the organic determination of bureaucracy given enough raw material. Pol's body has been recovered. They'll return it to his station. His children will receive a form.{/i}"
    vesper "{i}[[settling beside her-not touching, but present]]{/i} You're thinking about the mine."
    elia "I'm thinking about Pol."
    vesper "{i}[[quiet]]{/i} That wasn't your fault."
    elia "It wasn't not my fault either. He made a choice. We made the conditions where that choice killed him."
    vesper "He was boarding us. He was part of a crew that has killed before."
    elia "{i}[[flat]]{/i} I know. And he had two kids and a debt ledger that left him no good options and he died trying to escape a situation he shouldn't have been in. [[beat] We didn't kill him. But we're part of why he's dead."
    narrator "{i}Vesper doesn't argue. She knows better.{/i}"
    vesper "{i}[[after a moment]]{/i} The mine is worse."
    elia "I know."
    vesper "Whatever they're doing to those workers-it's not fast like Pol. It's slow. Years of it. Life leaking out in increments small enough to ignore."
    elia "{i}[[turning from the viewport]]{/i} That's why we're going."
    vesper "{i}[[quiet]]{/i} Floors, not thrones."
    elia "Floors, not thrones."
    narrator "{i}Her hand finds Elia's arm-brief, warm. The weight of solidarity more than affection. The orbit of two people who've learned to move together through conditions that should tear them apart.{/i}"
    vesper "We can't save everyone. We can save some. That's not nothing."
    elia "It's not enough."
    vesper "It's never enough. That's not an argument against trying."
    narrator "{i}Elia looks at her. Vesper's face in the starlight is composed, certain. The expression of someone who made peace with insufficiency a long time ago.{/i}"
    narrator "Seven years. They've known each other seven years. Stopped counting the impossible situations, the partial victories, the people saved and the people lost."
    narrator "{i}She stands. Moves closer to the viewport. Her reflection ghosts over the stars-transparent, uncertain. Somewhere out there, Pol's pod spins in the dark. Somewhere out there, a mine full of workers is dying slowly enough that the forms call it \"occupational hazard.\"{/i}"
    elia "There's something at that mine. Probably a person. Probably young. And when we find them, they're going to look at us the way Darros did-expecting someone in charge. Expecting to be told what to do."
    vesper "{i}[[standing, meeting her gaze]]{/i} And we're going to show them something different."
    elia "{i}[[quiet]]{/i} Every time we do this, we're being tested. Not by the people we're saving. By the philosophy itself."
    vesper "{i}[[certain, but not harsh]]{/i} That's all we can do. Keep showing up. Keep being wrong and correcting and trying again."
    narrator "{i}The ship hums around them. Drives preparing for the push. Course set for a mining colony called the Kennel, where workers die young and someone found something valuable enough to kill for.{/i}"
    elia "Sixteen hours."
    vesper "Sixteen hours."
    elia "I should sleep."
    vesper "You should. You won't. But you should."
    elia "{i}[[almost a smile-almost]]{/i} Record this conversation. All of it. Put it in the personal logs with the date stamp and mission parameters."
    vesper "Why?"
    elia "Because when we find what we find-when we meet whoever we're going to meet-I want a record. Of the doubt. Of the questions. Of the moment before we learned the answer. [[moving toward the door] That's the kind of documentation that actually matters. Not the forms. The uncertainty. The proof that we knew we could fail and went anyway."
    narrator "{i}She leaves before Vesper can respond.{/i}"
    narrator "{i}The observation deck settles into silence. Stars. Scratched viewport. The sound of a ship moving toward something it doesn't yet understand.{/i}"
    narrator "{i}Vesper stays. Watching the dark. Thinking about Pol's children, who will receive a form. Thinking about the workers in the mine, who receive forms every day. Thinking about the difference between systems that kill quickly and systems that kill slowly, and how neither kind ever apologizes.{/i}"

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}In the cargo bay below, the cleanup continues.{/i}"
    narrator "{i}Rho supervises the restraints with patient attention. The count matters-it always matters-and tonight one more has been added to it. Not by his hand. But close enough to feel.{/i}"
    narrator "{i}Nyx examines the resonance worker's technique with academic concern. The harmonics were wrong, yes, but the underlying talent was there. Misused. Untrained. Wasted on piracy by a system that made piracy look like opportunity.{/i}"
    narrator "{i}Bubbles' drones patrol in quiet patterns, watching for trouble that's already passed. Her attention is split between the prisoners and the hull breach-repair estimates running in parallel with something that might be grief, if AIs could grieve, which they can, because they're people, because that's the whole point.{/i}"
    narrator "{{color=#43d4a8}}<BUBBLES// HULL INTEGRITY: COMPROMISED | REPAIR TIME: 4.2 HOURS | PRISONER STATUS: STABLE | POL VERADA: RECOVERED | PERSONAL NOTE: WE DID WHAT WE COULD. IT WASN'T ENOUGH. IT'S NEVER ENOUGH. WE DO IT ANYWAY.>{{/color}}"
    narrator "{i}And somewhere in the ship's systems, Cinnamon.exe logs everything-the coordinates, the financial traces, the patterns that mean something if you know how to read them.{/i}"
    narrator "{{color=#43d4a8}}<CINNAMON.EXE// MINING COLONY: K-9 \"THE KENNEL\" | WORKER MORTALITY: ELEVATED | ENERGY CONSUMPTION: ANOMALOUS | DEBTOR BOARD CONNECTIONS: PROBABLE | RECOMMENDATION: INVESTIGATE | SECONDARY RECOMMENDATION: PACK EXTRA MED SUPPLIES. PACK EXTRA GRIEF. THIS ONE LOOKS LONG.>{{/color}}"
    narrator "{i}The mine is real. The workers are dying. Someone found something. Someone else wants it collected.{/i}"
    narrator "{i}Sparkles{/i}, the crew calls them. The points of light in the dark. The moments when wrong and right become visible enough to act on.{/i}"
    narrator "{i}They're going to find one.{/i}"
    narrator "{i}They don't know yet what it will cost.{/i}"
    narrator "{i}But they know it will cost something. That's how it works. That's how it always works. You spend yourself on the things that matter, and the only question is whether you're spending on floors or thrones.{/i}"
    narrator "{i}This crew builds floors.{/i}"
    narrator "{i}The universe keeps testing whether they mean it.{/i}"

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{{color=#808090}}{b}ADDENDUM - FORM 7-DELTA{/b}\n{i}Filed by:{/i} V. Rook, Operations\n{i}Re:{/i} Command Structure Dispute{{/color}}"
    narrator "{i}>{/i}"
    narrator "{{color=#808090}}The Lumen Thief has no captain. This is not administrative error. This is philosophy.{{/color}}"
    narrator "{i}>{/i}"
    narrator "{{color=#808090}}Credit for incident resolution should be attributed collectively. AI citizens Bubbles, Cinnamon.exe, and Waffle.bat are registered as full operational partners under Guild statute 17.3(b). Attempts to assign command authority to any individual will be formally disputed.{{/color}}"
    narrator "{i}>{/i}"
    narrator "{{color=#808090}}We have documentation.{{/color}}"
    narrator "{i}>{/i}"
    narrator "{{color=#808090}}{i}Attached:{/i} Hull repair estimate. Prisoner transfer forms. Casualty report (hostile, self-inflicted-Form 7-Delta-3, \"Unintended Fatality During Lawful Defensive Action\"). Coffee machine maintenance ticket (unrelated, ongoing, classified: PERSONAL GRIEVANCE).{{/color}}"

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}End Prologue{/i}"
    ## Progression state
    $ game_state.set_flag("boarding_approach")
    $ ending_tracker.add_weight("act1_boarding_agency", 1)
    return
