## Generated from 20c_archive_ritual.md by convert_prose.py
## Do not edit manually — re-run converter after prose changes

label act1_20c_archive_ritual:
    pause 0.3
    narrator "{i}After the hearing, the ship goes quiet in the way it does after violence that didn't leave bruises.{/i}"
    narrator "{i}Not silence. A hush.{/i}"
    narrator "{i}The kind of hush that says: everybody is holding their own parts so no one drops.{/i}"
    narrator "{i}Avyanna stands outside Vesper's office with her hands full of paper.{/i}"
    narrator "{i}Copies. Originals. A stack that looks like a weapon if you squint.{/i}"
    narrator "Paper can be burned."
    narrator "Paper can also burn someone else."
    narrator "{i}Vesper opens the door before Avyanna knocks.{/i}"
    vesper "You're hovering."
    avyanna "{i}[[automatic]]{/i} Sorry."
    narrator "{i}She stops.{/i}"
    avyanna "I am hovering."
    narrator "{i}Vesper's mouth twitches-approval that refuses to be cute.{/i}"
    vesper "Come in."

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}The office is the same as always: clean lines, sharp corners, a desk that looks like it has never forgiven anyone.{/i}"
    narrator "{i}Vesper clears a space.{/i}"
    narrator "{i}Not by sweeping things aside. By moving them to exact locations like the room has a map only she can see.{/i}"
    vesper "Set them there."
    narrator "{i}Avyanna sets the stack down carefully, as if the paper is glass.{/i}"
    avyanna "What happens now."
    vesper "Now we make it heavy."
    avyanna "Heavy."
    vesper "So it can't be erased by one bored clerk."

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}Cinnamon's terminal wakes without being prompted, like she heard the word erased and took it personally.{/i}"
    narrator "{{color=#43d4a8}}<CINNAMON.EXE// OBSERVATION: new evidence bundle present | ACTION: generate archive hashes | NOTE: I enjoy permanence>{{/color}}"
    avyanna "You enjoy permanence."
    narrator "{{color=#43d4a8}}<CINNAMON.EXE// RESPONSE: yes | ADDENDUM: hostile systems rely on your belief that nothing persists>{{/color}}"
    narrator "{i}Avyanna swallows.{/i}"
    vesper "Cinnamon, print chain-of-custody forms. Seven copies."
    avyanna "Seven."
    vesper "Three is minimum. Seven is insurance against sabotage."
    avyanna "That's... a lot."
    vesper "It's the point."

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}Vesper takes out a stamp.{/i}"
    narrator "{i}A physical stamp. Metal. Heavy. The kind of tool that feels like law even when it's just ink.{/i}"
    avyanna "Do we have authority to-"
    vesper "Under the Guild's own procedures, yes."
    vesper "Under the Compact's desire to pretend this never happened, no."
    avyanna "Then why-"
    vesper "Because authority is not a moral property."
    vesper "It's a lever."
    narrator "{i}Avyanna watches her stamp the first page.{/i}"
    narrator "{i}THUD.{/i}"
    narrator "{i}Ink blooms: RECEIPT ACKNOWLEDGED.{/i}"
    narrator "{i}The sound makes Avyanna flinch.{/i}"
    narrator "In the mine, stamps meant \"processed.\" Stamps meant \"unavoidable.\""
    narrator "{i}This stamp feels like something else.{/i}"
    vesper "You do the next one."
    narrator "{i}Avyanna's hands freeze.{/i}"
    avyanna "Me?"
    vesper "Yes."
    avyanna "What if I do it wrong."
    vesper "Then we redo it."
    avyanna "That's it."
    vesper "That's it."
    narrator "{i}Avyanna takes the stamp.{/i}"
    narrator "{i}It is heavier than she expected.{/i}"
    narrator "{i}She presses down.{/i}"
    narrator "{i}THUD.{/i}"
    narrator "{i}RECEIPT ACKNOWLEDGED.{/i}"
    narrator "{i}She stares at it.{/i}"
    narrator "My hand made that."
    narrator "{i}Her throat tightens.{/i}"
    vesper "Good."

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}They work.{/i}"
    narrator "{i}Vesper narrates without making it feel like a test.{/i}"
    vesper "Claim summary on top. Evidence list behind. Witness statements separated and indexed. Video hashes in the sealed envelope."
    avyanna "Why separate."
    vesper "So if someone attacks a witness, the evidence survives them."
    narrator "{i}Avyanna's stomach turns.{/i}"
    avyanna "That's... bleak."
    vesper "It's reality."
    vesper "The way we make it less bleak is we don't pretend."
    narrator "{i}Avyanna nods and keeps stamping.{/i}"

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}A soft chime at the door.{/i}"
    narrator "{i}Elisira slips in, silent as policy.{/i}"
    elisira "How's the archive."
    vesper "In progress."
    elisira "Good."
    narrator "{i}Elisira sets a small device on the desk-an external storage brick, scuffed and ordinary.{/i}"
    elisira "Offline copy. Air-gapped."
    avyanna "Why."
    elisira "Because networks can be bribed."
    avyanna "{i}[[quiet]]{/i} And paper can be burned."
    elisira "Yes."
    elisira "So we do both."
    narrator "{i}Elisira's gaze flicks to Avyanna.{/i}"
    elisira "You held yourself in the room."
    avyanna "I almost didn't."
    elisira "Almost is not the outcome."
    narrator "{i}She leaves without ceremony, like approval is a tool to be deployed precisely.{/i}"

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}Rho appears next.{/i}"
    narrator "{i}He leans in the doorway with coffee and the expression of someone pretending he's not here to check on the kid.{/i}"
    rho "Heard you made the clerk blink."
    avyanna "{i}[[blinking]]{/i} I-"
    vesper "{i}[[without looking up]]{/i} She did."
    rho "Nice."
    narrator "{i}He sets a mug down next to Avyanna's elbow.{/i}"
    narrator "{i}Not asking if she wants it. Not demanding gratitude. Just placing warmth in the area.{/i}"
    avyanna "Thank you."
    rho "{i}[[gruff]]{/i} Yeah."
    narrator "{i}He looks at the stacks.{/i}"
    rho "That's a lot of paper."
    vesper "It's not paper. It's weight."
    rho "{i}[[snorts]]{/i} Okay, philosopher."
    vesper "{i}[[flat]]{/i} Don't start."
    narrator "{i}Rho leaves before the coffee becomes a conversation.{/i}"

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}Elia arrives like she can't stand the idea of quiet being too serious for too long.{/i}"
    elia "Are we doing paperwork violence."
    vesper "Yes."
    elia "Delicious."
    avyanna "{i}[[startled laugh]]{/i} That's-"
    elia "A joke. Also true."
    narrator "{i}Elia leans over the desk, reads a page, and her face changes.{/i}"
    narrator "{i}Not joking now. Focused.{/i}"
    elia "{i}[[quiet]]{/i} They wrote her up as \"noncompliant\" for refusing a sedative."
    avyanna "Yes."
    elia "I want to bite someone."
    vesper "Put it in the queue."
    elia "{i}[[bright again]]{/i} Great. I love queues."
    narrator "{i}She reaches out, hesitates, then taps Avyanna's shoulder with one knuckle-light, careful.{/i}"
    elia "You did good, Avy."
    avyanna "That's not a metric."
    elia "It is my metric."
    narrator "{i}Elia points at the stamp.{/i}"
    elia "Can I stamp something."
    vesper "No."
    elia "Cruel."
    vesper "Necessary."
    narrator "{i}Elia exits with a dramatic sigh, leaving behind the faint smell of mischief like a promise.{/i}"

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}Bubbles drifts in last.{/i}"
    narrator "{i}She doesn't speak at first.{/i}"
    narrator "{i}She watches Avyanna stamp and stack and index.{/i}"
    narrator "{{color=#43d4a8}}<BUBBLES// OBSERVATION: trainee performing archival labor | INFERENCE: belonging increasing via contribution | CONFIDENCE: 0.84>{{/color}}"
    avyanna "{i}[[quiet, to Bubbles]]{/i} Is this... crew work."
    bubbles "Yes."
    avyanna "Even though it's just... paper."
    bubbles "Paper is how hostile systems pretend they are not hostile."
    bubbles "We use paper to make them show their teeth."
    narrator "{i}Avyanna's throat tightens.{/i}"
    narrator "We make them show their teeth."
    narrator "{i}Vesper seals the final envelope with a strip that changes color when broken.{/i}"
    vesper "That's it."
    avyanna "That's it."
    narrator "{i}She waits for the crash.{/i}"
    narrator "{i}For someone to say: you did not do enough.{/i}"
    narrator "{i}Instead, Vesper slides a copy folder toward her.{/i}"
    vesper "This one is yours."
    avyanna "Why."
    vesper "Because you are a witness."
    narrator "{i}Avyanna's hands hover over the folder.{/i}"
    narrator "Mine taught me witnesses get punished."
    narrator "{i}She takes it anyway.{/i}"

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}They leave the office together.{/i}"
    narrator "{i}In the atrium, there is a public board with a section labeled RECEIPTS.{/i}"
    narrator "{i}Avyanna has seen other entries there: small disputes, supply issues, petty injustices documented in neat lines.{/i}"
    narrator "{i}Vesper pins one sanitized summary-no names that would get someone killed, just the shape of the crime and the evidence that it happened.{/i}"
    vesper "{i}[[low]]{/i} We don't do this to be liked."
    avyanna "{i}[[quiet]]{/i} We do it because it's true."
    vesper "Yes."
    narrator "{i}A few crew members pause as they pass.{/i}"
    narrator "{i}They read.{/i}"
    narrator "{i}They don't clap. They don't cheer.{/i}"
    narrator "{i}They nod-like a vow acknowledged without noise.{/i}"
    narrator "{i}Avyanna stands beside Vesper and watches her own life become a public weight the mine can't lift easily.{/i}"
    narrator "This is what it feels like to have proof."
    narrator "{i}The ship hums around them, holding the moment without trying to own it.{/i}"

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}Later, Avyanna takes her copy folder back to her quarters.{/i}"
    narrator "{i}She sets it on the small desk like it might bite.{/i}"
    narrator "{i}Then she opens it anyway.{/i}"
    narrator "{i}The first page is the sanitized summary Vesper pinned. The second is the internal index. The third is her own witness statement-her words, typed cleanly, no mine stutter, no apologies baked in.{/i}"
    narrator "{i}Avyanna reads it three times.{/i}"
    narrator "If this existed when I was eight, would it have saved anyone."
    narrator "{i}Her throat tightens.{/i}"
    narrator "{i}She reaches for her notebook and writes another claim.{/i}"
    narrator "{{color=#808090}}{b}CLAIM:{/b} I am allowed to survive.{{/color}}"
    narrator "{i}She stares at it.{/i}"
    narrator "Allowed by whom."
    narrator "{i}She writes the next line carefully.{/i}"
    narrator "{{color=#808090}}{b}ENFORCED BY:{/b} us.{{/color}}"
    narrator "{i}It looks childish.{/i}"
    narrator "{i}It looks like the truth anyway.{/i}"

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}A notification pings on her terminal.{/i}"
    narrator "{{color=#43d4a8}}<CINNAMON.EXE// MESSAGE: archive replication complete | COPIES: 7 | LOCATION: distributed | NOTE: erasure now expensive>{{/color}}"
    avyanna "{i}[[muttering]]{/i} Good."
    narrator "{i}She sits back.{/i}"
    narrator "{i}The quiet in her room is different now.{/i}"
    narrator "{i}Not empty. Not waiting.{/i}"
    narrator "{i}Held.{/i}"
    narrator "{i}She can hear distant voices in the atrium-Elia laughing too loud, Rho complaining about the coffee machine like it's a moral failing, Waffle's text chattering across a screen somewhere.{/i}"
    narrator "{i}For a moment, the mine tries to overlay that sound with its own: sirens, boots, supervisors shouting numbers.{/i}"
    narrator "{i}Avyanna's body tenses.{/i}"
    narrator "{i}Then she remembers the stamp.{/i}"
    narrator "{i}THUD.{/i}"
    narrator "{i}Receipt acknowledged.{/i}"
    narrator "{i}She breathes until the mine recedes.{/i}"

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}She slips the copy folder into the bottom drawer of her desk.{/i}"
    narrator "{i}Not hiding it.{/i}"
    narrator "{i}Storing it like something that will still be there when she needs it.{/i}"
    narrator "{i}She looks at the door.{/i}"
    narrator "{i}Still open, as ship policy.{/i}"
    narrator "{i}She doesn't close it.{/i}"
    narrator "{i}But for the first time, she doesn't stare at it like it's a countdown either.{/i}"
    narrator "I don't have to be ready to run every second."
    narrator "{i}She lies down.{/i}"
    narrator "{i}The pillow smells like clean fabric instead of dust.{/i}"
    narrator "{i}Her hands still tremble, but less.{/i}"
    narrator "{i}She falls asleep with the ugly, miraculous weight of proof in the drawer and the knowledge that the ship will keep humming whether she's awake to guard it or not.{/i}"

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}When she wakes, the first thing her body does is listen.{/i}"
    narrator "{i}Not for sirens.{/i}"
    narrator "{i}For the ship.{/i}"
    narrator "{i}A steady hum. Footsteps in the corridor. A door hiss somewhere distant.{/i}"
    narrator "{i}No shouting. No quota bell. No supervisor voice turning time into threat.{/i}"
    narrator "{i}Her shoulders unclench one notch at a time.{/i}"
    narrator "I slept."
    narrator "{i}She sits up and waits for the panic that usually follows sleep.{/i}"
    narrator "{i}It comes, but smaller. Late. Like the mine is running out of power.{/i}"
    narrator "{i}Avyanna touches the back of her neck where her old tag used to itch.{/i}"
    narrator "{i}Then she stands and opens the drawer.{/i}"
    narrator "{i}The folder is still there.{/i}"
    narrator "{i}The paper didn't vanish overnight. No one \"processed\" it away while she wasn't looking.{/i}"
    narrator "{i}She closes the drawer again, not because she's hiding it-because she's practicing treating permanence as normal.{/i}"

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}In the galley, Rho is already at war with the coffee machine.{/i}"
    rho "{i}[[to the machine]]{/i} You are a liar and a coward."
    elia "{i}[[from the counter]]{/i} It's just a machine."
    rho "It knows what it did."
    narrator "{i}Avyanna pauses in the doorway, watching the scene like it's a documentary about a species she's joining.{/i}"
    narrator "They argue and nobody dies."
    narrator "{i}Bubbles notices her first, as usual.{/i}"
    bubbles "Good morning."
    avyanna "{i}[[quiet]]{/i} Morning."
    narrator "{i}Rho turns, squints at her the way he squints at broken parts.{/i}"
    rho "You sleep."
    avyanna "{i}[[blinking]]{/i} Yes."
    rho "Good."
    narrator "{i}He pushes a plate toward her without asking.{/i}"
    narrator "{i}Eggs. Toast. Something green that might be an herb and not a punishment.{/i}"
    avyanna "{i}[[tight]]{/i} I didn't-"
    rho "Eat."
    avyanna "{i}[[catching herself]]{/i} Why."
    rho "Because you're alive and it's morning and you don't have to earn breakfast."
    narrator "{i}Avyanna's throat tightens.{/i}"
    avyanna "Okay."
    narrator "{i}She sits.{/i}"
    narrator "{i}She eats one bite.{/i}"
    narrator "{i}Her body waits for the ledger to appear and demand repayment.{/i}"
    narrator "{i}Nothing happens.{/i}"
    narrator "{i}Elia watches her chew like it's a magic trick.{/i}"
    elia "See. The ship didn't explode because you accepted food."
    avyanna "{i}[[dry]]{/i} Not yet."
    elia "That's the spirit."

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}Cinnamon's text scrolls on the terminal above the galley counter.{/i}"
    narrator "{{color=#43d4a8}}<CINNAMON.EXE// STATUS: evidence archive stable | NOTE: hostile systems will attempt narrative repair | SUGGESTION: remain observant>{{/color}}"
    avyanna "Narrative repair."
    elia "{i}[[cheerful]]{/i} That means they're going to lie louder."
    rho "And send invoices for the privilege."
    narrator "{i}Avyanna swallows.{/i}"
    avyanna "{i}[[quiet]]{/i} And we keep receipts."
    narrator "{i}Vesper isn't here.{/i}"
    narrator "{i}But the phrase feels like a rail anyway.{/i}"
    bubbles "Yes."
    narrator "{{color=#43d4a8}}<BUBBLES// OBSERVATION: trainee repeating doctrine without prompting | INFERENCE: internalization | CONFIDENCE: 0.83>{{/color}}"
    narrator "{i}Avyanna finishes her toast.{/i}"
    narrator "{i}She doesn't thank anyone five times.{/i}"
    narrator "{i}She doesn't apologize for taking up a chair.{/i}"
    narrator "{i}She just exists in the galley with the others, and the ship allows it like it's always been the rule.{/i}"
    narrator "{i}Avyanna takes her mug to the sink when she's done, because the ship culture prefers it, not because she's afraid of being punished.{/i}"
    narrator "{i}She pauses with her hands in warm water, watching soap bubbles rise and pop.{/i}"
    narrator "Small things can be safe too."
    narrator "{i}She dries her hands and, without looking at anyone for permission, writes one line in her notebook:{/i}"
    narrator "{{color=#808090}}{b}OBSERVATION:{/b} breakfast arrived without an invoice.{{/color}}"
    narrator "{i}Then she puts the notebook away and goes back to the table.{/i}"
    narrator "{i}No one tells her she's taking too long.{/i}"
    narrator "{i}No one asks what she's paying.{/i}"
    narrator "{i}The ship hums like a city that expects its citizens to eat, to wash dishes, to exist-and refuses to make any of it a moral trial.{/i}"
    narrator "{i}For now.{/i}"
    return
