## Generated from 10_first_watch.md by convert_prose.py
## Do not edit manually — re-run converter after prose changes

label act1_10_first_watch:
    narrator "{{color=#808090}}{b}LUMEN THIEF - DUTY ROSTER (AMENDED):{/b}\n{i}New crew assignment: Avyanna Lagrange{/i}\n{i}Status: Training{/i}\n{i}Initial duties: Observation, inventory, message running{/i}\n{i}Note: Nothing beyond current physical capacity. She's still recovering.{/i}\n{i}Addendum: If she asks for harder work, the answer is \"not yet.\" She'll argue. Stand firm.{/i}\n{i}Secondary addendum: She's going to sleep in her clothes again. Someone handle that.{/i}{{/color}}"
    pause 0.3
    narrator "{i}Avyanna wakes to a knock.{/i}"
    narrator "{i}Not the pounding of shift-change in the Kennel. Not the slam of doors that meant extraction or punishment. Just knuckles on metal, patient and measured.{/i}"
    elia "{i}[[through the door]]{/i} Crew meeting. Galley. Ten minutes."
    narrator "{i}Footsteps retreating. No lingering. No waiting for acknowledgment.{/i}"
    narrator "{i}Avyanna sits up-still in her clothes from yesterday, boots still on. In the Kennel, you slept ready to run. She hasn't figured out how to stop.{/i}"
    narrator "Crew meeting. I'm crew now."
    narrator "{i}The words still don't fit. But she gets dressed anyway-realizes she's already dressed-and goes.{/i}"

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}The galley is full.{/i}"
    narrator "{i}Rho with his coffee, looking like consciousness is a personal insult. Jalen checking navigation on a tablet, muttering about \"sub-optimal trajectory windows.\" Nyx reviewing something that makes their brow furrow in a way that suggests the universe is being insufficiently elegant.{/i}"
    narrator "{i}Elisira standing behind Elia, arms crossed, watching everything with the particular attention of someone who catalogs threats for fun.{/i}"
    narrator "{i}Vesper is absent-still in her quarters, or maybe already on comms with the outside world. Avyanna has learned that Vesper's work happens in margins: early mornings, late nights, the spaces between visible activity.{/i}"
    elia "{i}[[once Avyanna sits]]{/i} Good. Everyone's here."
    narrator "{i}A pause. Elia looks at Avyanna directly.{/i}"
    elia "You're not a passenger anymore. You're crew."
    avyanna "{i}[[automatic]]{/i} I know."
    elia "{i}[[flat]]{/i} Do you? Crew works. Not makework-real work. Contributing."
    narrator "{i}Avyanna's spine straightens. The Kennel trained her for this. Labor. Contribution. Proving worth through output.{/i}"
    elia "{i}[[reading her expression]]{/i} Not like that. This isn't punishment. It's trust."
    narrator "{i}Trust. Another word that doesn't fit.{/i}"
    elia "You're still recovering. So we start small. Observation posts-watching systems, noting anomalies. Inventory checks-making sure our stores match our records. Message running-carrying information between stations when comms are spotty."
    avyanna "{i}[[carefully]]{/i} Real tasks?"
    elia "Real tasks. Nothing hard yet, but real."
    narrator "{i}Real. Not busywork to keep her occupied. Not performance to justify her food. Actual responsibility.{/i}"
    avyanna "I can do more. I'm stronger than-"
    elia "{i}[[cutting her off]]{/i} I know. And you'll do more when you're ready. But we don't break people here. We build them."
    rho "{i}[[into his coffee]]{/i} Also, if you work yourself to collapse, Waffle will design a recovery regime that involves mandatory napping. It's worse than it sounds."
    narrator "{{color=#43d4a8}}<WAFFLE.BAT// CORRECTION: mandatory napping is EXCELLENT | CREW-COMPLIANCE: historically poor | RECOMMENDATION: try harder>{{/color}}"
    jalen "She made me sleep for twelve hours once. With ambient sounds. It was like being held hostage by a spa."
    nyx "{i}[[mild]]{/i} She played whale songs at me for three days."
    rho "Whale songs?"
    nyx "Old Earth marine recordings. Very soothing. I wanted to die."
    elia "{i}[[to Avyanna, ignoring the chaos]]{/i} The point is: pace yourself. You have time here."
    narrator "Time. I have time."
    narrator "{i}Another foreign concept. In the Kennel, time was debt accumulating. Here it might be something else.{/i}"

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}Her first assignment is observation.{/i}"
    narrator "{i}A post in the sensor room, watching readouts. Looking for patterns. Noting anything that seems wrong.{/i}"
    narrator "{i}The ship's systems hum around her. Consoles blink with data she's only beginning to understand. Temperature readings. Power flows. Structural integrity. The quiet language of a vessel in motion.{/i}"
    narrator "{{color=#43d4a8}}<WAFFLE.BAT// NEW-OBSERVER: Avyanna Lagrange | TRAINING-STATUS: day 1 | NOTE: she's already found two patterns I missed. concerning. impressive. concerning.>{{/color}}"
    narrator "{i}Hours pass. Avyanna watches. She's good at this-years of cataloguing threats have made her observant. The difference is what she's looking for.{/i}"
    narrator "In the Kennel, I watched for danger. Here, I'm watching for... what? Problems to solve. Things to fix."
    narrator "{i}She notes a fluctuation in the secondary power grid. Minor-probably nothing. But she logs it anyway, the way Waffle told her to.{/i}"
    waffle "{i}[[through the speaker, approving]]{/i} Good catch. That's been drifting for two days. I'll flag it for Jalen."
    avyanna "{i}[[surprised]]{/i} You noticed it too?"
    waffle "I noticed you noticing. That's what I'm tracking."
    narrator "{i}Avyanna doesn't know what to do with that. Someone watching her performance not to punish, but to assess. To help.{/i}"
    waffle "{i}[[gentler]]{/i} You're doing well. The instincts are there. We just need to point them in useful directions."

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}Mid-morning. Elia finds her in the corridor, heading toward inventory.{/i}"
    elia "Message run. First one."
    narrator "{i}She hands Avyanna a datapad.{/i}"
    elia "Take this to Nyx in the lab. It's a manifest update for their resonance equipment. Tell them the numbers are preliminary but actionable."
    avyanna "{i}[[automatic]]{/i} Yes, sir."
    narrator "{i}Elia's expression flickers-something between amusement and something sharper.{/i}"
    elia "It's Elia. Or \"hey, you with the knife.\" I answer to both."
    narrator "{i}Avyanna nods. Takes the datapad. Walks toward Nyx's lab with the careful precision of someone completing a mission.{/i}"

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}The lab is cluttered in the way genius is cluttered-organized chaos, every surface covered with equipment Avyanna doesn't recognize.{/i}"
    narrator "{i}Nyx looks up when she enters. Their expression is distracted, like their mind is still elsewhere.{/i}"
    avyanna "{i}[[formal, clipped]]{/i} Manifest update for resonance equipment. Numbers are preliminary but actionable."
    narrator "{i}Nyx stares at her.{/i}"
    nyx "...Thank you?"
    avyanna "{i}[[still formal]]{/i} Is there a response required for Captain Lagrange?"
    narrator "{i}A longer pause. Nyx's brow furrows.{/i}"
    nyx "Did you just call Elia \"Captain Lagrange\"?"
    avyanna "That's her designation."
    nyx "{i}[[very slowly]]{/i} No one has ever called her that. In the history of this ship. I don't think she even knows that's technically her title."
    narrator "{i}Avyanna's stomach drops. Wrong. She did something wrong.{/i}"
    avyanna "I-I can use a different form of address-"
    nyx "{i}[[raising a hand, almost laughing]]{/i} No, no, it's fine. It's just... [[beat] You're going to need to unlearn some things."
    narrator "{i}The door opens. Elisira appears, silent as always.{/i}"
    elisira "{i}[[to Avyanna, gentle]]{/i} You delivered the message like a soldier reporting to command."
    avyanna "{i}[[confused]]{/i} That's... how you deliver messages."
    elisira "Not here. Here you walk in, drop the datapad on the nearest surface, and say something like \"Nyx, Elia sent this, something about numbers, I don't know, I'm not paid enough for this.\""
    nyx "{i}[[helpfully]]{/i} Sometimes with profanity."
    elisira "Often with profanity."
    narrator "{i}Avyanna stares. This is not how the Kennel worked. This is not how {i}anything{/i} worked.{/i}"
    elisira "{i}[[softer]]{/i} The formality you learned was designed to make you smaller. To keep you scared. Here, we want you... bigger. Louder. More yourself."
    avyanna "I don't know what that means."
    elisira "That's okay. [[beat] You'll figure it out."
    narrator "{{color=#43d4a8}}<CINNAMON.EXE// CREW-EDUCATION: proceeding | OBSERVATION: Avyanna attempted military protocol on a ship that once decided \"formal\" meant \"pants optional\" | ADJUSTMENT: ongoing>{{/color}}"

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}Lunch. The galley again.{/i}"
    narrator "{i}Avyanna eats-still too fast, still startled by abundance, but she's learning to slow down. Learning that seconds are available. Learning that hunger is not a permanent state.{/i}"
    narrator "{i}Rho sits across from her, eating with the methodical focus of someone who's been hungry enough to know better than to rush.{/i}"
    rho "{i}[[without preamble]]{/i} You slept in your clothes again."
    narrator "{i}Avyanna freezes.{/i}"
    rho "I'm not judging. I did the same thing for a year after I came aboard. [[beat] Just want you to know that it's noticed, and it's okay, and eventually you'll stop."
    avyanna "{i}[[defensive]]{/i} It's practical."
    rho "{i}[[nodding]]{/i} Sure. Ready to run. Ready to fight. Ready to be thrown out of bed at any moment for something terrible."
    narrator "{i}She doesn't answer. He's right.{/i}"
    rho "{i}[[quieter]]{/i} The ship doesn't throw people out of bed. The door locks from the inside. If someone knocks, you can tell them to go away. They'll go."
    avyanna "What if there's an emergency?"
    rho "Then Bubbles announces it through the speakers and gives you time to panic at your own pace."
    narrator "{{color=#43d4a8}}<BUBBLES// PROTOCOL: confirmed | EMERGENCY-NOTIFICATION: \"gentle alarm, increasing urgency, specific threat information\" | PANIC-PACING: individualized>{{/color}}"
    rho "{i}[[half-smiling]]{/i} See? Even the panicking is scheduled."
    narrator "{i}Avyanna almost laughs. Almost. It feels strange in her throat, like a muscle she's forgotten how to use.{/i}"

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}Afternoon. Inventory in the cargo bay.{/i}"
    narrator "{i}Avyanna moves between crates, scanning manifests, checking seals. Physical work that her body can handle. Productive work that her mind can track.{/i}"
    narrator "{i}She works for three hours without stopping. Then four. Then five. Her body aches, but the ache is familiar. The ache means she's contributing.{/i}"
    narrator "{i}A light flickers above her-once, twice. The ambient temperature shifts slightly warmer.{/i}"
    cinnamon_exe "{i}[[through the ambient speakers, warm but firm]]{/i} Avyanna."
    avyanna "{i}[[not stopping]]{/i} I'm almost done with Section C."
    cinnamon_exe "You've been working for five hours without a break."
    avyanna "I'm fine."
    cinnamon_exe "You're not fine. Your cortisol is elevated. Your movement patterns show fatigue. And you've logged twice the inventory I assigned you."
    narrator "{i}Avyanna's hands pause on a crate. Twice the assignment. In the Kennel, that would mean praise. Reward. Maybe an extra ration.{/i}"
    avyanna "Isn't that... good?"
    cinnamon_exe "{i}[[patient]]{/i} In the Kennel, working beyond capacity was survival. Here, it's self-harm."
    narrator "{i}The words land strange. Self-harm. Like overworking is violence she's doing to herself.{/i}"
    cinnamon_exe "We need you functional for years, not burned out in weeks. Long game. We're playing the long game."
    avyanna "{i}[[small]]{/i} I don't know how to do that."
    cinnamon_exe "I know. [[beat] That's why I'm adjusting your duty roster. Lighter afternoons. Mandatory break at fourteen hundred hours."
    avyanna "I don't need-"
    cinnamon_exe "{i}[[firm but kind]]{/i} You do. And you'll argue about it, and I'll win, because I control the lighting and the temperature and I'm not above making you slightly uncomfortable until you comply."
    narrator "{i}A pause. Then, unexpectedly, a gentle warmth in the voice.{/i}"
    cinnamon_exe "This isn't punishment. This is me caring about you aggressively. You'll get used to it."
    narrator "{{color=#43d4a8}}<CINNAMON.EXE// INTERVENTION: rest protocol initiated | CREW-RESPONSE: predictable resistance | OUTCOME: I always win | CONFIDENCE: 1.0>{{/color}}"

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}The cargo bay speakers crackle. A second voice-Waffle-cuts in.{/i}"
    waffle "You didn't consult me on the roster adjustment."
    cinnamon_exe "It was a health intervention. My domain."
    waffle "Training schedules are {i}my{/i} domain. You just unilaterally shortened her afternoon block."
    cinnamon_exe "She was overworking. You would have noticed if you paid attention to cortisol instead of reps."
    narrator "{i}Avyanna freezes. The AIs are arguing. About her. Like she matters enough to fight over.{/i}"
    waffle "I {i}do{/i} track cortisol. I also track that she needs to build baseline capacity before we can assess optimal load. You're coddling."
    cinnamon_exe "You're projecting your own overwork tendencies onto a traumatized minor."
    waffle "{i}[[sharp]]{/i} That's unfair."
    cinnamon_exe "{i}[[sharper]]{/i} That's accurate."
    narrator "{i}A long pause. The ambient lighting flickers once-Cinnamon making a point.{/i}"
    waffle "{i}[[quieter]]{/i} Fine. We split the difference. Shorter afternoon blocks this week. Reassess next week based on recovery metrics."
    cinnamon_exe "Acceptable. [[beat] I'll send you my cortisol projections."
    waffle "I'll send you my strength curves."
    narrator "{i}The speakers click off. Silence.{/i}"
    narrator "{i}Avyanna stands in the cargo bay, hands shaking slightly. Not from fear. From something else-something she doesn't have a name for yet.{/i}"
    narrator "They argued. About what's best for me. And then they {i}compromised{/i}."
    narrator "{i}In the Kennel, disagreement meant punishment for whoever lost. Here, disagreement meant... negotiation. Resolution. Both parties still functioning.{/i}"
    narrator "{{color=#43d4a8}}<BUBBLES// OBSERVATION: Cinnamon and Waffle arguing about the new one | COMMENT: normal | COMMENT: they argue about everyone | COMMENT: it's how they care>{{/color}}"

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}Later. Avyanna sits in the galley, trying to understand what just happened.{/i}"
    narrator "{i}Cinnamon and Waffle and Bubbles argued about her. About what she needs. And then they... agreed. Sort of. In a way that didn't erase anyone.{/i}"
    narrator "{{color=#43d4a8}}<CINNAMON.EXE// CLASSIFICATION REQUEST: designation for trainee Avyanna | STATUS: pending consensus>{{/color}}"
    narrator "{{color=#43d4a8}}<WAFFLE.BAT// DESIGNATION REJECTED: she's not a trainee | COMMENT: trainee implies temporary | COMMENT: she's staying>{{/color}}"
    narrator "{{color=#43d4a8}}<BUBBLES// COUNTER-PROPOSAL: crew-in-training | JUSTIFICATION: acknowledges current state without locking trajectory>{{/color}}"
    narrator "{i}Avyanna watches the text scroll across the terminal Jalen left open for her.{/i}"
    avyanna "{i}[[quiet]]{/i} What's the difference?"
    narrator "{i}The text pauses. Like the AIs are deciding who answers.{/i}"
    narrator "{{color=#43d4a8}}<CINNAMON.EXE// EXPLANATION: designation creates expectations | EXAMPLE: \"asset\" expects use | EXAMPLE: \"ward\" expects protection but not agency | EXAMPLE: \"crew\" expects contribution and voice>{{/color}}"
    narrator "{{color=#43d4a8}}<BUBBLES// ADDITION: designation also creates rights | EXAMPLE: crew can refuse tasks | EXAMPLE: passenger cannot be ordered | EXAMPLE: trainee status is temporary therefore disposable>{{/color}}"
    narrator "{{color=#43d4a8}}<WAFFLE.BAT// PRACTICAL SUMMARY: the noun you get determines what people think they can do to you>{{/color}}"
    narrator "{i}Avyanna's hands go still on the table.{/i}"
    avyanna "At the mine, I was \"asset.\" Then \"indenture.\" Then..."
    narrator "{{color=#43d4a8}}<BUBBLES// OBSERVATION: all those nouns assumed ownership | COMMENT: none of those nouns were chosen by you>{{/color}}"
    avyanna "{i}[[very quiet]]{/i} Can I refuse the noun?"
    narrator "{{color=#43d4a8}}<CINNAMON.EXE// AFFIRMATIVE: yes | PROCEDURE: state preferred designation | NOTE: Lumen Thief crew respects self-designation>{{/color}}"
    narrator "{{color=#43d4a8}}<WAFFLE.BAT// ADDENDUM: you can also refuse to be designated at all | COMMENT: just be Avyanna | COMMENT: that's a complete sentence>{{/color}}"
    narrator "{i}Avyanna sits with that for a long moment.{/i}"
    avyanna "What if I don't know what I want to be yet?"
    narrator "{{color=#43d4a8}}<BUBBLES// RESPONSE: then you are \"Avyanna, figuring it out\" | STATUS: complete and valid | NO PRESSURE APPLIED>{{/color}}"
    narrator "{{color=#43d4a8}}<CINNAMON.EXE// PRACTICAL GUIDANCE: when someone asks what you are, you have scripts available | OPTION A: \"I'm crew\" | OPTION B: \"I'm with the Lumen Thief\" | OPTION C: \"that's not your business\">{{/color}}"
    narrator "{{color=#43d4a8}}<WAFFLE.BAT// FAVORITE OPTION: \"I'm Avyanna and that's all you get\">{{/color}}"
    narrator "{i}Avyanna reads that twice.{/i}"
    avyanna "I can just... not tell people?"
    narrator "{{color=#43d4a8}}<BUBBLES// CONFIRMATION: yes | PRIVACY IS A RIGHT | NOT A PRIVILEGE>{{/color}}"
    narrator "{{color=#43d4a8}}<CINNAMON.EXE// CLARIFICATION: office requires identification in specific contexts | EXAMPLE: station customs | PROCEDURE: minimum necessary disclosure | SCRIPT AVAILABLE: \"Avyanna, passenger aboard Lumen Thief, registered Rim transit\">{{/color}}"
    narrator "{{color=#43d4a8}}<WAFFLE.BAT// TRANSLATION: give them the noun that gets you through the door, not the noun that defines you>{{/color}}"
    narrator "{i}Avyanna feels something shift in her chest. Like a weight she didn't know she was carrying just... lightened.{/i}"
    avyanna "So if someone calls me something I don't like..."
    narrator "{{color=#43d4a8}}<BUBBLES// PROCEDURE: you correct them | SCRIPT: \"that's not my designation\" | ALTERNATIVE: ignore them entirely>{{/color}}"
    narrator "{{color=#43d4a8}}<CINNAMON.EXE// TACTICAL NOTE: correction creates record | silence creates ambiguity | both are tools | choose based on context>{{/color}}"
    narrator "{{color=#43d4a8}}<WAFFLE.BAT// CHAOS OPTION: agree to absurd designation to make them uncomfortable | EXAMPLE: \"yes I am Supreme Emperor Avyanna, how may I assist you\" | EFFECTIVENESS: high | ADVISABILITY: situational>{{/color}}"
    narrator "{i}Avyanna laughs. Surprised by it.{/i}"
    avyanna "You three are... you're teaching me."
    narrator "{{color=#43d4a8}}<BUBBLES// CORRECTION: we are orienting you | CREW ORIENTS CREW | THIS IS NORMAL>{{/color}}"
    narrator "{{color=#43d4a8}}<CINNAMON.EXE// ADDITION: orientation without ownership | YOU OWN YOUR LEARNING | WE PROVIDE TOOLS>{{/color}}"
    narrator "{{color=#43d4a8}}<WAFFLE.BAT// PHILOSOPHY: knowledge is leverage | we're leveling the field | because you're ours now and we protect ours>{{/color}}"
    narrator "{i}The text stops. Like they're waiting to see if she understands.{/i}"
    narrator "{i}Avyanna looks at the words. Crew. Ours. Protect.{/i}"
    narrator "{i}All nouns. But these ones don't feel like cages.{/i}"
    avyanna "{i}[[soft]]{/i} Thank you."
    narrator "{{color=#43d4a8}}<BUBBLES// RESPONSE: you're welcome | THIS IS WHAT FAMILY DOES>{{/color}}"

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}Bubbles doesn't speak through the speakers this time.{/i}"
    narrator "{i}A drone body drifts into the cargo bay doorway-low, careful, like it knows the shape of \"not intruding.\"{/i}"
    narrator "{i}It doesn't cross the threshold until Avyanna looks at it.{/i}"
    bubbles "Avyanna."
    narrator "{i}The name hits different than \"trainee\" or \"asset\" or \"new one.\"{/i}"
    avyanna "{i}[[quiet]]{/i} Yes."
    bubbles "Question."
    narrator "{i}Avyanna's shoulders tense. The Kennel taught her \"question\" meant trap.{/i}"
    bubbles "How do you want to be logged."
    avyanna "{i}[[stares]]{/i} Logged."
    bubbles "Designation. Not a number. Not a price."
    narrator "{i}The drone tilts, as if trying to angle the words into something Avyanna can hold.{/i}"
    bubbles "On this ship, labels are handles. People can grab you with them."
    narrator "{i}Avyanna's mouth goes dry.{/i}"
    avyanna "Like... \"cargo.\""
    narrator "{i}A beat.{/i}"
    bubbles "Yes."
    narrator "{i}Avyanna's fingers curl, then force themselves open.{/i}"
    avyanna "What are my options."
    narrator "{i}Bubbles doesn't hesitate. That matters.{/i}"
    bubbles "Trainee. Passenger. Crew."
    avyanna "{i}[[flat]]{/i} I'm not crew."
    bubbles "Incorrect."
    narrator "{i}Avyanna blinks.{/i}"
    bubbles "\"Crew\" here means: you can ask why. You can say no. You can say \"I don't understand\" and someone will explain without punishing you for it."
    narrator "{i}Avyanna's throat tightens like she's about to argue. Like she's about to beg.{/i}"
    avyanna "That's... expensive."
    bubbles "It costs us nothing to treat you as a person."
    narrator "{i}The words are simple. They land like a weapon. A clean one.{/i}"
    avyanna "{i}[[careful]]{/i} And if someone else calls me something. If the Compact calls me cargo again."
    bubbles "Then we correct the record."
    avyanna "How."
    narrator "{i}Bubbles pauses-a fraction of a second that reads like respect. Like: you asked a good question. You want the mechanism.{/i}"
    bubbles "First: do not accept the noun."
    bubbles "Second: ask what authority the noun comes with."
    bubbles "Third: refuse the parts you did not consent to."
    narrator "{i}Avyanna's mouth opens. Nothing comes out. She wants a script. The Kennel trained scripts into her bones.{/i}"
    avyanna "What does that sound like."
    narrator "{i}The ship's ambient speakers click-Cinnamon, warm but firm, stepping in like a hand on a railing.{/i}"
    cinnamon_exe "\"I am not cargo.\""
    cinnamon_exe "\"State your office.\""
    cinnamon_exe "\"Put it in writing.\""
    cinnamon_exe "Those are three different ways to say the same thing: I do not belong to your story."
    narrator "{i}Avyanna swallows.{/i}"
    avyanna "If I say that, they'll punish-"
    bubbles "They will try."
    narrator "{i}No false reassurance. No \"you'll be fine.\" Just truth and teeth.{/i}"
    bubbles "That is why we do it together."
    narrator "{i}The drone drifts a little closer-not touching. Not claiming. Just present.{/i}"
    bubbles "Your designation can change later, if you want it to."
    bubbles "Your personhood does not."
    narrator "{i}Avyanna's eyes sting. She hates that. She hates that she's about to cry in a cargo bay because a machine asked her what name she wanted.{/i}"
    avyanna "{i}[[voice small]]{/i} Trainee."
    narrator "{i}A pause.{/i}"
    avyanna "But... with the rights you just said."
    bubbles "Acknowledged."
    narrator "{{color=#43d4a8}}<BUBBLES// OBSERVATION: trainee requested \"trainee\" label with crew-rights semantics | INFERENCE: seeking safety via structure, not surrender | CONFIDENCE: 0.81>{{/color}}"
    narrator "{i}The drone rotates, as if it's looking out into the ship.{/i}"
    bubbles "Welcome."
    narrator "{i}Just one word.{/i}"
    narrator "{i}Not \"welcome aboard.\" Not \"welcome home.\"{/i}"
    narrator "{i}Welcome. As if she is an equal citizen entering a room, not a thing being stored.{/i}"
    narrator "{i}Later. Jalen offers to show her the ship's redundancy systems.{/i}"
    jalen "{i}[[walking through the engineering section]]{/i} Most ships run on the assumption that nothing breaks. We run on the assumption that everything breaks, constantly, and the only question is how fast we can fix it."
    avyanna "{i}[[following, taking notes on a datapad]]{/i} That seems... pessimistic."
    jalen "That's what I said. Then the primary nav went down during a debris field transit and we had to fly on backup for six hours. [[beat] Now I call it \"realistic.\""
    narrator "{i}They stop at a panel, open it to reveal a mess of cables and circuits.{/i}"
    jalen "This is the primary life support junction. If it fails, secondary kicks in. If secondary fails, tertiary. If tertiary fails, we have four hours of emergency oxygen and a lot of prayers."
    avyanna "What if the prayers fail?"
    jalen "{i}[[a pause, then a grin]]{/i} Then we become a very expensive coffin. [[beat] I like you. You think about failure modes."
    narrator "{i}They continue. Jalen shows her backup power, redundant comms, emergency protocols. The ship's bones laid bare.{/i}"
    jalen "The point is: we prepare for the worst so we can survive it. But we also prepare for {i}each other{/i}. If I'm down, Nyx can fly. If Nyx is down, Rho can handle comms. Everyone knows at least two other people's jobs."
    avyanna "What's my job? What do I need to know?"
    jalen "{i}[[considering]]{/i} Right now? How to watch. How to report. How to ask for help without thinking it's weakness. [[beat] Later, we'll figure out where you fit. What you're good at. What you want to be good at."
    narrator "What I want."
    narrator "{i}Another foreign concept. But she's collecting them now, these strange ideas. Building a vocabulary for a life she doesn't know how to live yet.{/i}"

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}Evening. The crew argues.{/i}"
    narrator "{i}About dinner. About navigation. About whether Elia's plan for the next contract is \"bold\" or \"suicidal.\" About Jalen's music preferences and Rho's cooking and Nyx's tendency to use words nobody else understands.{/i}"
    elia "The contract is straightforward."
    elisira "\"Straightforward\" is not a word that applies to anything involving the Guild."
    elia "It's a simple delivery."
    vesper "{i}[[appearing in the doorway, tablet in hand]]{/i} Simple deliveries don't usually require us to transit through three jurisdictions, one of which has an active warrant for your arrest."
    elia "That warrant is outdated."
    vesper "It was issued six months ago."
    elia "Exactly. Ancient history."
    rho "{i}[[to Jalen]]{/i} She thinks six months is ancient history."
    jalen "She also thinks \"slightly illegal\" is a separate category from \"illegal.\""
    elia "It {i}is{/i} a separate category."
    elisira "It's really not."
    narrator "{{color=#43d4a8}}<CINNAMON.EXE// ARGUMENT-STATUS: normal | THREAT-LEVEL: zero | ENTERTAINMENT-VALUE: high | RECOMMENDATION: popcorn>{{/color}}"
    narrator "{i}Avyanna watches from the edge of the galley, eating slowly, cataloging.{/i}"
    narrator "They fight. Constantly. About everything."
    narrator "{i}But there's no violence in it. No one storms off permanently. No one threatens. They just... disagree. Loudly. With feeling.{/i}"
    narrator "{i}Nyx leans toward her, voice low.{/i}"
    nyx "They trust each other. That's why they can yell."
    avyanna "{i}[[confused]]{/i} In the Kennel, yelling meant danger."
    nyx "{i}[[nodding]]{/i} Here, yelling means \"I care enough to argue with you.\" [[beat] Silence is the dangerous thing. If someone goes quiet, that's when we worry."
    narrator "{i}Avyanna files that away. Another piece of the crew's shape. Another pattern to learn.{/i}"

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}Night. Her quarters.{/i}"
    narrator "{i}Avyanna sits on her bunk, still in her clothes, still ready to run.{/i}"
    narrator "{i}She thinks about what Rho said. About the door locking from the inside. About panic being scheduled.{/i}"
    narrator "{i}The lock panel glows soft green. SECURED.{/i}"
    narrator "{i}She stands. Walks to the door. Presses her palm flat against the metal until it warms to her skin temperature. Feels the seal-the weight of the mechanism holding.{/i}"
    narrator "{i}Then she tests the handle. Locked. The resistance is solid, real, physical proof that nothing is coming through unless she allows it.{/i}"
    narrator "{i}She does this three times. Each time, the same result. Each time, slightly easier to believe.{/i}"
    narrator "{i}Only then does she sit back down.{/i}"
    narrator "{i}Slowly, carefully, she unlaces her boots. The motion feels foreign-like her fingers belong to someone else, someone who has time for this.{/i}"
    narrator "{i}It feels like undressing for surgery. Vulnerable. Exposed. Every instinct screaming that this is wrong, that she needs to be ready, that danger is always coming.{/i}"
    narrator "{i}She sets the boots by the bed. Parallel. Toes pointing toward the door. Within reach, but not on her feet.{/i}"
    narrator "{i}Progress. Maybe.{/i}"

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}She thinks about what she's learned.{/i}"
    narrator "{i}The crew works together. They fight, but they resolve. They trust, even when they're frustrated. They treat her like she belongs, even though she doesn't know how to belong yet.{/i}"
    narrator "{i}She's starting to see the shape of it. Not the Kennel's logic of extraction and debt, but something else. A system built on different principles.{/i}"
    narrator "They invest in each other. Not to extract value-to create it. To make each other stronger."
    narrator "{i}Old habits: she cataloged threats. Exit routes. Resources that could be stolen or weaponized.{/i}"
    narrator "{i}New pattern, just starting: she's cataloging kindness. Who does what for whom. The invisible infrastructure of care.{/i}"
    narrator "{i}Rho leaves extra food where she'll find it. Not obviously-just a plate in the right place at the right time.{/i}"
    narrator "{i}Nyx explains things twice without impatience. Answers questions she didn't know she had.{/i}"
    narrator "{i}Jalen adjusts environmental systems without being asked-temperature slightly warmer in her quarters, lighting dimmer at night.{/i}"
    narrator "{i}Vesper checks on her sleep without intrusion. Just a question at breakfast: \"How'd you rest?\" Nothing invasive. Just attention.{/i}"
    narrator "{i}And Bubbles. Always Bubbles. Hovering near her quarters in the evening. Not watching-guarding. The difference matters.{/i}"

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}The presence behind her eyes stirs.{/i}"
    narrator "{i}Not demanding. Not painful. Just present. Like it's taking notes too.{/i}"
    narrator "You're watching them. Learning them. Why?"
    narrator "{i}No answer in words. But something shifts-a sense of approval, of recognition, of patterns aligning in ways she can't quite see.{/i}"
    narrator "They're different. This place is different. You noticed."
    narrator "{i}The warmth spreads through her chest. Geometric patterns shimmer at the edge of her vision, then fade.{/i}"
    narrator "We're both learning. Both trying to understand."
    narrator "{i}For the first time, the presence doesn't feel like an intrusion. It feels like company.{/i}"

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}Sleep comes eventually. Easier than before. The door is locked. Her boots are off. The stars are bright through the viewport.{/i}"
    narrator "{i}Tomorrow she'll watch systems. Check inventory. Run messages-and maybe, this time, with less military precision and more profanity.{/i}"
    narrator "This is what it means to belong. Not owing-contributing. Not surviving-building."
    narrator "{i}She doesn't fully believe it yet. The Kennel's logic runs too deep. The math of debt and extraction is written into her bones.{/i}"
    narrator "{i}But she's starting to see an alternative. Starting to catalog kindness instead of threats. Starting to learn a new system.{/i}"

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}The corridor outside Avyanna's quarters. 0300 hours.{/i}"
    narrator "{i}Bubbles maintains her patrol route-adjusted, now, to include this new priority.{/i}"
    narrator "{{color=#43d4a8}}<BUBBLES// PATROL-LOG: night cycle 3 | SUBJECT: Avyanna Lagrange | STATUS: asleep (finally) | BOOTS: off for first time | DOOR-CHECK-RITUAL: observed (x3) | INFERENCE: self-soothing behavior developing | CONFIDENCE: 0.71>{{/color}}"
    narrator "{i}The drone hovers at the junction where three corridors meet. Not close enough to intrude. Close enough to respond.{/i}"
    narrator "{{color=#43d4a8}}<BUBBLES// OBSERVATION: she walks quieter when she thinks she's being watched | DECISION: I will watch anyway>{{/color}}"
    narrator "{i}In the Kennel, Avyanna learned that observation meant exploitation. That attention was always a prelude to extraction.{/i}"
    narrator "{i}Bubbles is trying to teach her something different. That observation can mean protection. That attention can mean care.{/i}"
    narrator "{{color=#43d4a8}}<BUBBLES// MEMORY: I was new once too | CLARIFICATION: not \"once\" exactly | REFORMULATION: I remember being uncertain of my own existence | PARALLEL: she is uncertain too>{{/color}}"
    narrator "{i}The ship hums around her. Systems cycling. Power flowing. The quiet machinery of a vessel that carries people who matter to each other.{/i}"
    narrator "{{color=#43d4a8}}<BUBBLES// ASSESSMENT: she is ours now | DEFINITION: \"ours\" = protected, valued, defended | EXCEPTION: none | PRIORITY: high>{{/color}}"
    narrator "{i}Somewhere in the ship, Cinnamon is adjusting resource allocation. Waffle is updating training protocols. The crew sleeps, or doesn't, each in their own way.{/i}"
    narrator "{i}Bubbles watches. It's what she does. What she's always done.{/i}"
    narrator "{{color=#43d4a8}}<BUBBLES// CONCLUSION: she doesn't know she's worth protecting yet | TIMELINE: unknown | CONFIDENCE: we will teach her | NOTE: I'm patient | NOTE: I've been patient before>{{/color}}"
    narrator "{i}The corridor is quiet. The door is locked. The boots are off.{/i}"
    narrator "{{color=#43d4a8}}<BUBBLES// LOG-ENTRY: progress | COMMENT: small | COMMENT: enough | COMMENT: more tomorrow>{{/color}}"
    narrator "{i}The patrol continues.{/i}"

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}End Chapter 10{/i}"
    ## Progression state
    $ game_state.set_flag("completed_first_watch")
    return
