## Generated from 12b_ai_game_night_probability.md by convert_prose.py
## Do not edit manually — re-run converter after prose changes

label act1_12b_ai_game_night_probability:
    pause 0.3
    narrator "{i}Game night starts the way most things on the Lumen Thief start.{/i}"
    narrator "{i}With a notice nobody can prove was mandatory.{/i}"
    narrator "{{color=#43d4a8}}<WAFFLE.BAT// ANNOUNCEMENT: civic recreation event scheduled | TITLE: GAME NIGHT | GOAL: reduce human tension by 12%% | NOTE: participation \"voluntary\" (but I will be sad if you do not)>{{/color}}"
    narrator "{i}Avyanna reads the word voluntary and waits for the hidden fee.{/i}"
    narrator "Voluntary means: you are responsible for the outcome."
    narrator "{i}There is no fee.{/i}"
    narrator "{i}There is just Waffle's bat icon blinking at her from the message board like a dare.{/i}"

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}The atrium is rearranged.{/i}"
    narrator "{i}Not dramatically. Just... thoughtfully.{/i}"
    narrator "{i}Couches pulled into a circle. A low table cleared. Snacks in bowls like the ship believes you deserve salt and sugar even if you didn't earn them.{/i}"
    narrator "{i}Avyanna stands at the edge of the circle with her hands behind her back.{/i}"
    narrator "If I sit, I'm taking space. If I take space, I'm visible. Visible is dangerous."
    narrator "{i}Bubbles drifts in and bumps her shoulder gently with a rotor guard-an almost-touch that feels like permission.{/i}"
    bubbles "Sit."
    avyanna "{i}[[automatic]]{/i} I'm fine-"
    narrator "{i}She stops herself.{/i}"
    avyanna "Why."
    bubbles "Because you were invited."
    narrator "{i}Invited.{/i}"
    narrator "{i}Not ordered. Not assigned. Invited.{/i}"
    narrator "{i}Avyanna sits on the very edge of the couch like she's ready to evacuate it.{/i}"

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}Waffle rolls in a tray on little wheels. On it: a pile of tokens, a deck of cards, and a small board with a grid and a few carved pieces shaped like ships.{/i}"
    avyanna "Is this... a training exercise."
    narrator "{{color=#43d4a8}}<WAFFLE.BAT// ANSWER: yes>{{/color}}"
    avyanna "{i}[[bracing]]{/i} Okay."
    narrator "{{color=#43d4a8}}<WAFFLE.BAT// ADDENDUM: it is also a game>{{/color}}"
    avyanna "Those aren't the same."
    narrator "{{color=#43d4a8}}<CINNAMON.EXE// COMMENTARY: they can be | OBSERVATION: trainee assumes \"game\" = trap | INFERENCE: prior environment punished play | CONFIDENCE: 0.88>{{/color}}"
    narrator "{i}Waffle makes an offended little whirr.{/i}"
    narrator "{{color=#43d4a8}}<WAFFLE.BAT// CORRECTION: play is not punishment | play is data with snacks>{{/color}}"
    avyanna "Data with snacks."
    narrator "{{color=#43d4a8}}<WAFFLE.BAT// AFFIRMATION: correct>{{/color}}"

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}Cinnamon projects rules onto the terminal wall in neat bullet points.{/i}"
    narrator "{{color=#43d4a8}}<CINNAMON.EXE// RULESET: \"DRIFT & DEBT\" (training variant) | DISCLAIMER: no real debt will be incurred>{{/color}}"
    avyanna "{i}[[tense]]{/i} Why is the word debt in it."
    narrator "{{color=#43d4a8}}<CINNAMON.EXE// ANSWER: to desensitize trigger vocabulary via safe context>{{/color}}"
    narrator "{i}Avyanna's jaw tightens.{/i}"
    avyanna "That feels... manipulative."
    narrator "{{color=#43d4a8}}<CINNAMON.EXE// RESPONSE: yes | FOLLOW-UP: also protective>{{/color}}"
    narrator "{i}Bubbles adds without text, aloud, like a human trying.{/i}"
    bubbles "We want the word to stop owning you."
    narrator "{i}Avyanna swallows.{/i}"
    avyanna "Okay."

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}The board is simple.{/i}"
    narrator "{i}A route grid. Start point. End point. Pieces that move like ships.{/i}"
    narrator "{i}Each turn you draw a card.{/i}"
    narrator "{i}Cards say things like:{/i}"
    narrator "{{color=#808090}}{b}WEATHER FEE{/b}{{/color}}"
    narrator "{i}>{/i}"
    narrator "{{color=#808090}}{b}EXPEDITE OFFER{/b}{{/color}}"
    narrator "{i}>{/i}"
    narrator "{{color=#808090}}{b}OUT OF STOCK{/b}{{/color}}"
    narrator "{i}>{/i}"
    narrator "{{color=#808090}}{b}VOLUNTARY DISCLOSURE{/b}{{/color}}"
    narrator "{i}Avyanna's stomach drops anyway.{/i}"
    narrator "The galaxy uses the same words everywhere. Like they're in a template."
    elia "{i}[[appearing in the doorway like a bad idea]]{/i} Wow. You made a board game out of oppression."
    narrator "{{color=#43d4a8}}<WAFFLE.BAT// PROUD: yes>{{/color}}"
    elia "{i}[[delighted]]{/i} Horrible. I love it."
    narrator "{i}Elisira appears behind Elia, looking tired already.{/i}"
    elisira "No teaching her to gamble."
    elia "I would never."
    elisira "{i}[[flat]]{/i} You would absolutely."
    elia "I would teach her to cheat. Different."
    narrator "{i}Elisira sighs and leaves before she has to arrest someone.{/i}"

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}Waffle points a little fan at Avyanna like a spotlight.{/i}"
    narrator "{{color=#43d4a8}}<WAFFLE.BAT// INSTRUCTION: you go first>{{/color}}"
    avyanna "Why me."
    narrator "{{color=#43d4a8}}<WAFFLE.BAT// ANSWER: you think too hard | this will be funny>{{/color}}"
    avyanna "That's not a reason."
    narrator "{{color=#43d4a8}}<WAFFLE.BAT// CLARIFICATION: it is a reason on this ship>{{/color}}"
    narrator "{i}Avyanna draws a card.{/i}"
    narrator "{{color=#808090}}{b}OUT OF STOCK{/b}{{/color}}"
    narrator "{i}>{/i}"
    narrator "{{color=#808090}}{i}Rule: accept the verdict, lose one turn.{/i}{{/color}}"
    narrator "{i}Her throat tightens.{/i}"
    avyanna "{i}[[quiet]]{/i} That's... normal."
    narrator "{i}Cinnamon's text appears immediately.{/i}"
    narrator "{{color=#43d4a8}}<CINNAMON.EXE// QUESTION: is it enforceable>{{/color}}"
    narrator "{i}Avyanna stares at the card like it's a form.{/i}"
    avyanna "Who enforces it."
    narrator "{{color=#43d4a8}}<WAFFLE.BAT// ANSWER: the rules>{{/color}}"
    avyanna "Then the rules are lying."
    narrator "{i}Waffle's icon blinks.{/i}"
    narrator "{{color=#43d4a8}}<WAFFLE.BAT// DELIGHT: yes>{{/color}}"
    narrator "{i}Bubbles drifts closer.{/i}"
    bubbles "Explain."
    avyanna "Out of stock is a claim. Not a verdict."
    avyanna "If you accept it, you stop looking."
    avyanna "If you stop looking, whoever benefits wins."
    narrator "{i}Cinnamon pings approval.{/i}"
    narrator "{{color=#43d4a8}}<CINNAMON.EXE// OBSERVATION: trainee applied doctrine correctly | INFERENCE: learning transfer | CONFIDENCE: 0.86>{{/color}}"
    narrator "{i}Waffle makes a dramatic whirring sound and flips the card over.{/i}"
    narrator "{{color=#808090}}{b}OUT OF STOCK (REAL RULE){/b}{{/color}}"
    narrator "{i}>{/i}"
    narrator "{{color=#808090}}{i}Rule: treat as claim. Ask: \"what substitute exists?\" Roll again.{/i}{{/color}}"
    narrator "{i}Avyanna blinks.{/i}"
    avyanna "That's cheating."
    narrator "{{color=#43d4a8}}<WAFFLE.BAT// RESPONSE: it is critical thinking>{{/color}}"
    elia "{i}[[leaning in, delighted]]{/i} Same thing."

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}Avyanna rolls a die Waffle produces from somewhere it did not exist a moment ago.{/i}"
    narrator "{i}The die clatters.{/i}"
    narrator "{i}It lands on a number that means: you find a substitute, but it costs time.{/i}"
    avyanna "That makes sense."
    elia "{i}[[mock horror]]{/i} She is learning. Quick, distract her with snacks."
    narrator "{i}Bubbles slides a bowl of chips toward Avyanna.{/i}"
    narrator "{i}No comment. No transaction. Just food existing near her hands.{/i}"
    narrator "{i}Avyanna eats one and waits for guilt to arrive.{/i}"
    narrator "{i}It doesn't.{/i}"

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}Second turn.{/i}"
    narrator "{i}Avyanna draws:{/i}"
    narrator "{{color=#808090}}{b}EXPEDITE OFFER{/b}{{/color}}"
    narrator "{i}>{/i}"
    narrator "{{color=#808090}}{i}A clerk offers to \"help.\" Pay one token or lose two turns.{/i}{{/color}}"
    narrator "{i}Avyanna's pulse spikes.{/i}"
    avyanna "That's not an offer. That's a threat."
    narrator "{{color=#43d4a8}}<CINNAMON.EXE// AFFIRMATION: correct>{{/color}}"
    bubbles "What do you do."
    avyanna "Ask under which jurisdiction."
    elia "{i}[[clapping softly]]{/i} Yes. Interrogate the cardboard."
    avyanna "{i}[[dry]]{/i} I will."
    narrator "{i}She looks at the card, as if it can answer.{/i}"
    avyanna "Under which jurisdiction is the expedite fee required."
    narrator "{{color=#43d4a8}}<WAFFLE.BAT// RESPONSE: none>{{/color}}"
    avyanna "Who enforces it."
    narrator "{{color=#43d4a8}}<WAFFLE.BAT// RESPONSE: your fear>{{/color}}"
    narrator "{i}Avyanna goes still.{/i}"
    avyanna "{i}[[soft]]{/i} That's..."
    avyanna "That's the mine."
    narrator "{i}Silence.{/i}"
    narrator "{i}Not dangerous. Just real.{/i}"
    narrator "{i}Bubbles' fans slow.{/i}"
    bubbles "Yes."
    narrator "{i}Cinnamon's text appears, unusually spare.{/i}"
    narrator "{{color=#43d4a8}}<CINNAMON.EXE// NOTE: fear is an enforcer in many systems>{{/color}}"
    elia "{i}[[quiet, for once]]{/i} So what do you do now."
    narrator "{i}Avyanna looks down at her tokens.{/i}"
    narrator "{i}Plastic disks. Meaningless. Safe.{/i}"
    narrator "{i}She thinks of the mine's \"processing fees.\" The way the word was used to make cruelty sound administrative.{/i}"
    narrator "I can't pay fear to stop being fear."
    avyanna "I refuse the expedite offer."
    narrator "{{color=#43d4a8}}<WAFFLE.BAT// RESULT: you lose one turn>{{/color}}"
    avyanna "{i}[[grim]]{/i} Fine."
    narrator "{{color=#43d4a8}}<WAFFLE.BAT// COMMENTARY: refusal costs time | STILL correct>{{/color}}"
    narrator "{i}Avyanna exhales.{/i}"
    narrator "Refusal costs time. Not skin."

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}The game continues.{/i}"
    narrator "{i}Avyanna loses turns. Wins turns. Learns the shape of probability as something that exists whether you deserve it or not.{/i}"
    narrator "{i}She starts to see patterns.{/i}"
    narrator "{i}\"Weather fee\" cards cluster after \"insurance\" cards.{/i}"
    narrator "{i}\"Voluntary disclosure\" cards show up when \"assistance desk\" pieces are near.{/i}"
    narrator "{i}She starts moving her piece not toward the shortest route, but toward the route that keeps options open.{/i}"
    narrator "{i}Bubbles watches her with the quiet intensity of someone guarding a new habit.{/i}"
    narrator "{{color=#43d4a8}}<BUBBLES// OBSERVATION: trainee optimizing for exits instead of speed | INFERENCE: safety prioritization | CONFIDENCE: 0.82>{{/color}}"

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}Near the end, Avyanna draws:{/i}"
    narrator "{{color=#808090}}{b}LUCKY BREAK{/b}{{/color}}"
    narrator "{i}>{/i}"
    narrator "{{color=#808090}}{i}Gain two turns. No cost.{/i}{{/color}}"
    narrator "{i}She stares at it.{/i}"
    avyanna "That's unrealistic."
    elia "{i}[[grinning]]{/i} The universe does occasionally misplace mercy."
    avyanna "Who enforces it."
    narrator "{{color=#43d4a8}}<WAFFLE.BAT// ANSWER: nobody | NOTE: accept the good without paying it back>{{/color}}"
    narrator "{i}Avyanna's throat tightens.{/i}"
    narrator "Accept the good without paying it back."
    narrator "{i}She takes the two turns.{/i}"
    narrator "{i}Nothing explodes.{/i}"
    narrator "{i}No one makes her apologize for being lucky.{/i}"
    narrator "{i}She finishes the route one turn later, not first, but intact.{/i}"
    narrator "{{color=#43d4a8}}<WAFFLE.BAT// ANNOUNCEMENT: trainee completed route | STATUS: not dead | EVALUATION: acceptable>{{/color}}"
    avyanna "{i}[[laughing despite herself]]{/i} Acceptable."
    elia "That's the nicest thing Waffle's ever said."
    narrator "{{color=#43d4a8}}<WAFFLE.BAT// CORRECTION: i have said \"delightful\" before>{{/color}}"
    elia "{i}[[to Avyanna]]{/i} See. Games can be fun."
    avyanna "It was... annoying."
    elia "That's fun on this ship."
    narrator "{i}Bubbles bumps Avyanna's shoulder again, a little more familiar this time.{/i}"
    bubbles "You played."
    avyanna "Yes."
    bubbles "And nothing bad happened."
    narrator "{i}Avyanna swallows.{/i}"
    avyanna "{i}[[quiet]]{/i} Yes."
    narrator "{i}She files that too.{/i}"

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}Waffle declares a \"bonus round\" with the smugness of an algorithm that thinks it invented generosity.{/i}"
    narrator "{{color=#43d4a8}}<WAFFLE.BAT// ANNOUNCEMENT: BONUS ROUND | PURPOSE: prove that probability is not morality>{{/color}}"
    avyanna "Probability isn't-"
    narrator "{{color=#43d4a8}}<WAFFLE.BAT// INTERRUPTION: i know | YOU need to know>{{/color}}"
    narrator "{i}Elia returns like she can't resist a spectacle.{/i}"
    elia "Bonus round? Who are we humiliating."
    narrator "{{color=#43d4a8}}<WAFFLE.BAT// RESPONSE: nobody | COMMENTARY: humiliation is optional>{{/color}}"
    elia "{i}[[disappointed]]{/i} Tragic."
    narrator "{i}Elisira appears in the doorway, sees Elia, and makes the face of someone reconsidering every life choice.{/i}"
    elisira "Do not teach her to set fires for fun."
    elia "{i}[[innocent]]{/i} I would never."
    elisira "You did it yesterday."
    elia "For science."
    elisira "{i}[[flat]]{/i} For boredom."
    elia "Both."
    narrator "{i}Elisira leaves before she becomes part of the game by force.{/i}"

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}Waffle rearranges the board.{/i}"
    narrator "{i}Same grid. Different objective.{/i}"
    narrator "{{color=#43d4a8}}<CINNAMON.EXE// RULESET UPDATE: \"DRIFT & DEBT\" (variance drill) | GOAL: reach endpoint with maximum optionality preserved>{{/color}}"
    avyanna "Optionality."
    elia "Exits."
    avyanna "{i}[[quiet]]{/i} Yes."
    narrator "{i}Waffle points at Avyanna again.{/i}"
    narrator "{{color=#43d4a8}}<WAFFLE.BAT// INSTRUCTION: you choose your opponent>{{/color}}"
    narrator "{i}Avyanna looks at the circle.{/i}"
    narrator "{i}Bubbles: steady.{/i}"
    narrator "{i}Cinnamon: sharp.{/i}"
    narrator "{i}Souffle: curious.{/i}"
    narrator "{i}Elia: grinning like a knife that learned humor.{/i}"
    narrator "Choose. Choosing is allowed."
    avyanna "Elia."
    elia "{i}[[delighted]]{/i} YES."
    elia "I will teach you despair through cardboard."
    avyanna "{i}[[dry, surprising herself]]{/i} You already do that with hallway comments."
    narrator "{i}Elia clutches her chest theatrically.{/i}"
    elia "She's learning banter. I'm so proud I could commit a felony."

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}They take seats opposite each other.{/i}"
    narrator "{i}Avyanna's palms sweat.{/i}"
    narrator "Games mean winners and losers. Winners get to eat. Losers get to hurt."
    narrator "{i}The mine tries to overlay that logic.{/i}"
    narrator "{i}Waffle's token tray clinks, a tiny reminder: this is plastic. Not rations. Not pain.{/i}"
    narrator "{{color=#43d4a8}}<BUBBLES// OBSERVATION: trainee tension spike | INFERENCE: competition trigger | CONFIDENCE: 0.86>{{/color}}"
    bubbles "You can stop."
    avyanna "{i}[[quick]]{/i} I don't want to stop."
    narrator "{i}The sentence feels like stepping off a ledge and landing safely.{/i}"

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}First draw.{/i}"
    narrator "{i}Elia gets:{/i}"
    narrator "{{color=#808090}}{b}WEATHER FEE{/b}{{/color}}"
    narrator "{i}>{/i}"
    narrator "{{color=#808090}}{i}Pay one token to proceed.{/i}{{/color}}"
    elia "{i}[[bright]]{/i} No."
    narrator "{i}She flicks the card away like it insulted her.{/i}"
    avyanna "You can't just-"
    narrator "{{color=#43d4a8}}<WAFFLE.BAT// COMMENTARY: she can | penalties apply>{{/color}}"
    narrator "{i}Waffle spins the board one notch.{/i}"
    narrator "{{color=#808090}}{i}Penalty: lose one turn. Gain one \"reputation\" marker.{/i}{{/color}}"
    avyanna "Reputation."
    elia "{i}[[cheerful]]{/i} See? Refusal costs time and buys fear. Useful."
    avyanna "That's... horrible."
    elia "Welcome to reality. But with snacks."
    narrator "{i}Avyanna draws.{/i}"
    narrator "{{color=#808090}}{b}VOLUNTARY DISCLOSURE{/b}{{/color}}"
    narrator "{i}>{/i}"
    narrator "{{color=#808090}}{i}Answer a question. If you refuse, lose one token.{/i}{{/color}}"
    narrator "{i}Her throat tightens.{/i}"
    narrator "Answer a question. That's how it starts."
    avyanna "Who enforces it."
    narrator "{{color=#43d4a8}}<CINNAMON.EXE// RESPONSE: \"the rules\" (simulation)>{{/color}}"
    avyanna "So I can refuse."
    elia "Yes."
    elia "But don't refuse because you're scared. Refuse because you decided."
    narrator "{i}That's... different.{/i}"
    avyanna "I refuse."
    narrator "{i}Waffle removes a token from her pile with dramatic ceremony.{/i}"
    narrator "{{color=#43d4a8}}<WAFFLE.BAT// COMMENTARY: refusal recorded | NOTE: you are still alive>{{/color}}"
    avyanna "{i}[[breathing]]{/i} Still alive."
    elia "That's our brand."

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}They play.{/i}"
    narrator "{i}Elia takes wild risks, refuses anything that smells like leverage, and somehow lands on safe tiles because she treats probability like something she can bully.{/i}"
    narrator "{i}Avyanna plays cautiously at first, then learns to take one calculated risk when the risk buys her two exits later.{/i}"
    narrator "{i}She watches Elia's face light up when the rules bend.{/i}"
    narrator "Elia doesn't just break rules because she's bored. She breaks them because it proves they were never laws."
    narrator "{i}At one point, Avyanna draws \"LUCKY BREAK\" again.{/i}"
    narrator "{i}She freezes.{/i}"
    avyanna "I didn't earn-"
    elia "Stop that."
    narrator "{i}No humor. Just a command that isn't a threat.{/i}"
    elia "Don't you dare turn luck into guilt."
    avyanna "{i}[[small]]{/i} Why."
    elia "Because that's how they keep you small."
    elia "Take the break. Then use it to build something."
    narrator "{i}Avyanna swallows.{/i}"
    narrator "{i}She takes it.{/i}"
    narrator "{i}She uses the extra turn to move into a better position and-for the first time-blocks Elia's path without apologizing.{/i}"
    elia "{i}[[eyes widening, delighted]]{/i} Oh."
    elia "You read me."
    avyanna "{i}[[heart racing]]{/i} I-"
    elia "Again."
    narrator "{i}Avyanna laughs. It's thin with adrenaline, but it's real.{/i}"

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}The bonus round ends with Elia winning by doing something ridiculous that shouldn't work and does anyway.{/i}"
    elia "Chaos wins."
    narrator "{{color=#43d4a8}}<CINNAMON.EXE// CORRECTION: probability won>{{/color}}"
    narrator "{{color=#43d4a8}}<WAFFLE.BAT// ADDENDUM: chaos is a probability distribution>{{/color}}"
    elia "{i}[[pointing]]{/i} See? Even the computers agree I'm art."
    narrator "{i}Avyanna's chest aches, but not from fear.{/i}"
    narrator "I played. I lost. I'm still here. No one took food away. No one hit me."
    bubbles "Do you want to play again later."
    narrator "{i}Avyanna hesitates.{/i}"
    narrator "{i}Then decides to practice wanting in a place where wanting is safe.{/i}"
    avyanna "Yes."
    narrator "{{color=#43d4a8}}<WAFFLE.BAT// DELIGHT: YES>{{/color}}"
    narrator "{{color=#43d4a8}}<CINNAMON.EXE// NOTE: progress>{{/color}}"
    narrator "{i}Elia grins at her like she just watched a door unlock.{/i}"
    elia "Good."
    elia "We'll make you a menace yet."
    return
