## Generated from 15_ghost_net_lesson.md by convert_prose.py
## Do not edit manually — re-run converter after prose changes

label act1_15_ghost_net_lesson:
    narrator "{{color=#808090}}{b}LUMEN THIEF - TRAINING ARCHIVE (RESTRICTED):{/b}\n{i}Subject: Information Asymmetry{/i}\n{i}Instructor: Elisira Maren Lagrange{/i}\n{i}Trainee: Avyanna Lagrange{/i}\n{i}Summary: Lying is expensive. Credibility doesn't regenerate. Use it only when nothing else works.{/i}\n{i}Rule 1: Silence is not deception. It is survival.{/i}\n{i}Rule 2: Most people don't need to lie. They need to not say everything.{/i}\n{i}Rule 3: The best misdirection is a truth arranged strategically.{/i}\n{i}Addendum: If you get caught lying to Elisira, you were never going to get away with it anyway.{/i}{{/color}}"
    pause 0.3
    narrator "{i}The observation deck at 0200 is darker than it needs to be.{/i}"
    narrator "{i}Elisira chose the hour. The lighting, the angle, the exact moment Avyanna walks in and finds her already waiting-Cinnamon mentioned the scheduling request at breakfast, casual as weather.{/i}"
    narrator "{i}It is a lesson before the lesson starts.{/i}"
    narrator "She knew when I'd arrive. She knows my sleep patterns. She knows everything."
    narrator "{i}Avyanna stops in the doorway, cataloging: Elisira sits on the curved bench beneath the viewport, legs crossed, hands folded in her lap like a sculpture of patience. The stars behind her are cold and numerous and irrelevant.{/i}"
    elisira "You're on time."
    avyanna "You said 0200."
    elisira "I said \"late.\" I wanted to see if you'd interpret."
    narrator "{i}Avyanna's stomach tightens. She interpreted wrong. Or right. She can't tell.{/i}"
    avyanna "Late as in... not early?"
    elisira "Late as in: if you had come at 0145 to show initiative, I would have waited in a different room and made you find me. If you came at 0215 to test my patience, I would have left."
    narrator "{i}Avyanna's throat dries.{/i}"
    avyanna "So 0200 was the only correct answer."
    elisira "There were several correct answers. You found one."
    narrator "{i}A cooling beat: Elisira doesn't smile, but something in her posture eases a fraction. Approval, maybe. Or acknowledgment that the test is over.{/i}"
    elisira "Sit."
    narrator "{i}A mug is already on the bench beside where Avyanna is supposed to sit. Warm. Something herbal and sharp-smelling.{/i}"
    elisira "Drink."
    avyanna "Is it-"
    elisira "Not poison. I'm not Elia."
    narrator "{i}A beat. Avyanna doesn't know what to do with the gesture.{/i}"
    elisira "You'll think better if your body stops treating every room like a trap."
    narrator "{i}Avyanna takes the mug. The warmth seeps into her palms. She sips. It tastes like something growing-mint, maybe, or a plant she doesn't recognize.{/i}"

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}Avyanna sits on the opposite end of the bench. The distance feels chosen. Everything Elisira does feels chosen-her cup placed where her hands can reach it without looking, her sightline covering both entrances.{/i}"
    narrator "{i}The viewport is vast and dark. A nebula bleeds color at the edge of the frame-pinks and golds, distant and dying.{/i}"
    elisira "Do you know why I'm teaching you this?"
    avyanna "Because Elia assigned-"
    elisira "No."
    narrator "{i}The word lands like a blade on a table. Clean. Final.{/i}"
    elisira "Elia suggested. I accepted. There is a difference."
    narrator "{i}Avyanna swallows. The heat at the base of her skull stirs-not pain, just attention. Something listening.{/i}"
    avyanna "Why did you accept?"
    narrator "{i}Elisira is quiet for three breaths. Avyanna counts them. In the mine, silence meant danger. Here it means: she's deciding how much to tell you.{/i}"
    elisira "Because you're going to need this. And because most people teach it wrong."
    avyanna "Teach what wrong."
    elisira "Deception."
    narrator "{i}The word hangs between them. Avyanna waits for the lesson to start. Elisira waits for something else.{/i}"
    elisira "Tell me what you think deception is."
    narrator "{i}Avyanna's mind flickers to the mine. To supervisors who smiled before they punished. To workers who said \"I'm fine\" and collapsed an hour later. To herself, saying nothing, showing nothing, surviving.{/i}"
    avyanna "Hiding what's true."
    elisira "Incomplete. Try again."
    avyanna "Saying what isn't true."
    elisira "Also incomplete."
    narrator "{i}Avyanna's jaw tightens. She feels like she's being tested and failing, but she doesn't know the subject.{/i}"
    avyanna "I don't know what you want me to say."
    narrator "{i}Elisira's gaze sharpens-not angry, but focused. She looks like something deciding whether Avyanna is worth the effort of being dangerous at.{/i}"
    elisira "Good. That's the first honest thing you've said since you sat down."

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}The lesson begins.{/i}"
    narrator "{i}Elisira uncrosses her legs and leans forward. The casual posture drops. In its place: something precise, her hands folding once in her lap-left over right, thumbs aligned.{/i}"
    elisira "Deception is controlling what someone knows. When they know it. What they believe about what they know."
    narrator "{i}Avyanna blinks.{/i}"
    narrator "That sounds like something Vesper would say."
    elisira "Lying is the crudest form. It's also the most expensive."
    avyanna "Expensive how."
    narrator "{i}Elisira tilts her head. The starlight catches the edge of her jaw.{/i}"
    elisira "Credibility. Once you're caught lying, every true thing you say afterward is suspect. Every promise is questioned. Every alibi is investigated."
    narrator "{i}Her voice flattens, goes clinical.{/i}"
    elisira "Credibility doesn't regenerate. It's a finite resource. Most people spend it recklessly because they don't realize it exists."
    avyanna "And you don't."
    elisira "I almost never lie."
    narrator "{i}Avyanna stares. The heat behind her eyes pulses-confusion, maybe. Or warning.{/i}"
    avyanna "That's-"
    elisira "Surprising? Convenient? A lie in itself?"
    narrator "{i}Avyanna closes her mouth. She doesn't know which.{/i}"
    elisira "I'm going to teach you the difference between what I do and what people think deception is. Pay attention. I won't repeat myself."

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}Elisira stands. Moves to the viewport. Her reflection is a ghost against the stars-translucent, watching herself watch.{/i}"
    elisira "There are four modes of information control. Lying is only one of them, and it's the worst."
    narrator "{i}She holds up one finger. Her hands are scarred, Avyanna notices. Small white lines across the knuckles. Old.{/i}"
    elisira "One: Lying. Saying something false. High risk, high cost, leaves a trail. Sometimes necessary. Usually stupid."
    narrator "{i}Second finger.{/i}"
    elisira "Two: Omission. Not saying something true. Moderate risk, lower cost. Harder to prove. Most people don't even realize they've been omitted from information."
    narrator "{i}Third finger.{/i}"
    elisira "Three: Misdirection. Saying something true that leads to a false conclusion. Low risk, minimal trace. Requires the listener to do the work of deceiving themselves."
    narrator "{i}Fourth finger.{/i}"
    elisira "Four: Silence. Saying nothing. Zero trace. Zero liability. The universe defaults to ambiguity when you don't fill it."
    narrator "{i}She turns back to Avyanna. The starlight makes her eyes look ancient.{/i}"
    elisira "Most people think deception is about lying. It isn't. Lying is what you do when you've failed at the other three."

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}Avyanna's throat is dry. She swallows twice before she can speak.{/i}"
    avyanna "In the mine, we didn't... there wasn't-"
    narrator "{i}She stops. The words taste wrong. Like trying to explain color to someone who's only seen gray.{/i}"
    elisira "In the mine, you were observed constantly and punished for anything. So you learned silence."
    narrator "{i}The accuracy is violent.{/i}"
    avyanna "...Yes."
    elisira "Silence works when you have no leverage. When you're property. When the only goal is survival."
    narrator "{i}Elisira sits back down. Closer this time. She shifts the bench cushion-a small adjustment that puts Avyanna within arm's reach. The movement is practical. It doesn't feel practical.{/i}"
    elisira "You're not property anymore. Silence is still useful, but now you need the other tools."
    avyanna "Why?"
    elisira "Because people are going to ask you questions. And \"nothing\" isn't always an acceptable answer."
    narrator "{i}A beat. Elisira's eyes flick to the viewport, then back.{/i}"
    elisira "The ghost net."
    avyanna "What?"
    elisira "That's what I call it. The web of shared forms, reciprocal reporting, mutual audits. Every faction pretends they're independent, but they all feed the same logs. Ask the wrong question in Compact space, and a Writbound agent three systems away gets a ping."
    narrator "{i}Avyanna's throat tightens.{/i}"
    elisira "It's not one faction hunting you. It's the structure. The questions that propagate. And the only way through is to be so boring that no one bothers to ask."

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}Elisira pulls a small device from her pocket-a comm unit, deactivated. She sets it on the bench between them like evidence.{/i}"
    elisira "Scenario. You're at a Guild waystation. A Compact official asks where you were last cycle."
    narrator "{i}Avyanna's stomach drops. She thinks of Aurum. Of the mine. Of her file, her debt, her \"property of\" status that may or may not have been erased.{/i}"
    avyanna "I... don't tell them."
    elisira "They're an official. \"Don't tell them\" isn't an option. They have authority. What do you say?"
    narrator "{i}Avyanna's mind scrambles. The heat at the base of her skull pulses harder-frustration, maybe. Or the shard trying to help, offering nothing useful.{/i}"
    avyanna "I was... on the ship."
    elisira "True. They ask which ship."
    avyanna "The Lumen Thief."
    elisira "Registry number? Port of origin? Captain's name?"
    narrator "{i}Avyanna's heart accelerates. The walls close in. This is the Kennel again. This is being caught, being cornered, being-{/i}"
    elisira "Stop."
    narrator "{i}The word cuts through. Avyanna's breath catches.{/i}"
    elisira "You're panicking. That's the first mistake."
    avyanna "I wasn't-"
    elisira "Your hands are clenched. Your breathing changed. Your eyes went to the exit. You were panicking."
    narrator "{i}Avyanna looks down. Her hands are, in fact, clenched. She forces them open. The palms are sweating.{/i}"
    elisira "Panic is a tell. It's also unnecessary."
    narrator "{i}She pauses. Something in her expression shifts-almost imperceptibly softer.{/i}"
    elisira "If you feel your hands lock, you say \"pause.\" Not sorry. Pause. I'll stop. This isn't punishment. It's calibration."
    narrator "{i}The word lands strange. Care, delivered like a field manual.{/i}"
    elisira "Now. Watch."

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}Elisira's posture shifts. The predator relaxes into something softer-confused, a little hesitant. Her eyes widen fractionally. Her voice changes pitch.{/i}"
    narrator "{i}Elisira (as character): Oh, the registry? I'd have to check with my captain-she handles the paperwork. I just work environmental systems. You know how it is.{/i}"
    narrator "{i}The performance is flawless. Avyanna watches someone else wear Elisira's face.{/i}"
    narrator "{i}Then it drops. Elisira is herself again, sharp and still.{/i}"
    elisira "Nothing I said was false. The captain does handle paperwork. You do work environmental systems-you checked the air filters yesterday. \"You know how it is\" invites them to fill in their own assumptions."
    avyanna "But you didn't answer."
    elisira "I didn't need to. I gave them enough to make my silence unremarkable."
    narrator "{i}The heat at Avyanna's skull warms-not pain, but something like recognition. Like the shard is learning this too.{/i}"
    elisira "Misdirection isn't about what you say. It's about what they conclude."

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}Elisira runs her through scenarios for an hour.{/i}"
    narrator "{i}A Guild broker asking about cargo manifests. (Tell the truth about the legal cargo. Don't mention the compartment.){/i}"
    narrator "{i}A Compact patrol scanning for identity. (Hand over the papers. Ask about the weather. Be boring enough to forget.){/i}"
    narrator "{i}A rival crew asking about the ship's capabilities. (Understate. Let them think you're weaker than you are. They'll remember their own assumptions, not your words.){/i}"
    narrator "{i}A Writbound agent asking where Avyanna was born. (Which sector? Oh, Outer Rim. It's hard to track records out there. You know how it is.){/i}"
    narrator "You know how it is. She uses that phrase every time. It makes the listener complicit."
    narrator "{i}Avyanna fails most of the scenarios. Her voice shakes. Her pauses are too long. She reaches for lies when silence would serve. She speaks when she should wait.{/i}"
    narrator "{i}Every time, Elisira stops her.{/i}"
    elisira "Too fast. They'll know you rehearsed it."
    elisira "Too slow. Now they're curious why you're thinking."
    elisira "That's a lie. You just spent credibility. Was it worth it?"
    narrator "{i}It wasn't. It never is.{/i}"

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}By 0300, Avyanna's head aches. The heat at the base of her skull has gone from warm to throbbing, like the shard is overstimulated.{/i}"
    narrator "{i}Elisira notices. Of course she notices.{/i}"
    elisira "The shard is reactive to stress."
    avyanna "Nyx said-"
    elisira "Nyx said a lot of things. I'm saying this: it responds to you. Your body, your fear, your focus. Right now you're stressed. So it's stressed."
    narrator "{i}Avyanna's hand rises to the back of her neck without thinking. Beneath the skin, along her spine, something hums. Alive. Waiting.{/i}"
    avyanna "How do you know."
    elisira "Because I watch."
    narrator "{i}The answer is simple. It explains nothing. It explains everything.{/i}"
    elisira "Take a break. Breathe."
    narrator "{i}Avyanna breathes. The deck hums. The stars don't move.{/i}"

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}When Avyanna's heart rate steadies, Elisira speaks again. Softer now. Almost gentle, if Elisira is capable of gentle.{/i}"
    elisira "The real lesson isn't what I taught you tonight."
    avyanna "{i}[[surprised]]{/i} It isn't?"
    elisira "No. The real lesson is this: most people don't need to lie. They need to not say everything."
    narrator "{i}Avyanna frowns. The words feel familiar. Like something she almost knew.{/i}"
    elisira "In the mine, you learned that silence was survival. That's true. But silence isn't the same as deception. It's not even the same as hiding."
    narrator "{i}Elisira's voice drops. The sharpness fades. What's left is something rawer-experience, maybe. Or old pain.{/i}"
    elisira "Silence is choosing which truths to share and when. It's not lying. It's sovereignty."
    narrator "{i}Avyanna's chest tightens.{/i}"
    narrator "Sovereignty. A word that didn't exist in the Kennel."
    elisira "You don't owe anyone your whole story. You don't owe them your fear, your history, your shard, your name before this one. You get to choose what you give."
    narrator "{i}The heat behind Avyanna's eyes pulses-warmer now. Not warning. Something else. Recognition, maybe. Or gratitude.{/i}"
    avyanna "The Sparkle Doctrine says-"
    elisira "The Sparkle Doctrine is about this crew. About speaking truth to people who've earned it. It doesn't mean you owe truth to Compact officials, Guild brokers, or anyone else who hasn't bled with you."
    narrator "{i}A pause. The nebula outside continues its slow dying.{/i}"
    elisira "Elia would agree. Ask her if you don't believe me."
    narrator "{i}Avyanna won't ask. She doesn't need to. The truth of it lands like a lock clicking open.{/i}"

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}They sit in silence for a while. Comfortable, now. Or as comfortable as silence with Elisira gets.{/i}"
    narrator "{i}The ship hums. Somewhere below, Jalen is probably awake, running calculations they'll never share. Somewhere else, Rho is sleeping or pretending to. The AI citizens are monitoring, cataloging, running their endless quiet assessments.{/i}"
    narrator "{i}The ship is alive even when the crew isn't watching.{/i}"
    elisira "One more scenario. Then you sleep."
    avyanna "{i}[[wary]]{/i} Okay."
    elisira "You're at a waystation. A woman approaches you. She's well-dressed. Compact-affiliated. She asks if you're the girl they pulled from Aurum."
    narrator "{i}Avyanna's blood goes cold. The heat behind her eyes spikes-fear, warning, the shard responding to threat even when the threat is hypothetical.{/i}"
    avyanna "I..."
    elisira "She knows your face. She's seen a report. She's not guessing."
    narrator "{i}Avyanna's hands curl around the edge of the bench. She forces them flat. The metal is cold.{/i}"
    avyanna "I don't know what you're talking about."
    narrator "{i}Elisira's expression doesn't change. But something in her eyes shifts-disappointment, maybe. Or just observation.{/i}"
    elisira "That's a lie. She knows it's a lie. Now she knows you're defensive. What does she do next?"
    avyanna "She... presses harder."
    elisira "Yes. What should you have said instead?"
    narrator "{i}Avyanna's mind races. The scenarios blur together. Omission. Misdirection. Silence. Sovereignty.{/i}"
    avyanna "I... there was a situation at Aurum. A lot of workers were involved. I'm not really clear on the details."
    narrator "{i}Elisira waits. Avyanna continues, feeling her way through the dark.{/i}"
    avyanna "There was a rescue operation. The Guild was involved. I'm sure there's documentation somewhere."
    narrator "{i}She pauses. The heat pulses-not pain, but something warmer. Like encouragement.{/i}"
    avyanna "You know how it is."
    narrator "{i}Elisira almost smiles. The expression is strange on her face-foreign, quickly suppressed.{/i}"
    elisira "Better."
    avyanna "I didn't answer her question."
    elisira "You answered a question she didn't ask. That's what she'll remember. And if she presses, you've given yourself room to be confused, uncertain, helpful but unhelpful."
    narrator "{i}Avyanna exhales. The weight in her chest eases fractionally.{/i}"
    elisira "The goal isn't to win. It's to make the conversation more expensive than she wants to pay."

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}Elisira stands. The lesson is over. Avyanna can tell from the way her body changes-the teacher recedes, and something else takes its place. The shadow. The watcher. The person who sees exits and threats and never stops counting.{/i}"
    elisira "Sleep. We'll continue tomorrow."
    avyanna "What's tomorrow?"
    elisira "Watching."
    avyanna "Watching what?"
    narrator "{i}Elisira pauses at the door. The starlight catches her profile-sharp, angular, beautiful in the way that dangerous things are beautiful.{/i}"
    elisira "Me."
    narrator "{i}She leaves.{/i}"
    narrator "{i}Avyanna stays. The stars don't comfort her, but they don't judge her either. That's something.{/i}"

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}The next day, Elisira takes an incoming comm in the galley.{/i}"
    narrator "{i}Avyanna is supposed to be eating breakfast. Instead, she watches.{/i}"
    narrator "{i}Elisira has positioned herself near the recycler-a corner that looks casual but allows her to see both entrances. Her coffee cup is half-full, cooling. Her expression is neutral, pleasant, forgettable.{/i}"
    narrator "{i}The comm connects. A face appears on the small screen-middle-aged, Compact uniform collar visible, the kind of polished-bureaucratic look that means minor authority and major ego.{/i}"
    official "This is Coordinator Vance, Transitory Authority, Compact Bureau Node Clearance. We're performing a routine audit of vessels that passed through the Acheron corridor last quarter. I'm contacting every ship with transponder overlap on the cycle-47 manifest hash. Form 17-K, if you're keeping records."
    narrator "{i}Elisira's posture doesn't change. If anything, she relaxes more. Avyanna notices how controlled the relaxation is-shoulders dropping on cue, hands unclenching where he can see them.{/i}"
    elisira "{i}[[warm, slightly bored]]{/i} Of course. How can I help?"
    narrator "{i}Her voice is different. Lighter. More cooperative. A person with nothing to hide and nothing interesting to say.{/i}"
    official "Your ship-the Lumen Thief, registry 7742-KAEL-transited the lane on cycle 47. I have your transit receipt on file. Can you confirm your cargo manifest matches the hash you submitted at gate entry?"
    elisira "Oh, that was standard supplies. Med stock, fabrication polymers, some specialty tools. Vesper handles the details-she's our logistics lead. I mostly just make sure people get fed."
    narrator "{i}She laughs. It's warm and slightly self-deprecating. It's also completely false-Elisira has never laughed like that in Avyanna's presence.{/i}"
    official "{i}[[nodding, typing]]{/i} And your crew complement?"
    elisira "Seven, plus our AI systems. They're all licensed under Guild service protocols, if you need copies."
    official "AI citizens?"
    narrator "{i}A flicker of interest. Avyanna tenses. This is a trap. Compact law doesn't recognize AI citizenship-{/i}"
    elisira "{i}[[smoothly]]{/i} Sorry, shipboard slang. AI systems licensed under Guild maintenance protocols. They've got personality matrices, so we give them nicknames. Crew bonding thing. You know how it is."
    narrator "{i}The official's interest fades. Avyanna watches it happen-the way Elisira made \"AI citizens\" into an eccentricity instead of a legal challenge. Made it small. Forgettable.{/i}"
    narrator "{{color=#43d4a8}}<CINNAMON.EXE// EXTERNAL MASK: accepted | INTERNAL STATUS: citizen, not property | NOTE: we agreed to this. the shell protects the truth.>{{/color}}"
    official "I see. And your destination after Acheron?"
    elisira "Oh, we had a contract at Salvage. Labor arbitration support. It's all in the Guild files if you need verification."
    narrator "{i}The official types something. His brow furrows briefly-accessing records, probably. Avyanna's hands tighten under the table.{/i}"
    official "I'm not seeing that contract in the immediate registry."
    elisira "{i}[[unconcerned]]{/i} It might still be processing. Guild paperwork, you know. Everything takes three cycles longer than it should."
    narrator "{i}She shrugs. The official sighs-the sigh of someone who has also suffered from bureaucratic delays. A moment of shared frustration. Bonding.{/i}"
    official "I'll flag it for follow-up. Nothing urgent."
    elisira "Of course. Is there anything else?"
    official "No, that should be sufficient. Thank you for your cooperation."
    elisira "Anytime. Safe transits, Coordinator."
    narrator "{i}The comm disconnects. Elisira's face doesn't change for three full seconds-holding the mask in case of monitoring-and then it drops.{/i}"
    narrator "{i}What's left is sharp, still, predatory. The real Elisira. Avyanna's teacher.{/i}"

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}Elisira doesn't look at Avyanna. Doesn't acknowledge that she was being watched. But she speaks anyway, quiet enough that only Avyanna can hear.{/i}"
    elisira "What did you see?"
    narrator "{i}Avyanna thinks. Replays the conversation in her head.{/i}"
    avyanna "You didn't lie."
    elisira "No."
    avyanna "Everything you said was technically true."
    elisira "Yes."
    avyanna "But you arranged it so he concluded things that weren't true."
    narrator "{i}Elisira takes a sip of her cold coffee. Her face is neutral again. Patient.{/i}"
    elisira "What things?"
    avyanna "That... the AI citizens are just systems with nicknames. That the Salvage contract was routine. That you're just a cook who doesn't know much."
    narrator "{i}The last one makes Avyanna's chest tighten. The lie that wasn't a lie-Elisira as harmless, forgettable, domestic.{/i}"
    elisira "I never said I was a cook."
    avyanna "You implied-"
    elisira "I said I make sure people get fed. True. I'm the one who manages food rotation when Elia forgets to eat and Vesper gets lost in casework. I fed you your first real meal on this ship."
    narrator "{i}The memory surfaces: Avyanna in the med bay, Elisira appearing with a tray, saying nothing, leaving before thanks could be offered.{/i}"
    avyanna "That's... true."
    elisira "Everything was true. He filled in the rest himself. That's what people do."

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}Avyanna sits with that for a long moment. The galley smells like recycled coffee and Jalen's attempt at synthetic toast. Someone has scratched \"WAFFLE MAKES BETTER TOAST\" into the counter near the dispensary. It's been there for months.{/i}"
    narrator "People assume. They hear a partial truth and finish the story themselves. And they believe their own conclusions more than they'd believe mine."
    avyanna "The official will report that we're boring."
    elisira "He'll report that we're cooperative, mundane, and not worth investigating further."
    avyanna "Even though we're not."
    elisira "Being interesting is expensive. Being boring is free."
    narrator "{i}Avyanna turns that over. It sounds like something Vesper would say-or maybe something they both learned from the same source. The ship's philosophy, distilled into survival strategy.{/i}"
    avyanna "What if he'd pressed harder? About the AI citizens?"
    narrator "{i}Elisira sets down her coffee cup. The movement is precise.{/i}"
    elisira "Then I would have redirected again. Asked about his day. Mentioned transit schedules. Made myself more trouble than I was worth."
    avyanna "And if that didn't work?"
    elisira "Then I would have lied."
    narrator "{i}The word lands simply. No justification. No excuse.{/i}"
    elisira "But lying would have cost me. Now, if he ever checks again, my record is: cooperative, boring, compliant. That's valuable. That's what I protected tonight."
    narrator "{i}Avyanna nods. The heat at the base of her skull hums-approval, maybe. Or just attention.{/i}"
    narrator "{i}Elisira pauses. For a moment, her hand moves toward Avyanna's shoulder-then stops. The gesture aborts mid-motion, replaced by adjusting her own collar.{/i}"
    elisira "Lying is for when you've failed at everything else. Remember that."

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}Elisira pauses at the corridor. Not turning back fully. Just enough to prove she hasn't forgotten Avyanna exists.{/i}"
    elisira "One more thing."
    narrator "{i}Avyanna's spine goes rigid on instinct. \"One more thing\" used to mean surprise charges. Extra shifts. A quota adjustment.{/i}"
    elisira "Homework."
    avyanna "{i}[[blinking]]{/i} Homework."
    narrator "{i}Elisira slides a thin printout onto the table-station letterhead, a bland bulletin in bureaucratic font. The kind of paper that looks harmless until it kills you.{/i}"
    elisira "Circle every noun that describes a person."
    elisira "Underline every verb that implies ownership."
    elisira "Then write, in the margin: what assumption those words are trying to smuggle into your skull."
    narrator "{i}Avyanna stares at the printout.{/i}"
    avyanna "Why."
    elisira "Because you keep thinking lies are the interesting part."
    narrator "{i}She finally looks at Avyanna, eyes flat and sharp.{/i}"
    elisira "Lies are easy."
    elisira "Assumptions are infrastructure."
    elisira "If you can see the assumptions, you can predict the whole system's next move."
    narrator "{i}Avyanna's chest tightens. Not fear-focus.{/i}"
    avyanna "And then what."
    elisira "Then you write one sentence that refuses the assumption without starting a fight you can't win."
    avyanna "{i}[[quiet]]{/i} Like you did with the Compact official."
    elisira "Yes."
    narrator "{i}Elisira adjusts her collar-mask back on, already leaving.{/i}"
    elisira "Bring it to me tomorrow."
    elisira "If your margin notes are good, I'll give you harder paper."
    narrator "{i}It's almost a joke.{/i}"
    narrator "{i}It's almost encouragement.{/i}"
    narrator "{i}It lands anyway.{/i}"
    narrator "{i}Later, in her bunk, Avyanna stares at the ceiling and lets the lesson settle.{/i}"
    narrator "Silence is sovereignty. Truth can be arranged. Boring is free."
    narrator "{i}The heat along her spine settles into a low, steady hum-not words, but warmth. Agreement, maybe. Or just presence.{/i}"
    narrator "{i}She thinks of the mine. The constant surveillance. The way speaking meant danger and silence meant survival. She'd thought she knew about hiding.{/i}"
    narrator "I didn't know anything. I knew how to disappear. Elisira knows how to be seen and still keep everything that matters."
    narrator "{i}There's a difference. A huge one.{/i}"
    narrator "{i}Avyanna rolls onto her side. The ship's hum is steady. Someone-Rho, probably-is moving in the corridor, boots heavy and unhurried.{/i}"
    narrator "I don't owe anyone my whole story."
    narrator "{i}The thought feels like a door opening. Small, but real.{/i}"
    narrator "{i}For years, every truth about herself was extracted. Forced. Demanded by forms and supervisors and the endless ledger of her debt. Her history belonged to Aurum. Her future belonged to the balance.{/i}"
    narrator "Here, I get to choose."
    narrator "{i}The warmth at her skull spreads-down her spine, into her chest. Not pain. Not warning. Something else.{/i}"
    narrator "I get to choose what I give."
    narrator "{i}She closes her eyes. For the first time in weeks, sleep comes easily.{/i}"

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}The next morning, Vesper catches her in the commons. Her datapad is in hand. Her expression is neutral, but something in her eyes is sharper than usual.{/i}"
    vesper "Elisira says you're learning."
    avyanna "{i}[[carefully]]{/i} She said that?"
    vesper "She said \"not hopeless.\" For Elisira, that's high praise."
    narrator "{i}Avyanna doesn't smile, but something in her chest loosens.{/i}"
    vesper "How do you feel?"
    narrator "{i}The question is genuine. Vesper always asks genuine questions, even when the answers are inconvenient.{/i}"
    narrator "{i}Avyanna considers. How does she feel?{/i}"
    narrator "Tired. Scared. Slightly less terrified than yesterday."
    narrator "{i}But that's not what she says.{/i}"
    avyanna "I feel like I understand something I didn't before."
    vesper "What's that?"
    narrator "{i}Avyanna meets her eyes. The heat hums. The lesson settles into her bones.{/i}"
    avyanna "That silence isn't weakness. It's a choice."
    narrator "{i}Vesper's expression shifts-just slightly. Something like pride. Or recognition.{/i}"
    vesper "Good."
    narrator "{i}She turns to leave. Pauses at the door.{/i}"
    vesper "For what it's worth: Elisira doesn't teach people she doesn't believe in. If she's spending time on you, it means something."
    narrator "{i}Then she's gone.{/i}"

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}Avyanna sits in the commons alone, surrounded by the ship's quiet breathing.{/i}"
    narrator "{i}On the message board, someone has added a new note: {i}Nav check tomorrow, 0800. Jalen will be grumpy. Bring offerings (coffee).{/i}"
    narrator "{i}Below it: {i}WHAT COUNTS AS COFFEE ON THIS SHIP IS AN OPEN PHILOSOPHICAL QUESTION - E{/i}"
    narrator "{i}Below that, in smaller handwriting: {i}the recycler's attempt is a war crime - R{/i}"
    narrator "{i}Avyanna reads them. Rereads them. Small complaints. Small life. The ship continuing its existence through bickering and maintenance and people noticing what matters.{/i}"
    narrator "{i}She gets up. Goes to the galley. Makes coffee-or the closest thing the dispensary can manage.{/i}"
    narrator "{i}She doesn't drink it. She leaves it outside Jalen's door with a note: {i}For 0800. A. L.{/i}"
    narrator "{i}It's a small thing. It's a choice.{/i}"
    narrator "{i}The heat at her skull warms. Not approval-something simpler. Just: awareness. Just: the shard noticing that she's changing.{/i}"
    narrator "{i}She walks back to her bunk, boots quiet on the deck.{/i}"
    narrator "I'm learning."
    narrator "{i}The thought doesn't scare her anymore.{/i}"

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{{color=#43d4a8}}<BUBBLES// OBSERVATION: trainee left offering outside pilot's quarters | INFERENCE: bonding behavior | CONFIDENCE: 0.72 | NOTE: she's learning which debts are real.>{{/color}}"

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}End Chapter 15{/i}"
    return
