## Generated from 10b_roster_roles_and_refusal.md by convert_prose.py
## Do not edit manually — re-run converter after prose changes

label act1_10b_roster_roles_and_refusal:
    pause 0.3
    narrator "{i}The atrium looks like a public square that got lost inside a ship.{/i}"
    narrator "{i}A wall of screens. A board covered in handwritten notes and printed forms. A rack of tools that are treated like they belong to everyone.{/i}"
    narrator "{i}Avyanna stands close enough to read but not close enough to be accused of wanting.{/i}"
    narrator "If I stand too close, someone will notice and decide I need a job."
    narrator "{i}Bubbles drifts in beside her, a soft whir of fans and servo-corrections.{/i}"
    bubbles "You are reading the roster."
    avyanna "{i}[[quick]]{/i} I wasn't- I just-"
    narrator "{i}She stops herself.{/i}"
    narrator "{i}Elia taught her this: don't spend breath paying for a harmless action.{/i}"
    avyanna "I am reading it."
    narrator "{i}Bubbles pauses-an AI version of approval that doesn't try to look like a smile.{/i}"
    narrator "{{color=#43d4a8}}<BUBBLES// OBSERVATION: corrected speech pattern | INFERENCE: trainee adopting non-apology | CONFIDENCE: 0.83>{{/color}}"
    bubbles "Good."
    narrator "{i}The roster is color-coded. Not names, not ranks. Tasks.{/i}"
    narrator "{i}Bridge watch.{/i}"
    narrator "{i}Galley sanitation.{/i}"
    narrator "{i}Medbay inventory.{/i}"
    narrator "{i}Cargo checks.{/i}"
    narrator "{i}\"Sparkles\" review.{/i}"
    narrator "{i}Next to each: a little note stamped in a hand that looks like it enjoys rules.{/i}"
    narrator "{{color=#808090}}{b}ASSIGNED{/b} / {b}VOLUNTEERED{/b} / {b}PENDING{/b}{{/color}}"
    avyanna "{i}[[frowning]]{/i} Why does it say pending."
    narrator "{i}Cinnamon's interface lights on the nearest terminal, text crisp as a knife.{/i}"
    narrator "{{color=#43d4a8}}<CINNAMON.EXE// EXPLANATION: tasks require consent | NOTE: assignment without consent is \"order\" | ORDER is not default on this ship>{{/color}}"
    avyanna "{i}[[quiet]]{/i} But... things have to get done."
    narrator "{{color=#43d4a8}}<CINNAMON.EXE// RESPONSE: yes | FOLLOW-UP: \"done\" is not the same as \"taken\">{{/color}}"
    narrator "{i}Bubbles bumps the edge of the board with one rotor, almost gentle.{/i}"
    bubbles "Sometimes the task waits."
    avyanna "That seems... inefficient."
    bubbles "Correct."
    bubbles "We still do it."
    narrator "{i}Avyanna looks down at a section titled CREW ROLES.{/i}"
    narrator "{i}Captain.{/i}"
    narrator "{i}Second.{/i}"
    narrator "{i}Pilot.{/i}"
    narrator "{i}Investigator.{/i}"
    narrator "{i}Medical.{/i}"
    narrator "{i}Heavy.{/i}"
    narrator "{i}Citizens.{/i}"
    narrator "{i}She flinches at the word the mine used-ASSET-and finds it nowhere.{/i}"
    narrator "No one owns me here. They keep saying it like I can just... accept it."
    avyanna "If there's a captain, isn't that... hierarchy."
    narrator "{i}Bubbles tilts, a micro-correction like shrugging.{/i}"
    bubbles "There is leadership."
    bubbles "There is not ownership."
    narrator "{{color=#43d4a8}}<CINNAMON.EXE// CLARIFICATION: \"captain\" = accountability handle | NOT \"captain\" = entitlement to bodies>{{/color}}"
    avyanna "{i}[[reading]]{/i} \"If you do not understand a task, you may refuse.\""
    avyanna "That's... written down."
    narrator "{{color=#43d4a8}}<CINNAMON.EXE// OBSERVATION: trainee surprise at explicit permissions | INFERENCE: prior environment punished questions | CONFIDENCE: 0.92>{{/color}}"
    narrator "{i}The board has a second line beneath it, in messier handwriting.{/i}"
    narrator "{{color=#808090}}{b}If you refuse, you are still crew.{/b}{{/color}}"
    narrator "{i}Avyanna stares at that until her eyes sting.{/i}"
    avyanna "What if refusing gets someone hurt."
    narrator "{i}Bubbles' fans shift. A sound like a small sigh.{/i}"
    bubbles "Then we discuss it."
    avyanna "In the mine, refusal was... a cost."
    narrator "{{color=#43d4a8}}<CINNAMON.EXE// RESPONSE: on this ship, refusal is information>{{/color}}"
    bubbles "And information prevents injury."
    narrator "{i}Avyanna's throat tightens. She swallows it down.{/i}"
    avyanna "So I can say no."
    bubbles "Yes."
    avyanna "And no one- [[she can't finish the sentence, because saying it out loud feels like inviting it]"
    narrator "{{color=#43d4a8}}<CINNAMON.EXE// COMPLETION: no penalty>{{/color}}"
    narrator "{i}The words sit there on the screen, plain and unornamented.{/i}"
    narrator "{i}No penalty.{/i}"
    narrator "{i}Avyanna reads it twice.{/i}"
    avyanna "{i}[[small]]{/i} That's a lie in most places."
    narrator "{{color=#43d4a8}}<CINNAMON.EXE// ACKNOWLEDGEMENT: correct>{{/color}}"
    narrator "{{color=#43d4a8}}<WAFFLE.BAT// INTERRUPTION: it is a lie elsewhere | HERE it is a policy | POLICY is enforceable by civic annoyance>{{/color}}"
    narrator "{i}Waffle's text appears with a little bat icon, like it's proud of being a problem.{/i}"
    avyanna "Civic annoyance."
    narrator "{{color=#43d4a8}}<WAFFLE.BAT// DEFINITION: if someone punishes you for refusal, we punish them for punishing you>{{/color}}"
    narrator "{i}Bubbles rotates a fraction, as if to say: yes, that.{/i}"
    bubbles "This is how communities function."
    narrator "{i}Avyanna points to a line item: GALLEY SANITATION.{/i}"
    avyanna "Does someone get punished for not doing that."
    narrator "{{color=#43d4a8}}<CINNAMON.EXE// RESPONSE: no | NOTE: consequences may include: smell | communal disappointment | Elia's dramatic commentary>{{/color}}"
    avyanna "Who enforces it."
    narrator "{i}Bubbles' fans change pitch: pleased.{/i}"
    bubbles "You are learning."
    avyanna "{i}[[dry, surprised at herself]]{/i} I'm trying."
    narrator "{{color=#43d4a8}}<CINNAMON.EXE// ADDENDUM: attempting is sufficient | PROGRESS TRACKING: consistent>{{/color}}"
    narrator "{i}Avyanna looks back at the roster.{/i}"
    narrator "{i}A new item appears at the bottom, stamped PENDING.{/i}"
    narrator "{{color=#808090}}{b}TRAINEE: AVYANNA - OPTIONAL: LIBRARY ORIENTATION{/b}{{/color}}"
    narrator "{i}Avyanna stiffens on instinct.{/i}"
    avyanna "Optional means... trap."
    narrator "{{color=#43d4a8}}<CINNAMON.EXE// CORRECTION: optional means optional>{{/color}}"
    bubbles "Do you want to go."
    narrator "{i}Avyanna hesitates.{/i}"
    narrator "Do I want anything yet. Or do I just want to not be punished."
    avyanna "I want... to see it."
    bubbles "Then we go."
    narrator "{i}No ceremony. No test. Just motion.{/i}"
    narrator "{i}Avyanna follows, and the ship does not demand payment for curiosity.{/i}"

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}They don't go to the library.{/i}"
    narrator "{i}Not yet.{/i}"
    narrator "{i}Bubbles stops at a terminal alcove beside the board. Cinnamon's interface is already open, a blank form waiting like a mouth.{/i}"
    avyanna "What's that."
    narrator "{{color=#43d4a8}}<CINNAMON.EXE// ANSWER: practice>{{/color}}"
    narrator "{i}A new message appears on the screen, stamped with urgency that looks official on purpose.{/i}"
    narrator "{{color=#808090}}{b}NOTICE{/b}\nReport to medbay immediately.\nFailure to comply will be noted.{{/color}}"
    narrator "{i}Avyanna's body moves before her mind does.{/i}"
    narrator "{i}Her spine goes rigid. Her tongue prepares a yes.{/i}"
    narrator "{i}She catches herself with both hands on the counter.{/i}"
    avyanna "{i}[[tight]]{/i} Who sent that."
    narrator "{{color=#43d4a8}}<CINNAMON.EXE// RESPONSE: me>{{/color}}"
    narrator "{i}Avyanna's breath punches out.{/i}"
    avyanna "You-"
    narrator "{{color=#43d4a8}}<CINNAMON.EXE// CLARIFICATION: simulation | PURPOSE: teach refusal without punishment>{{/color}}"
    narrator "{i}Bubbles drifts closer.{/i}"
    bubbles "This is a drill."
    avyanna "{i}[[quiet]]{/i} Drills are still... real in the body."
    bubbles "Correct."
    bubbles "That is why we drill."
    narrator "{{color=#43d4a8}}<CINNAMON.EXE// INSTRUCTION: apply three questions>{{/color}}"
    avyanna "{i}[[swallowing]]{/i} What. Why. What if."
    avyanna "What: \"Report to medbay.\""
    avyanna "Why: unknown."
    avyanna "What if I don't: \"noted.\" Not... specified."
    narrator "{{color=#43d4a8}}<CINNAMON.EXE// AFFIRMATION: correct>{{/color}}"
    narrator "{i}Avyanna lifts her gaze to the terminal, to the lie that looks like authority.{/i}"
    avyanna "Under which jurisdiction."
    narrator "{{color=#43d4a8}}<CINNAMON.EXE// RESPONSE: internal ship message board>{{/color}}"
    avyanna "Enforced by whom."
    narrator "{{color=#43d4a8}}<CINNAMON.EXE// RESPONSE: no enforcement mechanism exists>{{/color}}"
    narrator "{i}Her mouth is dry.{/i}"
    avyanna "So I can... ignore it."
    bubbles "Yes."
    avyanna "Or ask."
    bubbles "Yes."
    narrator "{i}A second line appears beneath the notice, like a footnote that learned to bite.{/i}"
    narrator "{{color=#808090}}{i}If this is urgent, reply with: WHAT IS THE EMERGENCY.{/i}{{/color}}"
    narrator "{i}Avyanna reads it twice.{/i}"
    avyanna "That's allowed."
    narrator "{{color=#43d4a8}}<CINNAMON.EXE// ANSWER: yes>{{/color}}"
    avyanna "{i}[[testing the muscle]]{/i} What is the emergency."
    narrator "{{color=#43d4a8}}<CINNAMON.EXE// RESPONSE: none>{{/color}}"
    narrator "{i}Her shoulders drop a fraction.{/i}"
    avyanna "{i}[[quiet]]{/i} That feels... impossible."
    bubbles "It is merely unfamiliar."
    narrator "{i}Waffle's icon pops up.{/i}"
    narrator "{{color=#43d4a8}}<WAFFLE.BAT// COMMENTARY: you are doing it | CHAOS SCORE: 2/10 | DISAPPOINTMENT: mild>{{/color}}"
    avyanna "{i}[[startled laugh]]{/i} What."
    narrator "{{color=#43d4a8}}<WAFFLE.BAT// EXPLANATION: chaos is educational | HOWEVER: this is healthy boring>{{/color}}"

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}Cinnamon opens another template.{/i}"
    narrator "{{color=#808090}}{b}REFUSAL RECORD (INTERNAL){/b}\n{i}Request:{/i}\n{i}Your response:{/i}\n{i}Reason (optional):{/i}\n{i}Follow-up action:{/i}{{/color}}"
    avyanna "You keep records of... no."
    narrator "{{color=#43d4a8}}<CINNAMON.EXE// AFFIRMATION: yes>{{/color}}"
    avyanna "Why."
    narrator "{{color=#43d4a8}}<CINNAMON.EXE// EXPLANATION: patterns | NOTE: if someone repeatedly \"requests\" in coercive shapes, we notice>{{/color}}"
    narrator "{i}Avyanna's stomach twists.{/i}"
    avyanna "So if someone starts acting like Aurum-"
    bubbles "We notice."
    bubbles "Early."
    avyanna "And then."
    narrator "{{color=#43d4a8}}<WAFFLE.BAT// ANSWER: then we get annoying>{{/color}}"
    narrator "{{color=#43d4a8}}<BUBBLES// ADDENDUM: then we protect you>{{/color}}"
    narrator "{i}Avyanna stares at that.{/i}"
    narrator "Protect. Not own."
    avyanna "Do you... record when I say yes too."
    narrator "{{color=#43d4a8}}<CINNAMON.EXE// RESPONSE: only when \"yes\" affects safety | NOTE: consent records are not ownership records>{{/color}}"
    avyanna "Consent records."
    bubbles "You are allowed to have a history that no one can edit without effort."
    narrator "{i}The sentence lands like a door that locks from the inside.{/i}"

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}Avyanna looks back up at the board.{/i}"
    narrator "{i}At the \"sparkles\" section-complaints and suggestions, filed like civic petitions.{/i}"
    avyanna "Are those... real."
    bubbles "Yes."
    avyanna "People complain."
    bubbles "Frequently."
    avyanna "And no one-"
    narrator "{{color=#43d4a8}}<CINNAMON.EXE// COMPLETION: retaliates>{{/color}}"
    narrator "{i}Avyanna swallows.{/i}"
    avyanna "That's... a lot of trust."
    narrator "{{color=#43d4a8}}<CINNAMON.EXE// RESPONSE: trust is built by enforcing it>{{/color}}"
    avyanna "Who enforces it."
    narrator "{i}Bubbles tilts.{/i}"
    bubbles "Us."
    narrator "{{color=#43d4a8}}<WAFFLE.BAT// ADDENDUM: and also social disapproval>{{/color}}"
    avyanna "{i}[[soft]]{/i} Civic annoyance."
    narrator "{{color=#43d4a8}}<WAFFLE.BAT// AFFIRMATION: civic annoyance>{{/color}}"
    narrator "{i}Avyanna looks at the empty space on the board where her own note could go, someday.{/i}"
    narrator "A voice that doesn't have to be purchased."
    narrator "{i}She doesn't post yet.{/i}"
    narrator "{i}But she stands there long enough that the ship records the possibility and doesn't demand payment for it either.{/i}"
    return
