## Generated from 09b_rowan_finds_vesper.md by convert_prose.py
## Do not edit manually — re-run converter after prose changes

label act1_09b_rowan_finds_vesper:
    narrator "{{color=#808090}}{b}LUMEN THIEF - PRIVATE NOTE (VESPER):{/b}\n{i}Topic: where the name came from{/i}\n{i}Reminder: love can be a discipline{/i}{{/color}}"
    pause 0.3
    narrator "{i}The rook sits on Vesper's desk like it's waiting for a verdict.{/i}"
    narrator "{i}Dark wood. Worn edges. The kind of object that looks small until you realize someone carried it for years.{/i}"
    narrator "{i}Avyanna notices it because she notices everything that might be a rule.{/i}"
    avyanna "{i}[[quiet]]{/i} What's that."
    narrator "{i}Vesper doesn't look up from the identity paperwork.{/i}"
    vesper "A rook."
    avyanna "I know. Why."
    narrator "{i}Vesper's pen stops.{/i}"
    narrator "{i}A breath. Controlled. Like she's deciding whether this answer is safe to give a sixteen-year-old.{/i}"
    vesper "It was a gift."
    narrator "{i}Avyanna waits. The ship taught her that waiting isn't always punishment.{/i}"
    vesper "Rowan gave it to me."
    narrator "{i}The name lands with weight. Not because Avyanna knows Rowan, but because Vesper's voice shifts when she says it-fractionally older, fractionally more careful.{/i}"
    narrator "Rowan."
    narrator "{i}Vesper's thumb brushes the rook like it's a scar you can touch without bleeding.{/i}"

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}The station's arbitration hall smells like paper and fear.{/i}"
    narrator "{i}Not the clean fear of violence.{/i}"
    narrator "{i}The slow fear of being decided about by strangers.{/i}"
    narrator "{i}Vesper stands behind a broker in a suit that costs more than her childhood did.{/i}"
    narrator "{i}She is twelve and already good at being invisible when it serves someone else.{/i}"
    narrator "{i}The broker is talking like he's telling the truth. He isn't.{/i}"
    narrator "{i}Vesper can feel the lie in the cadence-where he speeds up, where he slows down, where he uses a word that sounds neutral but isn't.{/i}"
    broker "...standard withholding. Standard jurisdiction. Standard-"
    narrator "{i}\"Standard\" is a spell. Vesper hears it like one.{/i}"
    narrator "{i}Across the hall, a woman watches.{/i}"
    narrator "{i}Older. Not old. The kind of older that makes rooms rearrange themselves so she can pass through.{/i}"
    narrator "{i}She isn't wearing a badge.{/i}"
    narrator "{i}She doesn't need one.{/i}"
    narrator "{i}She has someone else's confidence, worn like a coat.{/i}"
    narrator "{i}Rowan Rook.{/i}"
    narrator "{i}Vesper doesn't know her name yet.{/i}"
    narrator "{i}She just knows the woman is looking at the same lie and not flinching.{/i}"
    narrator "{i}The broker's opponent-a labor representative with cracked nails-starts to fold.{/i}"
    labor_rep "If we just adjust the rate a little, maybe-"
    narrator "{i}The broker smiles. Gentle. Predatory.{/i}"
    narrator "{i}Vesper's stomach tightens.{/i}"
    narrator "If they adjust, the math still kills them. It just kills them slower."
    narrator "{i}Vesper leans in and whispers to the broker-quiet enough no one can accuse her of speaking out of turn.{/i}"
    vesper "If you concede now, they'll raise the compliance fee in two weeks. They always do. It's in the supplemental schedule."
    narrator "{i}The broker's jaw tightens. He ignores her.{/i}"
    narrator "{i}Because she's the assistant.{/i}"
    narrator "{i}Because she's a tool.{/i}"
    narrator "{i}Because tools don't get to have opinions.{/i}"
    narrator "{i}Rowan Rook stands up.{/i}"
    narrator "{i}Not dramatic.{/i}"
    narrator "{i}Just... standing, and suddenly the air has a spine.{/i}"
    rowan "Objection."
    narrator "{i}A murmur ripples through the hall. The arbitrator blinks like he forgot people could interrupt procedure.{/i}"
    arbitrator "On what basis."
    rowan "On the basis that you are being asked to bless a murder with paperwork."
    narrator "{i}Silence.{/i}"
    narrator "{i}The broker turns, incredulous.{/i}"
    broker "Who are you."
    rowan "{i}[[mild]]{/i} Someone who reads."
    narrator "{i}Rowan's gaze flicks to Vesper for half a second.{/i}"
    narrator "{i}Not pity.{/i}"
    narrator "{i}Recognition.{/i}"
    narrator "{i}Rowan speaks like she's talking to the whole room, but the words land like they're aimed at one girl behind a liar.{/i}"
    rowan "\"Standard\" is a story people tell so they don't have to admit they are choosing harm."
    rowan "Show the full schedule. Not the summary. Not the highlight reel. The full ledger."
    narrator "{i}The arbitrator hesitates.{/i}"
    narrator "{i}Rowan waits. Patient. Not begging. Not threatening.{/i}"
    narrator "{i}Just making the truth heavy enough that refusing it would require effort.{/i}"
    narrator "{i}The labor representative lifts their chin.{/i}"
    labor_rep "We have it."
    narrator "{i}They slide a document forward. Paper. Physical. Court-proof.{/i}"
    narrator "{i}The broker's smile cracks.{/i}"
    narrator "{i}Rowan's mouth twitches like she's pleased and annoyed at once.{/i}"

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}After, the broker storms out.{/i}"
    narrator "{i}Vesper follows automatically, still in assistant posture, still trained to chase whoever pays her oxygen.{/i}"
    narrator "{i}Rowan steps into her path in the corridor.{/i}"
    rowan "You saw it."
    narrator "{i}Vesper freezes.{/i}"
    narrator "{i}No one has ever asked her if she \"saw\" something like it mattered.{/i}"
    vesper "I did."
    rowan "You didn't speak."
    vesper "I'm not allowed to."
    rowan "That's an excuse."
    narrator "{i}The words should feel like a slap.{/i}"
    narrator "{i}They don't.{/i}"
    narrator "{i}They feel like a door unlocking.{/i}"
    rowan "You want to be useful."
    vesper "Yes."
    rowan "Then be honest about your constraints."
    rowan "If you can't speak, you find a way to make the truth speak without you."
    narrator "{i}Rowan reaches into her pocket and pulls out a small carved rook.{/i}"
    narrator "{i}Sets it on the corridor rail between them.{/i}"
    rowan "Do you know what this is."
    vesper "A chess piece."
    rowan "It's an exit."
    narrator "{i}Vesper frowns.{/i}"
    rowan "The rook moves straight."
    rowan "No diagonals. No flourish. No pleading."
    rowan "When you want something in a room full of liars, you move straight toward it."
    rowan "And you accept the cost of being seen."
    narrator "{i}Vesper's throat tightens.{/i}"
    vesper "Why are you telling me this."
    rowan "Because you're already doing the first part."
    rowan "You're seeing."
    rowan "I'm offering you the second part."
    narrator "{i}Rowan's hand hovers over the rook, then pulls back.{/i}"
    narrator "{i}Not taking. Not insisting. Offering.{/i}"
    rowan "You can refuse."
    rowan "No penalty."
    narrator "{i}Vesper stares at the rook.{/i}"
    narrator "Refusal without punishment. That's not a thing."
    narrator "{i}Rowan waits anyway, like she means it.{/i}"
    vesper "{i}[[quiet]]{/i} What do you want from me."
    rowan "Nothing you can't give freely."
    rowan "I want you to stop letting people use your competence like it belongs to them."
    narrator "{i}Vesper's chest hurts with something sharp and unfamiliar.{/i}"
    vesper "I don't have a place."
    rowan "Then take one."
    rowan "Or come with me and we'll build one."
    narrator "{i}Vesper reaches for the rook.{/i}"
    narrator "{i}Her fingers tremble once.{/i}"
    narrator "{i}Then steady.{/i}"
    vesper "Okay."
    narrator "{i}Rowan nods like she expected it, but still respects that it was chosen.{/i}"
    rowan "Good."
    rowan "First lesson, then."
    rowan "Love can be a discipline."
    rowan "Not a hunger."
    narrator "{i}Vesper doesn't understand yet.{/i}"
    narrator "{i}But she keeps the rook.{/i}"
    narrator "{i}And for the next six years, Rowan will teach her what that means-raising her without owning her, protecting her without possession, loving her without crossing lines that can't be uncrossed.{/i}"
    narrator "{i}When Vesper turns eighteen, Rowan will look at her across a table and say: \"Now you get to choose.\"{/i}"
    narrator "{i}And Vesper will choose her. Freely. Equally. Without the weight of debt or dependency pressing down on the answer.{/i}"
    narrator "{i}Three years after that, Rowan will die protecting her one last time. And Vesper will carry the rook-and the lesson-forward into every negotiation, every contract, every moment when power and care threaten to collapse into the same terrible thing.{/i}"

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}Back in the present, Vesper's pen moves again.{/i}"
    narrator "{i}The rook sits under her palm like a held line.{/i}"
    avyanna "{i}[[careful]]{/i} Do you miss her."
    narrator "{i}Vesper's throat works.{/i}"
    vesper "Yes."
    narrator "{i}A beat.{/i}"
    vesper "And I don't use that to make you smaller."
    narrator "{i}Avyanna swallows.{/i}"
    avyanna "Okay."
    narrator "{i}Vesper returns to the paperwork.{/i}"
    narrator "{i}But she leaves the rook where Avyanna can see it.{/i}"
    ## Progression state
    $ relationship_manager.change_affinity("vesper", 2)
    return
