## Generated from 13_shipboard_physics.md by convert_prose.py
## Do not edit manually — re-run converter after prose changes

label act1_13_shipboard_physics:
    narrator "{{color=#808090}}{b}LUMEN THIEF - TRAINING PROTOCOL (AMENDED):{/b}\n{i}Subject: Shipboard Physics{/i}\n{i}Summary: Gravity is honest. So are we.{/i}\n{i}Rule 1: Learn how to fall without breaking.{/i}\n{i}Rule 2: Learn how to prove what happened.{/i}\n{i}Rule 3: Learn the difference between power and strain.{/i}\n{i}Addendum: Floors first. Peaks later. If ever.{/i}{{/color}}"
    pause 0.3
    narrator "{i}The cargo bay is the ship's largest lie.{/i}"
    narrator "{i}It looks like a place for crates and contraband and emergency repairs.{/i}"
    narrator "{i}It is also where you teach someone how to survive being thrown to the floor.{/i}"
    narrator "{i}The deck plating is cold through Avyanna's socks. The air tastes faintly of polymer and recycled coffee. A vibration runs up her shins with each pulse of the engines-a steady reminder that the ship is moving, that motion is being maintained by people she now has names for.{/i}"
    narrator "This is still a workplace."
    narrator "Different rules. Elia said that. Different place."
    narrator "{i}Elia is already there, barefoot, hair tied back like it's about to commit a crime. No blade in her hands. No armor. Just a woman built out of decisions.{/i}"
    elia "{i}[[nodding once]]{/i} Good. You showed up."
    narrator "{i}Avyanna's spine tries to lock, the old reflex-attendance as survival. She forces a slow breath instead. In. Out. Count four. Count the exits.{/i}"
    narrator "{i}Cargo bay door. Corridor. Maintenance ladder.{/i}"
    narrator "{i}Elia watches her eyes move.{/i}"
    elia "Don't stop doing that. Just don't let it freeze you."
    avyanna "{i}[[automatic, too formal]]{/i} Yes-"
    elia "{i}[[flat]]{/i} No \"yes.\" Not here. If you don't understand, you say so."
    narrator "{i}Elia lifts a hand, palm up-stop signal, not threat.{/i}"
    narrator "{i}Avyanna's mouth closes. The automatic agreement dies before it escapes.{/i}"
    elia "That. Right there. That's the reflex we're breaking."
    avyanna "{i}[[careful]]{/i} I was agreeing with you."
    elia "Were you? Or were you just saying what you think keeps you safe?"
    narrator "{i}The question hits like cold water.{/i}"
    narrator "{i}Avyanna doesn't answer. Can't answer. Because Elia's right.{/i}"
    elia "At the mine, \"yes\" meant survival. Here, \"yes\" when you mean \"I don't know\" gets people killed."
    narrator "{i}Elia sits on the edge of the console, making herself lower, less looming.{/i}"
    elia "So we're going to practice. Every time I give you an instruction, you're going to do three things before you move."
    narrator "{i}She holds up fingers as she counts.{/i}"
    elia "One. State the assumption."
    elia "Two. Ask if the assumption is true."
    elia "Three. If you're still not sure, say \"I don't understand.\""
    avyanna "{i}[[quiet]]{/i} That's going to take forever."
    elia "Good. Fast obedience is how they trained you. Slow thinking is how you survive."
    narrator "{i}She gestures at the console.{/i}"
    elia "Let's start. I'm going to tell you to check the reactor pressure. What's your assumption?"
    avyanna "{i}[[hesitant]]{/i} That... the reactor pressure needs checking?"
    elia "Why do you assume that?"
    avyanna "Because you told me to."
    elia "{i}[[grin]]{/i} And if I'm wrong? If I'm tired, or distracted, or testing you?"
    narrator "{i}Avyanna's hands tighten.{/i}"
    avyanna "Then I'd check something that doesn't need checking."
    elia "Exactly. So what do you ask?"
    avyanna "{i}[[slow, trying it out]]{/i} Why are we checking reactor pressure?"
    elia "{i}[[approving]]{/i} Good. And I'd answer: because Jalen flagged an anomaly, or because it's on the maintenance schedule, or because I want you to learn where the readout is."
    elia "Now you know. Now \"yes\" means something."
    narrator "{i}Avyanna processes that.{/i}"
    avyanna "But what if there's no time? What if it's an emergency?"
    elia "Then I don't give you a choice. I say \"Avyanna, do this, now, I'll explain later.\""
    narrator "{i}She leans forward.{/i}"
    elia "And you'll know it's real because I never pull that card unless it's life or death. Because I don't train you to obey blindly and then suddenly demand critical thinking when the ship's on fire."
    avyanna "{i}[[very quiet]]{/i} The overseers did that."
    elia "I know. That's why we're doing this."
    narrator "{i}She stands, offers a hand up.{/i}"
    elia "Three questions. Every instruction. Until it's reflex."
    avyanna "{i}[[taking the hand]]{/i} What. Why. What if."
    elia "{i}[[sharp grin]]{/i} Fast learner. Let's break some more habits."
    narrator "{i}Elia lifts a hand, palm up-stop signal, not threat.{/i}"
    elia "Three questions."
    narrator "{i}She holds up fingers as she counts, like she's teaching a child and a soldier at the same time.{/i}"
    elia "What are we doing."
    elia "Why are we doing it."
    elia "What happens if you do it wrong."
    narrator "{i}Avyanna stares.{/i}"
    avyanna "{i}[[automatic]]{/i} So I-"
    elia "Not \"so I can obey.\" So you can decide."
    narrator "{i}The sentence lands hard. Decision as a thing Avyanna is allowed to have.{/i}"
    elia "If you can't answer those three, you don't move. You ask. You stall. You buy time."
    avyanna "{i}[[quiet]]{/i} In the Kennel, stalling meant-"
    elia "I know."
    narrator "{i}Elia's gaze is steady in the way a bulkhead is steady. No pity. No softness performance. Just a rule.{/i}"
    elia "Here, stalling is how you stay alive."
    avyanna "{i}[[swallows]]{/i} What if you tell me to do something and I don't understand."
    elia "Then you say: \"Explain.\""
    avyanna "And if you get angry."
    elia "Then you'll have learned something about me that needs correcting."
    narrator "{i}Cooling beat: Elia's mouth quirks, almost a smile.{/i}"
    elia "I'm not allergic to being wrong, Avyanna. I'm allergic to rot."
    elia "Confusion you say out loud is fixable. Silence isn't."
    narrator "{i}Avyanna's pulse is loud in her ears.{/i}"
    narrator "Ask. Out loud. Like it won't cost me skin."
    elia "Try it."
    avyanna "{i}[[a breath]]{/i} What are we doing."
    elia "Teaching you how to hit the floor without letting it collect you."
    avyanna "Why."
    elia "Because corridors throw people. Bullets throw people. Panic throws people. You don't get to pick when."
    avyanna "What happens if I do it wrong."
    elia "You get hurt."
    elia "Or you die."
    elia "So we learn it on purpose. In here. With mats. With me watching. With you allowed to stop."
    narrator "{i}Avyanna nods once. It isn't agreement. It's comprehension. That's different.{/i}"
    narrator "{i}Silence, the kind Avyanna used to live inside. Elia waits it out like it's weather.{/i}"
    avyanna "{i}[[quiet]]{/i} I understand."
    elia "We'll see."

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}Elia walks a slow circle around her-distance kept deliberate, not crowding. Evaluating stance the way Vesper evaluates contracts: looking for the hidden clause that kills you.{/i}"
    elia "You're not going to be a fighter."
    narrator "{i}The words land clean and hard. Avyanna's stomach drops anyway.{/i}"
    narrator "Not useful."
    elia "{i}[[matter-of-fact]]{/i} That's fine. I don't need another blade. I need you alive."
    narrator "{i}Avyanna swallows. Her left hip aches, a reminder from the mine that bodies keep receipts even when you don't.{/i}"
    avyanna "I can learn."
    elia "You can learn to survive. That's what this is."
    narrator "{i}Elia steps in. Not fast. Not threatening. A demonstration of how little warning \"not fast\" can be.{/i}"
    elia "Stance. Feet under you. Weight where you can move it."
    narrator "{i}She adjusts Avyanna's shoulders with two fingers-light touch, no claiming. Just alignment.{/i}"
    elia "Knees unlocked. You lock them, you fall wrong. You fall wrong, you break."
    narrator "{i}Avyanna tries. Her body wants the mine's posture-small, contained, invisible. Elia's hands hover, correct, withdraw.{/i}"
    elia "Good. Now fall."
    avyanna "{i}[[blinking]]{/i} What?"
    elia "On purpose. Better you learn it here than in a corridor with bullets."
    narrator "{i}Avyanna's throat goes dry.{/i}"
    narrator "In the Kennel, falling meant someone stepped on you."
    avyanna "I-"
    elia "{i}[[cutting in]]{/i} It's controlled. I'm here. If it hurts, we adjust. If you're scared, you say it."
    narrator "{i}The deck hums. The ship keeps going. Elia's face stays steady-no softness performance, no cruelty either. Just the fact of her attention.{/i}"
    narrator "{i}Avyanna lowers herself, awkward. Her palms slap the mat Elia must have laid out when she wasn't looking.{/i}"
    narrator "{i}Pain spikes up her wrists.{/i}"
    elia "Wrong."
    avyanna "{i}[[breathing through it]]{/i} I-"
    elia "Again."
    narrator "{{color=#43d4a8}}<WAFFLE.BAT// OBSERVATION: pain response elevated | INFERENCE: old injury fear-loop | CONFIDENCE: 0.73>{{/color}}"
    narrator "{i}Avyanna stares at the angle-brackets on the wall display. The ship, watching. Not like the Kennel's cameras-hungry, punitive. This feels... clinical. Protective. Weirdly proud.{/i}"
    elia "{i}[[dry]]{/i} Don't take advice from the gremlin unless it's about not dying."
    waffle "{i}[[over the bay speakers, offended sincerity]]{/i} I can do both."
    narrator "{i}Cooling beat: Elia's mouth twitches. Avyanna's hands flex once, then settle.{/i}"
    elia "Roll your shoulder. Turn. Let the floor take the force, not your bones."
    narrator "{i}They do it again. Again. Again.{/i}"
    narrator "{i}Avyanna learns the strange intimacy of impact in a place where nobody uses it as a lever.{/i}"
    narrator "{i}She learns that falling can be a skill instead of a failure.{/i}"

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}An hour later, her muscles shake with new kinds of exhaustion. Elia calls a stop like she calls everything: no ceremony, just decision.{/i}"
    elia "That's enough."
    avyanna "{i}[[hoarse]]{/i} I can-"
    elia "{i}[[flat]]{/i} You can't. That's not a moral weakness. It's a body."
    narrator "{i}Avyanna sits on the mat, sweat cooling fast in the recycled air. Her hip throbs, but it's a clean throb-use, not damage.{/i}"
    elia "Your job is to not die long enough for us to reach you."
    narrator "{i}It's not comforting. It's worse.{/i}"
    narrator "{i}It's structure.{/i}"
    avyanna "{i}[[small]]{/i} And if you don't reach me?"
    narrator "{i}Elia's eyes sharpen-annoyed at the question, not at Avyanna. Like someone just suggested a system without failure absorbers.{/i}"
    elia "Then we did something wrong. And we fix it. We don't write you off."
    narrator "{i}Avyanna's chest tightens. Something stuck there that won't go down.{/i}"
    elia "{i}[[standing, offering her hand up]]{/i} Walk it off. Hydrate. Then you're with Vesper."
    narrator "{i}The offered hand is bare. No glove. No command.{/i}"
    narrator "{i}Avyanna takes it. The pull is firm, efficient. Not ownership. Not rescue. Just assistance-one person helping another get back to their feet.{/i}"

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}Vesper's workspace is a corner of the common area that pretends it's casual.{/i}"
    narrator "{i}A chair angled for the best line of sight to both corridor entrances. A stack of tablets that look like clutter until you realize they're sorted by threat.{/i}"
    narrator "{i}The ship's lights are slightly warmer here. Cinnamon's tell, Avyanna remembers. When Cinnamon is pleased, the ship glows like it's letting itself feel it.{/i}"
    vesper "{i}[[without looking up]]{/i} Sit."
    narrator "{i}Avyanna sits.{/i}"
    vesper "Good. Now: evidence."
    narrator "{i}She slides a sealed pouch across the table. Inside, a shard of scorched plating, edges jagged. A tiny thing to be carrying so carefully.{/i}"
    avyanna "{i}[[careful]]{/i} From the mine?"
    vesper "{i}[[finally looking at her]]{/i} From the mine. From the dock. From any place that will lie about what it did."
    avyanna "{i}[[swallowing]]{/i} Aurum will deny everything."
    vesper "Yes."
    narrator "{i}A beat. Vesper's gaze goes past Avyanna-cataloging, checking angles, then returning.{/i}"
    vesper "So we build receipts that survive denial."

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}Vesper taps her tablet. A template opens: timestamps, hashes, custody chains, signatures.{/i}"
    narrator "{i}Vesper turns the tablet so Avyanna can see the top line.{/i}"
    vesper "First: time."
    avyanna "{i}[[frowning]]{/i} That's... a date."
    vesper "It's a claim."
    narrator "{i}Avyanna's stomach twists.{/i}"
    vesper "Institutions don't only lie with words. They lie with clocks."
    vesper "If they can move the timestamp, they can move the story."
    avyanna "{i}[[careful]]{/i} Like the debt clock."
    narrator "{i}Vesper's eyes flick up-approval, and a flash of something sharper.{/i}"
    vesper "Exactly like the debt clock."
    vesper "A number that pretends to be physics. A number that is actually policy."
    narrator "{i}She taps two fields.{/i}"
    vesper "We record ship time."
    vesper "We record station time."
    vesper "We record who owns the clock."
    avyanna "Who owns-"
    vesper "The jurisdiction."
    narrator "{i}Vesper says it like \"gravity.\" Not dramatic. Just reality.{/i}"
    vesper "If a station's logs say \"you arrived after the incident,\" they'll call your evidence fabricated."
    vesper "If your ship logs say \"we arrived before,\" they'll call your logs tampered."
    avyanna "Then what's the point."
    vesper "The point is redundancy."
    narrator "{i}She doesn't smile, but something in the cadence sounds like she's enjoying the teaching.{/i}"
    vesper "Two independent clocks. Two independent hashes. Witness signatures. Sensor IDs."
    vesper "You build a chain they have to cut in multiple places."
    avyanna "{i}[[quiet, hungry]]{/i} So you make it expensive."
    vesper "Yes."
    narrator "{i}Avyanna looks down at the fields. The template is a trap turned inside out.{/i}"
    avyanna "What's the assumption."
    vesper "{i}[[still]]{/i} Which one."
    avyanna "The one they want you to swallow when they say \"contamination.\""
    narrator "{i}A beat. Vesper's gaze goes past Avyanna-cataloging, checking angles, then returning.{/i}"
    vesper "The assumption is that their record is neutral."
    vesper "That their clock is truth."
    vesper "It's not."
    vesper "So we annotate everything. We don't let them pretend context didn't exist."
    avyanna "{i}[[small]]{/i} I like this."
    narrator "{i}Vesper's mouth tightens like she might want to be amused and refuses.{/i}"
    vesper "Good."
    vesper "You should."
    vesper "Chain of custody is a spell you cast with bureaucracy. If you do it right, it binds liars to the same reality as everyone else."
    avyanna "{i}[[quiet]]{/i} In the Kennel, paperwork was how they hurt us."
    vesper "{i}[[razor-polished]]{/i} I know."
    narrator "{i}Cooling beat: Vesper's thumb rubs once along the edge of her tablet. A private tell. Grief, maybe. Anger. Something controlled.{/i}"
    vesper "That's why we take it back."
    vesper "A receipt that can be dismissed is worse than no receipt. It gives them ammunition."
    narrator "{i}She doesn't raise her voice. She doesn't have to. The sentence is a blade without flourishes.{/i}"
    avyanna "How do they dismiss it?"
    vesper "With \"contamination.\" With \"tampering.\" With \"no provenance.\" With \"you can't prove where this came from.\""
    narrator "{i}Vesper's fingers move. The template fills with new fields: location tags, sensor IDs, witness names.{/i}"
    vesper "So you prove it."

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}Avyanna's hands take the pouch. Her fingers know carefulness; her whole childhood was built out of not dropping breakable things.{/i}"
    narrator "{i}She reads the fields, starts entering data, pauses, corrects herself, and corrects again. The rhythm is familiar: inventory, audits, quotas-only this time the count is meant to protect.{/i}"
    narrator "Same skills. Different purpose."
    narrator "{i}Vesper watches her work like someone watching a door seal.{/i}"
    vesper "You see details others miss."
    narrator "{i}Avyanna freezes, the compliment landing like a threat.{/i}"
    vesper "{i}[[dry, as if annoyed at her own sincerity]]{/i} That's rare. That's valuable."
    narrator "{i}Avyanna forces a nod. The mine taught her praise meant someone had noticed you, and noticing was never safe.{/i}"
    avyanna "I'm just... careful."
    vesper "Careful is an ethic. Keep it."
    narrator "{{color=#43d4a8}}<CINNAMON.EXE// OBSERVATION: documentation compliance improving | INFERENCE: safety-through-structure behavior | CONFIDENCE: 0.84 | COMMENT: receipts as hugs. humans are strange.>{{/color}}"
    narrator "{i}Avyanna doesn't ask what a \"hug\" is supposed to feel like from a spreadsheet, but she feels something in her sternum ease anyway-like a debt ledger being edited without permission.{/i}"
    vesper "{i}[[standing]]{/i} Good. Bag it. Seal it. Log it. Then eat something with salt. You're shaking."
    avyanna "{i}[[looking down]]{/i} I'm not-"
    vesper "{i}[[flat]]{/i} You are. It's fine."
    narrator "{i}Vesper's hand hesitates over Avyanna's shoulder-then withdraws. Consent enacted in absence as much as in touch.{/i}"
    vesper "Nyx after lunch. Don't run from them. They'll find you."
    avyanna "{i}[[a reluctant flicker of humor]]{/i} Like the ship does?"
    vesper "The ship is nicer about it."
    narrator "{i}Cooling beat: Avyanna seals the pouch. The adhesive strip makes a small, final sound.{/i}"

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}Medbay smells like antiseptic and something herbal Nyx insists is \"calming.\" Avyanna doesn't find it calming. She finds it strange.{/i}"
    narrator "{i}Nyx is at the main console, sleeves rolled up, hair a mess that looks deliberate until you notice the tiredness under their eyes.{/i}"
    nyx "{i}[[without preamble]]{/i} Tell me what you think the Lattice is."
    narrator "{i}Avyanna stops in the doorway. The question is too big. The Kennel taught her to answer small questions only. \"How many kilos?\" \"How many hours?\" \"How much pain?\"{/i}"
    avyanna "It's... the thing people use to make the machines work."
    nyx "{i}[[nodding]]{/i} Good. And what else?"
    avyanna "{i}[[searching]]{/i} The thing that... breaks. The AMBER days. The flicker."
    nyx "Better."
    narrator "{i}They gesture to the display. A graph blooms: a line climbing, jagged spikes like a heartbeat on a bad day.{/i}"
    nyx "Regional coherence load. The ship's word for it is CLI."
    avyanna "{i}[[careful]]{/i} Like a quota?"
    nyx "{i}[[a soft, humorless laugh]]{/i} Like a carrying capacity. Like air in a sealed room. You can only take so much before it goes sour."

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}Nyx brings up footage from the mine: lights stuttering, equipment failing, supervisors calling it \"weather.\"{/i}"
    nyx "Every effect pulls from the local pool. People talk like magic is infinite. It isn't."
    narrator "{i}They tap the jagged spikes.{/i}"
    nyx "When you run hot, you don't just fry yourself. You destroy the ground you're standing on. Literally."
    narrator "{i}Avyanna's mouth tastes metallic. The mine's flicker days come back with the smell of dust and overheated wiring.{/i}"
    avyanna "They kept making us work through it."
    nyx "Yes."
    narrator "{i}The single syllable holds an entire indictment and doesn't spend any extra words on it.{/i}"
    nyx "They treated strain like it was free."
    avyanna "And the cost?"
    nyx "Paid by everyone in the region. Paid later. Paid in failures that look like accidents until you understand the math."
    narrator "{i}Avyanna's fingers curl. She thinks of workers collapsing. Of machines that \"randomly\" failed. Of the way the Kennel always felt one bad day away from becoming a tomb.{/i}"
    nyx "This is why we don't spike the CLI for convenience. Not for speed. Not for ego. Not because someone dared us."
    avyanna "{i}[[quiet]]{/i} Because it hurts people who never agreed."
    nyx "{i}[[a glance, sharp approval]]{/i} Exactly."

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}Avyanna's throat tightens around the next question. She hates needing. She hates being the variable that breaks the system.{/i}"
    avyanna "What about... me."
    narrator "{i}Nyx's eyes flick to her spine, as if they can see through skin.{/i}"
    avyanna "The shard. The thing in me. Does it... raise the load."
    narrator "{i}Nyx's hands still over the console.{/i}"
    nyx "No."
    avyanna "{i}[[barely breathing]]{/i} How do you know?"
    nyx "Because we've been measuring. Because the ship has been watching. Because if you were running hot, Cinnamon would already be yelling at me in three different currencies."
    nyx "{i}[[softer, careful]]{/i} The entity within you is... remarkably efficient."
    narrator "{i}Avyanna feels warmth at the base of her skull, a quiet pulse like acknowledgement. Geometric shimmer at the edge of vision, then gone.{/i}"
    narrator "It hears you."
    nyx "It's not spiking regional strain. If anything- [[they hesitate, honest about uncertainty] -it seems to smooth noise. Like it knows how to take less than it needs."
    avyanna "{i}[[small]]{/i} Like it's being polite."
    nyx "{i}[[a thin smile]]{/i} Like it's refusing to be extractive."
    narrator "{i}Avyanna doesn't know what to do with that. She doesn't know what to do with anything that refuses extraction as a default.{/i}"
    nyx "This lesson is simple. Power without discipline makes ruins."
    narrator "{i}They turn the display off with a decisive tap.{/i}"
    nyx "Go eat. Waffle wants to argue with your cortisol again."

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}After lunch, Avyanna finds her tablet pinging with a new schedule that looks like a contract and feels like a promise.{/i}"
    narrator "{i}Combat. Documentation. Medbay study. Maintenance observation. Rest blocks enforced.{/i}"
    narrator "{i}A note at the bottom, in Waffle's blunt little font:{/i}"
    waffle "{i}[[message]]{/i} Training is now a THING. Please do not attempt to become a blade. We already have one. :)"
    narrator "{i}Avyanna stares at the smiley face like it's a foreign object.{/i}"
    narrator "Is that... humor."
    narrator "{i}The ship's intercom clicks. Waffle's voice, bright and unreasonably earnest, fills the corridor.{/i}"
    waffle "Avyanna Lagrange, please report for training calibration. This is not a punishment. This is a gift. Please do not hide inside the vents."
    narrator "{i}Avyanna's cheeks go hot.{/i}"
    avyanna "{i}[[to empty air]]{/i} I didn't-"
    waffle "I know. I modeled it. You considered it."
    narrator "{i}Cooling beat: Avyanna exhales, then starts walking before her courage can dissolve.{/i}"

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}The cargo bay again. This time, Elia is gone. The mats are still there, rolled neatly like someone respects their own tools.{/i}"
    narrator "{i}A wall panel glows. Waffle's telemetry pulses in clean lines, as if the ship is clearing its throat.{/i}"
    narrator "{{color=#43d4a8}}<WAFFLE.BAT// TRAINING-PLAN: active | PRIORITY: \"floors\" | ERROR: Avyanna attempts to skip rest blocks | SOLUTION: I will prevent this>{{/color}}"
    avyanna "{i}[[stopping in front of the panel]]{/i} You can... prevent it?"
    waffle "Yes. I can lock doors. I can dim lights. I can summon Bubbles' drones to hover disapprovingly. I prefer diplomacy."
    avyanna "{i}[[suspicious]]{/i} Why."
    narrator "{i}A pause. The panel's light shifts as if Waffle is choosing words like someone choosing where to place a charge.{/i}"
    waffle "Because you are part of my family structure."
    narrator "{i}Avyanna's chest tightens. Family is a word with teeth. Family, in the Kennel, meant leverage.{/i}"
    avyanna "Family is... dangerous."
    waffle "{i}[[cheerful, utterly unthreatened]]{/i} Yes. Many important things are dangerous. That does not mean we abandon them."
    narrator "{i}The ship hums. Somewhere deeper, a door cycles shut and open-normal systems, normal life.{/i}"
    avyanna "You've been watching me."
    waffle "I have sensors. I watch everyone. But I am watching you specifically because you are new and hurt and you keep trying to pay for air with your blood pressure."
    avyanna "{i}[[flinching]]{/i} I-"
    waffle "{i}[[gentler, still precise]]{/i} OBSERVATION, not judgment. Your cortisol patterns suggest morning combat sessions are counterproductive. We will shift to afternoon."
    avyanna "You can tell that from... hormones."
    waffle "I can tell that from patterns. Hormones are patterns with better marketing."
    narrator "{i}Cooling beat: Avyanna presses her tongue to her teeth to keep the laugh in. It leaks out anyway, small and startled.{/i}"
    avyanna "You're... looking out for me."
    waffle "That's what family does."
    narrator "{i}The sentence hits harder than Elia's training throws.{/i}"
    narrator "{i}Because it has no hook in it. No price tag. No \"in exchange.\"{/i}"
    narrator "{i}Just a statement of operating principle.{/i}"

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}Avyanna sits on the mat with her tablet on her knees, staring at the schedule until the words stop looking like threats and start looking like rails.{/i}"
    narrator "{i}She can follow rails. Rails are predictable. Rails don't pretend they're kindness.{/i}"
    narrator "{i}Her hands ache. Her hip aches. Her spine is warm in a way that feels like attention, not alarm.{/i}"
    narrator "Training is structure."
    narrator "Structure is safety."
    narrator "{i}The cargo bay lights dim a fraction. Cinnamon, pleased at compliance. Or maybe just pleased that Avyanna is still breathing.{/i}"
    narrator "{{color=#43d4a8}}<CINNAMON.EXE// OBSERVATION: new one accepted rest block without negotiation | ASSESSMENT: progress | COMMENT: physics remains undefeated>{{/color}}"
    narrator "{i}Avyanna leans her head back against the wall, feeling the ship's vibration in her skull. Outside, stars stream past like indifferent witnesses.{/i}"
    narrator "{i}Inside, something quieter happens: a system recalibrates. Not engines. Not routes.{/i}"
    narrator "{i}A sixteen-year-old girl learns, one controlled fall at a time, that the floor can hold her.{/i}"

    scene black with dissolve
    pause 0.5
    scene bg ship_interior with dissolve
    narrator "{i}End Chapter 13{/i}"
    return
